Repository primefaces/primereact, pull requests merged in 2022-11, with the labels that each got.

#3524 Fix #3498: Non-responsive toast.
  components/lib/toast/Toast.css
Labels: Type: Bug

#3547 Fix #3545: Calendar set range programmatically
  components/lib/calendar/Calendar.js
Labels: Core Team

#3549 Fix #3546: Splitter error with only 1 panel
  components/lib/splitter/Splitter.js
Labels: Core Team

#3562 Fix #3548: Field data with dot in name
  components/lib/utils/ObjectUtils.js
Labels: Core Team

#3558 Add jest unit testing to Chip component
  components/lib/chip/Chip.spec.js
  package.json
Labels: Component: Test

#3570 Fix #3569: Tooltip Jest tests
  components/lib/tooltip/Tooltip.js
  components/lib/tooltip/Tooltip.spec.js
  components/lib/utils/utils.d.ts
Labels: Core Team

#3574 Fix #3573: Allow value to be set programatically
  components/lib/inputtext/inputtext.d.ts
  components/lib/inputtextarea/inputtextarea.d.ts
Labels: Core Team

#3591 Fix #3590: TieredMenu hide on leaf click
  components/lib/tieredmenu/TieredMenu.js
  components/lib/tieredmenu/TieredMenuSub.js
Labels: Core Team

#3579 Divider: switch to snapshot tests
  components/lib/divider/Divider.spec.js
  components/lib/divider/__snapshots__/Divider.spec.js.snap
Labels: Component: Test

#3605 Fix #3595: Add maxLength prop to InputNumber Component.
  api-generator/components/autocomplete.js
  api-generator/components/inputmask.js
  api-generator/components/inputnumber.js
  components/doc/autocomplete/apidoc.js
  components/doc/inputmask/apidoc.js
  components/doc/inputnumber/apidoc.js
  components/lib/inputnumber/InputNumber.js
  components/lib/inputnumber/inputnumber.d.ts
Labels: Type: New Feature

#3609 Fix #3608: Ripple and Message jest tests
  components/lib/button/Button.spec.js
  components/lib/button/__snapshots__/Button.spec.js.snap
  components/lib/message/Message.spec.js
  components/lib/message/__snapshots__/Message.spec.js.snap
  components/lib/progressbar/ProgressBar.spec.js
  components/lib/ripple/Ripple.spec.js
  components/lib/ripple/__snapshots__/Ripple.spec.js.snap
  components/test/index.js
Labels: Core Team

#2772 Fix #2671: Showcase store theme in local storage
  pages/_app.js
Labels: Status: Pending Review

#3611 Fix #3610: Panel, FieldSet, Card jest tests
  components/lib/badge/Badge.spec.js
  components/lib/card/Card.spec.js
  components/lib/card/__snapshots__/Card.spec.js.snap
  components/lib/fieldset/Fieldset.spec.js
  components/lib/fieldset/__snapshots__/Fieldset.spec.js.snap
  components/lib/panel/Panel.spec.js
  components/lib/panel/__snapshots__/Panel.spec.js.snap
Labels: Core Team

#3612 Fix #3029: InputNumber when overwriting with suffix
  components/lib/inputnumber/InputNumber.js
  components/lib/utils/ObjectUtils.js
Labels: Core Team

#3615 Fix #2871: InputNumber duplicating suffix when using decimals
  components/lib/inputnumber/InputNumber.js
Labels: Core Team

#3619 Enforce minimum Node engine in package.json
  package-lock.json
  package.json
Labels: Core Team

#3622 Fix #3621: BlockUI Jest test
  components/doc/rating/templatedoc.js
  components/lib/blockui/BlockUI.spec.js
  components/lib/blockui/__snapshots__/BlockUI.spec.js.snap
  components/test/index.js
Labels: Core Team

#3625 Fix #2588: Tooltip add position=mouse
  api-generator/components/tooltip.js
  components/doc/tooltip/index.js
  components/lib/tooltip/Tooltip.js
  components/lib/tooltip/tooltipoptions.d.ts
  pages/tooltip/index.js
Labels: Core Team

#3627 Fix #3626: Splitter/ScrollPanel Jest tests
  components/lib/scrollpanel/ScrollPanel.spec.js
  components/lib/scrollpanel/__snapshots__/ScrollPanel.spec.js.snap
  components/lib/splitter/Splitter.spec.js
  components/lib/splitter/__snapshots__/Splitter.spec.js.snap
  package-lock.json
  package.json
Labels: Core Team

#3630 Fix #3629: Calendar value typescript def
  components/lib/calendar/calendar.d.ts
Labels: Core Team

#3637 Fix #3636: Radiobutton fire onChange only if changed
  components/lib/radiobutton/RadioButton.js
Labels: Core Team

#3639 Fix #3638: ConfirmDialog showcase example render correctly
  components/doc/confirmdialog/basicdoc.js
  components/doc/confirmdialog/positiondoc.js
  components/doc/confirmdialog/usingdoc.js
  components/doc/inputtextarea/autoresizedoc.js
  components/doc/tabview/customheaderdoc.js
  components/doc/toolbar/toolbardoc.js
  pages/confirmdialog/index.js
Labels: Core Team

#3640 Fix #3635: InputTextarea/InputText proper typescript def
  components/lib/inputmask/inputmask.d.ts
  components/lib/inputnumber/inputnumber.d.ts
  components/lib/inputtext/inputtext.d.ts
  components/lib/inputtextarea/inputtextarea.d.ts
  components/lib/mention/mention.d.ts
  components/lib/password/password.d.ts
Labels: Core Team

#3642 Fix #3641: Checkbox fix disabled pointer
  components/lib/checkbox/Checkbox.css
  components/lib/multistatecheckbox/MultiStateCheckbox.js
  components/lib/tristatecheckbox/TriStateCheckbox.js
Labels: Core Team

#3650 Fix #3465: React hook form Password example
  pages/reacthookform/index.js
Labels: Core Team

#3648 Fix #3647: Image fallback URL if there is an error
  api-generator/components/avatar.js
  components/doc/avatar/index.js
  components/lib/avatar/Avatar.js
  components/lib/avatar/avatar.d.ts
  pages/avatar/index.js
Labels: Core Team

#3651 Typescript doc fixes
  components/doc/dialog/basicdoc.js
  components/doc/dialog/maximizabledoc.js
  components/doc/dialog/positiondoc.js
  components/doc/dialog/responsivedoc.js
  components/doc/dialog/withoutmodaldoc.js
  components/doc/overlaypanel/overlaypaneldoc.js
  components/doc/tooltip/positionsdoc.js
Labels: Component: Documentation

#3652 Fix #3643: RowGroupHeaderTemplate allow custom rendering
  components/lib/datatable/TableBody.js
  components/lib/datatable/datatable.d.ts
Labels: Core Team

#3658 Fix #3649: Listbox emptyMessage, emptyFilterMessage
  api-generator/components/listbox.js
  components/doc/listbox/apidoc.js
  components/lib/listbox/ListBox.js
  components/lib/listbox/listbox.d.ts
Labels: Core Team

#3664 Fix #3476: DataTable: TypeError when adding and starting editing a new row
  components/lib/datatable/BodyCell.js
Labels: Type: Bug

#3667 Fix #1883: Orderlist Drag and Drop
  components/lib/orderlist/OrderList.css
  components/lib/orderlist/OrderListSubList.js
Labels: Core Team

#3675 Fix #3659: AutoComplete use deepEquals for comparison
  components/lib/autocomplete/AutoComplete.js
Labels: Core Team

#3684 Fix #3683: BlockUI add containerStyle, containerClassName
  api-generator/components/blockui.js
  components/doc/blockui/index.js
  components/lib/blockui/BlockUI.js
  components/lib/blockui/BlockUI.spec.js
  components/lib/blockui/__snapshots__/BlockUI.spec.js.snap
  components/lib/blockui/blockui.d.ts
Labels: Core Team

#3691 Fix #3689: TreeTable body cell error
  components/lib/treetable/TreeTableBodyCell.js
Labels: Core Team

#3697 Fix #3694: Update responsive style on scrollable change
  components/lib/datatable/DataTable.js
Labels: Core Team

#3705 Fix #1945/#3703: onRowMouseEnter/onRowMouseLeave
  api-generator/components/datatable.js
  components/doc/datatable/index.js
  components/lib/datatable/BodyRow.js
  components/lib/datatable/DataTable.js
  components/lib/datatable/TableBody.js
  components/lib/datatable/datatable.d.ts
Labels: Core Team

#3707 Fix #1396: onValueChanged called on filter state change
  components/lib/datatable/DataTable.js
Labels: Core Team

#3708 Fix #3302: Multiselect add overlayVisible property
  api-generator/components/multiselect.js
  components/doc/multiselect/apidoc.js
  components/lib/multiselect/MultiSelect.js
  components/lib/multiselect/multiselect.d.ts
Labels: Core Team

#3713 Fix #3712: PrimeReact.nullSortOrder working properly
  components/lib/utils/ObjectUtils.js
Labels: Core Team

#3709 Fix #2042: Dialog better handling of draggable
  components/lib/dialog/Dialog.js
  components/lib/hooks/Hooks.js
  components/lib/hooks/hooks.d.ts
  components/lib/hooks/useDraggable.js
  components/lib/utils/DomHandler.js
Labels: Core Team

#3719 Fix #2318: ContextMenu submenu collision detection
  components/lib/contextmenu/ContextMenuSub.js
Labels: Core Team

#3722 Fix #3721: MultiSelect add filterInputAutoFocus
  api-generator/components/multiselect.js
  components/doc/multiselect/apidoc.js
  components/lib/multiselect/MultiSelect.js
  components/lib/multiselect/MultiSelectHeader.js
  components/lib/multiselect/MultiSelectPanel.js
  components/lib/multiselect/multiselect.d.ts
Labels: Core Team

#3723 Fix #3721: Remove filterInputAutoFocus
  api-generator/components/multiselect.js
  components/doc/multiselect/apidoc.js
  components/lib/multiselect/MultiSelect.js
  components/lib/multiselect/MultiSelectPanel.js
  components/lib/multiselect/multiselect.d.ts
Labels: Core Team
