Repository primefaces/primereact, pull requests merged in 2022-08, with the labels that each got.

#2563 Fix #2562: Sidebar allow dismissable on non-modal
  components/doc/sidebar/index.js
  components/lib/sidebar/Sidebar.js
  pages/sidebar/index.js
Labels: discussion

#3102 Refactor KeyFilter
  components/lib/keyfilter/KeyFilter.js
Labels: pending-review

#3185 Fix #3184: Dialog responsive breakpoints restored
  components/lib/dialog/Dialog.js
Labels: Core Team

#3186 Fix #3172: InputTextArea/InputText typescript updates
  components/lib/inputtext/inputtext.d.ts
  components/lib/inputtextarea/inputtextarea.d.ts
Labels: Core Team

#3187 Fix #3166: Dialog remove blockScroll on exit
  components/lib/dialog/Dialog.js
Labels: Core Team

#3194 Fix #3193: Button/SplitButton visible property
  api-generator/components/button.js
  api-generator/components/splitbutton.js
  components/doc/button/index.js
  components/doc/splitbutton/index.js
  components/lib/button/Button.js
  components/lib/button/button.d.ts
  components/lib/splitbutton/SplitButton.js
  components/lib/splitbutton/splitbutton.d.ts
  pages/button/index.js
Labels: Core Team

#3195 Fix #3192: Calendar monthpicker fix for disabled dates
  components/lib/calendar/Calendar.js
Labels: Core Team

#3198 Fix #3197: Confirm Dialog/Popup only callback once
  components/lib/confirmdialog/ConfirmDialog.js
  components/lib/confirmpopup/ConfirmPopup.js
  components/lib/utils/ObjectUtils.js
Labels: Core Team

#3199 Fix #3200 Add Generics to Dropdown, Cascadeselect, Listbox, Multiselect, Selectbutton
  components/lib/cascadeselect/cascadeselect.d.ts
  components/lib/dropdown/dropdown.d.ts
  components/lib/listbox/listbox.d.ts
  components/lib/multiselect/multiselect.d.ts
  components/lib/selectbutton/selectbutton.d.ts
  components/lib/selectitem/selectitem.d.ts
Labels: TypeScript

#3208 Fix #3202: ConfirmDialog/Popup return JSON not array
  components/lib/confirmdialog/ConfirmDialog.js
  components/lib/confirmpopup/ConfirmPopup.js
Labels: Core Team

#2766 Fix #1392/#1296: AutoComplete shows "[object Object]"
  components/lib/autocomplete/AutoComplete.js
Labels: Status: Pending Review

#3123 Fix #3122: Dialog/Sidebar/Overlay prevent animation flickering
  components/lib/dialog/Dialog.css
  components/lib/overlaypanel/OverlayPanel.css
  components/lib/sidebar/Sidebar.css
Labels: Core Team
