Repository primefaces/primereact, pull requests merged in 2022-10, with the labels that each got.

#3399 Fix #3397: SlideMenu expose navigate methods
  components/doc/slidemenu/index.js
  components/lib/slidemenu/SlideMenu.js
  components/lib/slidemenu/slidemenu.d.ts
Labels: Core Team

#3400 Fix #1450: Datatable/Treetable add globalFilterMatchMode
  api-generator/components/datatable.js
  api-generator/components/treetable.js
  components/doc/datatable/index.js
  components/doc/treetable/index.js
  components/lib/datatable/DataTable.js
  components/lib/datatable/datatable.d.ts
  components/lib/treetable/TreeTable.js
  components/lib/treetable/treetable.d.ts
Labels: Core Team

#3411 Fix #3398/#3407: SlideMenu add onNavigate, setLevelState
  api-generator/components/slidemenu.js
  components/doc/slidemenu/index.js
  components/lib/slidemenu/SlideMenu.js
  components/lib/slidemenu/slidemenu.d.ts
Labels: Core Team

#3412 Fix #3388: CellSelection with metakey row index
  components/lib/datatable/TableBody.js
Labels: Core Team

#3416 Fix #3413: Splitter strict mode rendering
  components/lib/splitter/Splitter.js
Labels: Core Team

#3424 Fix #3423: AutoComplete readonly in multiple mode
  components/lib/autocomplete/AutoComplete.js
Labels: Core Team

#3434 Fix #3432: Dialog maximized restore scrollbar
  components/lib/dialog/Dialog.js
  components/lib/dialog/dialog.d.ts
Labels: Core Team

#3417 Fix #3388: Cell selection with metakey
  components/lib/datatable/TableBody.js
Labels: Core Team

#3437 Fix #3430/#2996: Datatable global filter has old value
  components/lib/datatable/DataTable.js
Labels: Core Team

#3438 Fix #3433: Progressbar dynamic progress bar
  components/lib/progressbar/ProgressBar.css
  components/lib/progressbar/ProgressBar.js
Labels: Core Team

#3439 Fix #3215: BodyClassName allow function with rowData
  components/doc/datatable/index.js
  components/lib/column/column.d.ts
  components/lib/datatable/BodyCell.js
  components/lib/treetable/TreeTableBodyCell.js
Labels: Core Team

#3441 Fix #3440: Change style from object to React.CSSProperties
  components/lib/accordion/accordion.d.ts
  components/lib/autocomplete/autocomplete.d.ts
  components/lib/calendar/calendar.d.ts
  components/lib/cascadeselect/cascadeselect.d.ts
  components/lib/chart/chart.d.ts
  components/lib/checkbox/checkbox.d.ts
  components/lib/column/column.d.ts
  components/lib/confirmpopup/confirmpopup.d.ts
  components/lib/datatable/datatable.d.ts
  components/lib/dataview/dataview.d.ts
  components/lib/dialog/dialog.d.ts
  components/lib/dropdown/dropdown.d.ts
  components/lib/editor/editor.d.ts
  components/lib/fileupload/fileupload.d.ts
  components/lib/inputnumber/inputnumber.d.ts
  components/lib/inputswitch/inputswitch.d.ts
  components/lib/knob/knob.d.ts
  components/lib/listbox/listbox.d.ts
  components/lib/mention/mention.d.ts
  components/lib/menuitem/menuitem.d.ts
  components/lib/multiselect/multiselect.d.ts
  components/lib/multistatecheckbox/multistatecheckbox.d.ts
  components/lib/orderlist/orderlist.d.ts
  components/lib/password/password.d.ts
  components/lib/picklist/picklist.d.ts
  components/lib/row/row.d.ts
  components/lib/scrolltop/scrolltop.d.ts
  components/lib/sidebar/sidebar.d.ts
  components/lib/speeddial/speeddial.d.ts
  components/lib/splitbutton/splitbutton.d.ts
  components/lib/splitter/splitter.d.ts
  components/lib/tabview/tabview.d.ts
  components/lib/toast/toast.d.ts
  components/lib/tooltip/tooltipoptions.d.ts
  components/lib/tree/tree.d.ts
  components/lib/treenode/treenode.d.ts
  components/lib/treeselect/treeselect.d.ts
  components/lib/treetable/treetable.d.ts
  components/lib/virtualscroller/virtualscroller.d.ts
Labels: Core Team

#3442 Fix #2987: Datascroller do not reset first on lazy
  components/lib/datascroller/DataScroller.js
  components/lib/datascroller/datascroller.d.ts
Labels: Core Team

#3443 Fix #2918: RowExpander allow function using rowData
  components/lib/column/column.d.ts
  components/lib/datatable/BodyCell.js
  pages/datatable/rowexpand.js
Labels: Core Team

#3457 Fix #3455: Toast add remove method
  components/lib/toast/Toast.js
  components/lib/toast/toast.d.ts
Labels: Core Team

#3460 Fix #3453: Button typescript def remove getElement
  components/lib/button/button.d.ts
Labels: Core Team

#3468 Fix #3467: Autocomplete dropdownAriaLabel
  components/lib/autocomplete/AutoComplete.js
  components/lib/autocomplete/autocomplete.d.ts
Labels: Core Team

#3471 Fix #3469: ColumnEventParams fix typescript
  components/lib/column/column.d.ts
Labels: Core Team

#3472 Fix #3470: Datatable custom restore state column fix
  components/lib/datatable/DataTable.js
Labels: Core Team

#3473 Fix #2677: InputNumber invalid $refs
  components/lib/inputnumber/InputNumber.js
Labels: Core Team

#3482 Fix #3483: Splitter: Non optimal handling of splitter sizing
  components/lib/splitter/Splitter.js
Labels: Status: Pending Review

#3485 Fix #3484: Calendar update inputfield if popup is displayed
  components/lib/calendar/Calendar.js
Labels: Core Team

#3493 Fix #3492: CONTRIBUTING - Wrong forum url
  CONTRIBUTING.md
Labels: Component: Documentation

#3494 Fix #3489: Paginator should respect props.first
  components/lib/paginator/Paginator.js
Labels: Core Team

#3499 Fix #3497: Ripple fix for touchable devices
  components/lib/ripple/Ripple.js
Labels: Core Team

#3505 Fix #3503: PaginatorTemplateOptions interface elements should be opti…
  components/lib/paginator/paginator.d.ts
Labels: Type: Enhancement

#3507 Fix #3506: Listbox typescript fixes
  components/lib/listbox/listbox.d.ts
Labels: Core Team

#3510 Fix #3509: Timeline - Add missing type of align as enum.
  components/lib/timeline/timeline.d.ts
  package-lock.json
Labels: typescript, Core Team

#3530 Fix #3526: Ripple fixes for TouchStart
  components/lib/ripple/Ripple.js
Labels: Core Team

#3538 Fix #3533: Add unit tests to nightly and PR builds
  .github/workflows/node.js.yml
  package.json
Labels: Component: Test, Core Team
