Repository primefaces/primereact, pull requests merged in 2022-12, with the labels that each got.

#3737 Fix #2837: TieredMenu/ContextMenu height handling
  components/lib/contextmenu/ContextMenuSub.js
  components/lib/tieredmenu/TieredMenuSub.js
Labels: Core Team

#3739 Fix #3738: Slider replace 0/100 with min/max values
  components/lib/slider/Slider.js
Labels: Core Team

#3741 Fix #3463: AutoComplete align overlay panel
  components/lib/autocomplete/AutoComplete.js
Labels: Core Team

#3745 Fix #3744 : fix index type of AccordionEventParams: add number[]
  components/lib/accordion/accordion.d.ts
  package-lock.json
Labels: typescript

#3751 Fix #3750: FileUpload expose setFiles method
  components/doc/fileupload/apidoc.js
  components/lib/fileupload/FileUpload.js
  components/lib/fileupload/fileupload.d.ts
Labels: Core Team

#3759 Fix #3757: Splitbutton repsect menu API className
  components/lib/splitbutton/SplitButtonItem.js
Labels: Core Team

#3760 Fix #3755: Dialog maximized should have no margin
  components/lib/dialog/Dialog.css
Labels: Core Team

#3765 Fix #3361: Datatable frozenValue check for empty array
  components/lib/datatable/DataTable.js
Labels: Core Team

#3763 Fix #3428: p-input-filled/ripple-disabled added to overlays
  components/lib/autocomplete/AutoCompletePanel.js
  components/lib/calendar/Calendar.js
  components/lib/cascadeselect/CascadeSelectSub.js
  components/lib/colorpicker/ColorPickerPanel.js
  components/lib/confirmpopup/ConfirmPopup.js
  components/lib/contextmenu/ContextMenu.js
  components/lib/dialog/Dialog.js
  components/lib/dropdown/DropdownPanel.js
  components/lib/galleria/Galleria.js
  components/lib/menu/Menu.js
  components/lib/multiselect/MultiSelectPanel.js
  components/lib/overlaypanel/OverlayPanel.js
  components/lib/password/Password.js
  components/lib/sidebar/Sidebar.js
  components/lib/tieredmenu/TieredMenu.js
  components/lib/toast/Toast.js
  components/lib/treeselect/TreeSelectPanel.js
Labels: Core Team

#3769 Fix #3768: ToggleButton disabled tabIndex -1
  components/lib/togglebutton/ToggleButton.js
Labels: Core Team

#3771 Fix #3770: Calendar initial display minute respect stepMinute
  components/lib/calendar/Calendar.js
Labels: Core Team

#3773 Typescript doc updates
  components/doc/captcha/captchadoc.js
  components/doc/datatable/scroll/frozenrowsdoc.js
  components/doc/dialog/withoutmodaldoc.js
  components/doc/galleria/fullscreen/custom.js
  components/doc/galleria/galeriademo.js
  components/doc/image/thumbnaildoc.js
  components/doc/menu/basicdoc.js
  components/doc/menu/index.js
  components/doc/menu/inlinedoc.js
  components/doc/menu/overlaydoc.js
Labels: Component: Documentation, Core Team

#3774 Fix #3770: Calendar initial display minute respect stepMinute
  components/lib/calendar/Calendar.js
Labels: Core Team

#3778 Fix #3777: Calendar console warning about invalid props
  components/lib/calendar/Calendar.js
Labels: Core Team

#3780 Fix #3779: ConfirmPopup call onHide when clicking outside overlay
  components/lib/confirmpopup/ConfirmPopup.js
Labels: Core Team

#3782 Fix #3781: InputText typescript def value force string
  components/lib/inputtext/inputtext.d.ts
  components/lib/inputtextarea/inputtextarea.d.ts
Labels: Core Team

#3785 Fix #3783: Datatable error editing cells quickly
  components/lib/datatable/BodyCell.js
Labels: Core Team

#3793 Fix #3792: FileUpload index on itemTemplate
  components/lib/fileupload/FileUpload.js
Labels: Core Team

#3794 Fix #3789: Inline displaying wrong years
  components/lib/calendar/Calendar.js
Labels: Core Team

#3797 Fix #3796: TreeTable error in resize expand mode
  components/lib/treetable/TreeTable.js
Labels: Core Team

#3801 Fix #3800: BodyCell check elementRef exists
  components/lib/datatable/BodyCell.js
Labels: Core Team

#3805 Fix #3803: Datatable error with datakey and virtualscroller
  components/lib/datatable/BodyCell.js
Labels: Core Team

#3808 Fix #3804: Datatable error on selecting cell while fetching data
  components/lib/datatable/BodyCell.js
Labels: Core Team

#3791 Fix #3790: SelectButton focus method
  components/doc/selectbutton/validationdoc.js
  components/lib/selectbutton/SelectButton.js
  components/lib/selectbutton/selectbutton.d.ts
  pages/selectbutton/index.js
Labels: Core Team

#3813 Fix #3811: Sidebar toggle dissmissable state
  components/lib/sidebar/Sidebar.js
Labels: Core Team

#3814 Fix #3812: Reduce re-renders by not appending index to key
  components/lib/datatable/TableBody.js
Labels: Core Team

#3818 Fix #3817: Row reorder fixes from PrimeNG
  components/doc/datatable/reorderdoc.js
  components/lib/datatable/TableBody.js
  components/lib/utils/ObjectUtils.js
Labels: Core Team

#3820 Fix #3819: Global filter not clearing
  components/lib/datatable/DataTable.js
Labels: Core Team

#3822 Fix: #2523 DataTable/TreeTable: stricter generically typed API
  components/lib/datatable/datatable.d.ts
Labels: Typescript

#3825 Fix: #2523 DataTable/TreeTable: stricter generically typed API
  components/lib/datatable/datatable.d.ts
Labels: Core Team
