Repository primefaces/primereact, pull requests merged in 2022-05, with the labels that each got.

#2848 #2844 - bug fixed
  components/lib/calendar/Calendar.d.ts
Labels: typescript

#2832 Fix #2830: Splitter with multiple gutters
  components/lib/splitter/Splitter.js
Labels: pending-review

#2850 Fix #2849: InputNumber spinner touch events
  components/lib/inputnumber/InputNumber.js
Labels: pending-review

#2846 Fix #2843: InputNumber respect autoFocus on spin buttons
  components/lib/inputnumber/InputNumber.js
Labels: pending-review

#2823 Fix #2060: SlideMenu performance enhancement
  components/lib/slidemenu/SlideMenuSub.js
Labels: pending-review

#2816 Fix #1525: Fileupload disable buttons while uploading
  components/lib/fileupload/FileUpload.js
Labels: pending-review

#2807 Fix #2606: PickList allow source and target item templates
  api-generator/components/picklist.js
  components/doc/picklist/index.js
  components/lib/picklist/PickList.d.ts
  components/lib/picklist/PickList.js
Labels: pending-review

#2789 Fix #2690: FileUpload onBeforeDrop callback
  api-generator/components/fileupload.js
  components/doc/fileupload/index.js
  components/lib/fileupload/FileUpload.d.ts
  components/lib/fileupload/FileUpload.js
Labels: need revision

#2869 fix #2868 Ensure CSS is marked as a sideeffect to avoid being omission via tree-shaking
  package-build.json
Labels: pending-review

#2824 Fix #1367/#1862: Column resizeable attribute
  api-generator/components/column.js
  components/doc/datatable/index.js
  components/lib/column/Column.d.ts
  components/lib/column/Column.js
  components/lib/datatable/HeaderCell.js
  components/lib/treetable/TreeTableHeader.js
  pages/datatable/colresize.js
Labels: need revision

#2806 Fix #2226: Breadcrumb allow Home MenuItem template
  api-generator/components/breadcrumb.js
  components/doc/breadcrumb/index.js
  components/lib/breadcrumb/BreadCrumb.js
Labels: need revision

#2916 Attempt to improve DataTable.rowClassName and DataTable.cellClassName descriptions
  api-generator/components/datatable.js
Labels: documentation

#2917 Attempt to improve TreeTable.rowClassName description
  api-generator/components/treetable.js
Labels: documentation

#2944 Update SelectItem import statement
  components/lib/dropdown/Dropdown.d.ts
Labels: typescript

#2945 SelectItem case sensitive import
  components/lib/cascadeselect/CascadeSelect.d.ts
  components/lib/listbox/ListBox.d.ts
  components/lib/multiselect/MultiSelect.d.ts
  components/lib/selectbutton/SelectButton.d.ts
Labels: typescript
