Repository primefaces/primereact, pull requests merged in 2022-07, with the labels that each got.

#3005 Fix #3004: Tree arrow keys with dragdrop enabled
  components/lib/tree/UITreeNode.js
Labels: pending-review

#2994 Fix #2978/#2433: Datatable virtualscroller column resizing
  components/lib/datatable/DataTable.js
Labels: pending-review

#2972 Fix #2971: InputMask use ref not inputRef
  components/lib/inputmask/InputMask.d.ts
  components/lib/inputmask/InputMask.js
Labels: pending-review

#2962 Fix #2961: Calendar yearpicker incorrect
  components/lib/calendar/Calendar.js
Labels: pending-review

#2929 Fix #2926: Toast wrap long text
  components/lib/toast/Toast.css
Labels: pending-review

#2922 Fix #2921: FloatLabel with webkit autofill fix
  components/lib/inputtext/InputText.css
Labels: pending-review

#2920 Fix #2919: Avatar priority image, label, icon
  components/lib/avatar/Avatar.js
Labels: pending-review

#2911 Restrict Toast/Message SeverityType to the only four valid values
  components/lib/badge/Badge.d.ts
  components/lib/message/Message.d.ts
  components/lib/messages/Messages.d.ts
  components/lib/tag/Tag.d.ts
  components/lib/toast/Toast.d.ts
Labels: pending-review, typescript

#2810 Fix #2018: Calendar only fire onChange if dirty
  components/lib/calendar/Calendar.js
Labels: pending-review

#2798 Fix #2797: Chips add onKeyDown and KeyFilter
  api-generator/components/chips.js
  components/doc/chips/index.js
  components/lib/chips/Chips.d.ts
  components/lib/chips/Chips.js
Labels: pending-review, discussion

#2809 Fix #2808: MegaMenu start and end template attributes
  api-generator/components/megamenu.js
  components/doc/megamenu/index.js
  components/lib/megamenu/MegaMenu.css
  components/lib/megamenu/MegaMenu.d.ts
  components/lib/megamenu/MegaMenu.js
  components/lib/menubar/Menubar.js
  pages/megamenu/index.js
Labels: pending-review, need revision

#3026 Fix #3023: Sort nulls like Excel by default at bottom
  components/lib/datatable/DataTable.js
  components/lib/utils/ObjectUtils.js
Labels: pending-review

#3027 Fix #3019: Column sortFunction add rowData
  components/lib/column/Column.d.ts
  components/lib/datatable/DataTable.js
  components/lib/treetable/TreeTable.js
Labels: pending-review

#3032 Fix #3031: Image add onError callback
  components/lib/image/Image.d.ts
  components/lib/image/Image.js
Labels: pending-review

#2787 Fix #1879: Input focus() should not scroll unless autoFocus=true
  components/lib/autocomplete/AutoComplete.js
  components/lib/calendar/Calendar.js
  components/lib/cascadeselect/CascadeSelect.js
  components/lib/checkbox/Checkbox.js
  components/lib/chips/Chips.js
  components/lib/datatable/RowRadioButton.js
  components/lib/dropdown/Dropdown.js
  components/lib/dropdown/DropdownPanel.js
  components/lib/inputnumber/InputNumber.js
  components/lib/inputswitch/InputSwitch.js
  components/lib/mention/Mention.js
  components/lib/multiselect/MultiSelect.js
  components/lib/radiobutton/RadioButton.js
  components/lib/terminal/Terminal.js
  components/lib/treeselect/TreeSelect.js
  components/lib/utils/DomHandler.js
Labels: discussion

#2820 Next 12
  package-lock.json
  package.json
Labels: pending-review, dependencies

#3050 Fix #3046: DataTable row reorder not working
  api-generator/components/datatable.js
  components/doc/datatable/index.js
  components/lib/datatable/DataTable.d.ts
  components/lib/datatable/DataTable.js
  components/lib/datatable/TableBody.js
  pages/datatable/reorder.js
Labels: pending-review
