Repository primefaces/primereact, pull requests merged in 2022-09, with the labels that each got.

#3224 Fix #3196: Message(s) add icon attribute
  api-generator/components/message.js
  components/doc/messages/index.js
  components/lib/message/Message.js
  components/lib/message/message.d.ts
  components/lib/messages/UIMessage.js
  components/lib/messages/messages.d.ts
Labels: Core Team

#3222 Fixes #3221: Add support for keyboard users for Checkbox RadioButton
  components/lib/checkbox/Checkbox.js
  components/lib/radiobutton/RadioButton.js
Labels: Component: Accessibility

#3229 Fix #3228: Splitbutton fix visible property
  components/lib/splitbutton/SplitButtonItem.js
Labels: Core Team

#3234 Fix #3233: ConfirmPopup respect dismissable property
  components/lib/confirmpopup/ConfirmPopup.js
Labels: Core Team

#3243 Fix #3241: Tooltip allow event=both for handling hover and focus.
  api-generator/components/tooltip.js
  components/doc/tooltip/index.js
  components/lib/tooltip/Tooltip.js
  components/lib/tooltip/tooltipoptions.d.ts
  pages/tooltip/index.js
Labels: Core Team

#3248 Fixed #3219 - Rating Component with custom icons.
  api-generator/components/rating.js
  components/doc/rating/index.js
  components/lib/rating/Rating.css
  components/lib/rating/Rating.js
  components/lib/rating/rating.d.ts
  pages/rating/cancel.png
  pages/rating/custom-icon-active.png
  pages/rating/custom-icon.png
  pages/rating/index.js
Labels: Core Team

#3251 Fix #3250: Messages/Toast fix replace method
  components/lib/messages/Messages.js
  components/lib/toast/Toast.js
Labels: Core Team

#3253 Fix #3252: InputTextArea proper type def
  components/lib/inputtextarea/inputtextarea.d.ts
Labels: Core Team

#3255 Fix #3254: SpeedDial pass aria-label through to button
  components/lib/speeddial/SpeedDial.js
Labels: Core Team

#3257 Fix #3256: Dialog focus trap issue with multiple dialogs
  components/lib/dialog/Dialog.js
Labels: Core Team

#3261 Fix #3258: Calendar setValue should update view date
  components/lib/calendar/Calendar.js
Labels: Core Team

#3262 Fix #3259: TabView add aria-labels to previous and next button
  components/lib/tabview/TabView.js
Labels: Core Team

#3265 Fix #3263: Datatable aria label fixes
  api-generator/components/datatable.js
  components/doc/datatable/index.js
  components/lib/api/Locale.js
  components/lib/datatable/BodyCell.js
  components/lib/datatable/BodyRow.js
  components/lib/datatable/ColumnFilter.js
  components/lib/datatable/DataTable.js
  components/lib/datatable/RowCheckbox.js
  components/lib/datatable/RowRadioButton.js
  components/lib/datatable/datatable.d.ts
  components/lib/dropdown/Dropdown.js
  components/lib/paginator/RowsPerPageDropdown.js
  pages/datatable/selection.js
Labels: Core Team

#3276 Fix #3275: AutoComplete add dropdownAriaLabel with defaults
  api-generator/components/autocomplete.js
  components/doc/autocomplete/index.js
  components/lib/autocomplete/AutoComplete.js
  components/lib/autocomplete/autocomplete.d.ts
  pages/autocomplete/index.js
Labels: Core Team

#3279 Update dependencies including Next.js
  package-lock.json
  package.json
Labels: Core Team

#3281 Fix #3280: ARIA add close/clear labels
  components/lib/dialog/Dialog.js
  components/lib/dropdown/DropdownPanel.js
  components/lib/galleria/Galleria.js
  components/lib/image/Image.js
  components/lib/inplace/Inplace.js
  components/lib/messages/UIMessage.js
  components/lib/multiselect/MultiSelectHeader.js
  components/lib/overlaypanel/OverlayPanel.js
  components/lib/sidebar/Sidebar.js
  components/lib/treeselect/TreeSelect.js
Labels: Core Team

#3286 Fix #3284: Multiple sorting with dates was not correct
  components/lib/datatable/DataTable.js
  components/lib/treetable/TreeTable.js
  components/lib/utils/ObjectUtils.js
Labels: Core Team

#3282 Fix #3171: ScrollPanel Cannot scroll inside dialog
  components/lib/scrollpanel/ScrollPanel.js
Labels: Core Team

#3130 Fix #2913: Password label is same as meter color
  components/lib/password/Password.js
  public/themes/arya-blue/theme.css
  public/themes/arya-green/theme.css
  public/themes/arya-orange/theme.css
  public/themes/arya-purple/theme.css
  public/themes/bootstrap4-dark-blue/theme.css
  public/themes/bootstrap4-dark-purple/theme.css
  public/themes/bootstrap4-light-blue/theme.css
  public/themes/bootstrap4-light-purple/theme.css
  public/themes/fluent-light/theme.css
  public/themes/lara-dark-blue/theme.css
  public/themes/lara-dark-indigo/theme.css
  public/themes/lara-dark-purple/theme.css
  public/themes/lara-dark-teal/theme.css
  public/themes/lara-light-blue/theme.css
  public/themes/lara-light-indigo/theme.css
  public/themes/lara-light-purple/theme.css
  public/themes/lara-light-teal/theme.css
  public/themes/luna-amber/theme.css
  public/themes/luna-blue/theme.css
  public/themes/luna-green/theme.css
  public/themes/luna-pink/theme.css
  public/themes/md-dark-deeppurple/theme.css
  public/themes/md-dark-indigo/theme.css
  public/themes/md-light-deeppurple/theme.css
  public/themes/md-light-indigo/theme.css
  public/themes/mdc-dark-deeppurple/theme.css
  public/themes/mdc-dark-indigo/theme.css
  public/themes/mdc-light-deeppurple/theme.css
  public/themes/mdc-light-indigo/theme.css
  public/themes/nova-accent/theme.css
  public/themes/nova-alt/theme.css
  public/themes/nova/theme.css
  public/themes/rhea/theme.css
  public/themes/saga-blue/theme.css
  public/themes/saga-green/theme.css
  public/themes/saga-orange/theme.css
  public/themes/saga-purple/theme.css
  public/themes/tailwind-light/theme.css
  public/themes/vela-blue/theme.css
  public/themes/vela-green/theme.css
  public/themes/vela-orange/theme.css
  public/themes/vela-purple/theme.css
Labels: Core Team

#3291 Fix #3290: Password add keyfilter support
  api-generator/components/password.js
  components/doc/password/index.js
  components/lib/password/password.d.ts
Labels: Core Team

#3293 Fix #3292: ARIA expand and collapse labels
  components/lib/accordion/Accordion.js
  components/lib/api/Locale.js
  components/lib/datatable/BodyCell.js
  components/lib/datatable/RowTogglerButton.js
  components/lib/tree/UITreeNode.js
  components/lib/treetable/TreeTableRow.js
  pages/locale/index.js
Labels: Core Team

#3287 Fix #3244 Autocomplete: add emptyMessage property.
  components/doc/autocomplete/index.js
  components/lib/autocomplete/AutoComplete.js
  components/lib/autocomplete/AutoCompletePanel.js
  components/lib/autocomplete/autocomplete.d.ts
Labels: Type: New Feature, Core Team

#3313 Fix #3312: Tabview add onBeforeTabClose/Change events
  api-generator/components/tabview.js
  components/doc/tabview/index.js
  components/lib/tabview/TabView.js
  components/lib/tabview/tabview.d.ts
Labels: Core Team

#3316 Fix #3315: Calendar viewstatechange
  components/lib/calendar/Calendar.js
  components/lib/calendar/calendar.d.ts
Labels: Core Team

#3317 Fix #3310: RowExpansionTemplate allow for custom rendering
  components/doc/datatable/index.js
  components/lib/datatable/TableBody.js
  components/lib/datatable/datatable.d.ts
Labels: Core Team

#3322 Fix #3321: Pass "data" properties to input components
  components/lib/autocomplete/AutoComplete.js
  components/lib/checkbox/Checkbox.js
  components/lib/dropdown/Dropdown.js
  components/lib/inputnumber/InputNumber.js
  components/lib/inputswitch/InputSwitch.js
  components/lib/multiselect/MultiSelect.js
  components/lib/radiobutton/RadioButton.js
  components/lib/utils/ObjectUtils.js
Labels: Core Team

#3323 Fix #839/#1852/#3319: ARIA support to input elements
  components/lib/autocomplete/AutoComplete.js
  components/lib/cascadeselect/CascadeSelect.js
  components/lib/checkbox/Checkbox.js
  components/lib/chips/Chips.js
  components/lib/dropdown/Dropdown.js
  components/lib/inputnumber/InputNumber.js
  components/lib/inputswitch/InputSwitch.js
  components/lib/listbox/ListBox.js
  components/lib/mention/Mention.js
  components/lib/multiselect/MultiSelect.js
  components/lib/multistatecheckbox/MultiStateCheckbox.js
  components/lib/radiobutton/RadioButton.js
  components/lib/slider/Slider.js
  components/lib/tree/Tree.js
  components/lib/treeselect/TreeSelect.js
  components/lib/tristatecheckbox/TriStateCheckbox.js
  components/lib/utils/DomHandler.js
  components/lib/utils/ObjectUtils.js
Labels: Core Team

#3212 fixes #3200 Add Generics to Dropdown, Listbox, Multiselect and Selectbutton
  components/lib/cascadeselect/cascadeselect.d.ts
  components/lib/dropdown/dropdown.d.ts
  components/lib/listbox/listbox.d.ts
  components/lib/multiselect/multiselect.d.ts
  components/lib/selectbutton/selectbutton.d.ts
  components/lib/selectitem/selectitem.d.ts
Labels: TypeScript

#3328 Fix #3327: SortOrder typescript constants
  components/lib/api/Api.js
  components/lib/api/SortOrder.js
  components/lib/api/api.d.ts
Labels: Core Team

#3338 Fix #3288: Add global index.d.ts
  components/lib/index.d.ts
  package-build.json
Labels: Core Team

#3340 Fix #3250: Message use let instead of const
  components/lib/messages/Messages.js
  package-build.json
Labels: Core Team

#3346 Primeicons version update --v6
  components/layout/menu.json
  package-lock.json
  package.json
  public/data/icons.json
Labels: Core Team

#3349 Fix #839: ARIA fixes
  components/lib/button/Button.js
  components/lib/datatable/BodyCell.js
  components/lib/datatable/RowTogglerButton.js
  components/lib/inplace/Inplace.js
  components/lib/tree/UITreeNode.js
  components/lib/treetable/TreeTableRow.js
Labels: Core Team

#3345 Fix #3344: FullCalendar remove all traces
  api-generator/components/fullcalendar.js
  components/lib/fullcalendar/FullCalendar.js
  components/lib/fullcalendar/fullcalendar.d.ts
  components/lib/fullcalendar/package.json
  components/lib/index.d.ts
  components/lib/primereact.all.js
  pages/setup/index.js
Labels: Core Team

#3356 fix: typo on the sidebar menu and the UI Kit page.
  components/layout/menu.json
  pages/uikit/index.js
Labels: Core Team

#3366 Fix #3365: RowsPerPageDropdown proper aria-label
  components/lib/paginator/RowsPerPageDropdown.js
Labels: Core Team

#3372 Fix #3370: Galleria localeOption was missing
  components/lib/galleria/Galleria.js
Labels: Core Team

#3374 Fix #3373: Datatable show filter active
  components/lib/datatable/ColumnFilter.js
Labels: Core Team

#3371 Toast: close icon fixed
  components/lib/toast/ToastMessage.js
Labels: Core Team

#3379 Fix #3378: Data attributes not on hidden inputs
  components/lib/autocomplete/AutoComplete.js
  components/lib/checkbox/Checkbox.js
  components/lib/dropdown/Dropdown.js
  components/lib/inputswitch/InputSwitch.js
  components/lib/multiselect/MultiSelect.js
  components/lib/radiobutton/RadioButton.js
Labels: Core Team

#3380 Fix #3375: Dropdown allow filtering of primitive strings
  components/lib/api/FilterService.js
Labels: Core Team

#3386 Fix #3381: Calendar allow override of parse/format time
  api-generator/components/calendar.js
  components/doc/calendar/index.js
  components/lib/calendar/Calendar.js
  components/lib/calendar/calendar.d.ts
Labels: Core Team

#3391 Fix #3390: Image add previewSrc property
  api-generator/components/image.js
  components/doc/image/index.js
  components/lib/image/Image.js
  components/lib/image/image.d.ts
  pages/image/index.js
Labels: Core Team

#3394 Fix #3390: Rename previewSrc as zoomSrc
  api-generator/components/image.js
  components/doc/image/index.js
  components/lib/image/Image.js
  components/lib/image/image.d.ts
  pages/image/index.js
Labels: Core Team

#3395 Fix #2864: AccordionTab tabIndex
  components/doc/accordion/index.js
  components/lib/accordion/Accordion.js
  components/lib/accordion/accordion.d.ts
Labels: Core Team
