Repository primefaces/primereact, pull requests merged in 2023-08, with the labels that each got.

#4713 fix: datatable: contextmenu for multiple rows #4342
  components/lib/datatable/TableBody.js
Labels: Type: Enhancement

#4717 fix: #4714 Datatable: Multiselection checkbox with context menu broke UI
  components/lib/datatable/DataTable.js
  components/lib/datatable/TableBody.js
Labels: Type: Bug

#4732 Fix primfaces #4730: Calendar: input field cannot parse year-only format
  components/lib/calendar/Calendar.js
Labels: Type: Bug

#4741 Fix #4724: Autocomplete prevent error on trim()
  components/lib/autocomplete/AutoComplete.js
  components/lib/utils/ObjectUtils.js
  components/lib/utils/utils.d.ts
Labels: Core Team

#4742 Autocomplete fix incorrect prop
  components/lib/autocomplete/AutoCompleteBase.js
  components/lib/autocomplete/AutoCompletePanel.js
Labels: Core Team

#4743 Fix scrollpanel scrollbar on zoom out
  components/lib/scrollpanel/ScrollPanelBase.js
Labels: Type: Enhancement

#4746 Fixed Button p-badge rendered twice
  components/lib/button/Button.js
  components/lib/button/__snapshots__/Button.spec.js.snap
Labels: Core Team

#4749 Fix #4748: Image proper handling of zoom in and zoom out
  components/lib/image/Image.js
Labels: Core Team

#4754 Fix tooltip
  components/lib/tooltip/Tooltip.js
  components/lib/tooltip/TooltipBase.js
Labels: Core Team

#4755 Fix #4704: typescript order for closeOnEscape
  components/lib/image/image.d.ts
  components/lib/overlaypanel/overlaypanel.d.ts
Labels: Core Team

#4756 Fix #4753: ConfirmDialog appendTo
  components/lib/confirmdialog/ConfirmDialog.js
Labels: Core Team

#4410 Fix #3139 : After resizing and reordering column takes the size of the column it is displacing
  components/lib/datatable/DataTable.js
Labels: Type: Enhancement

#4673 Fix #4649: Datatable add closeEditingRows()
  components/lib/datatable/DataTable.js
  components/lib/datatable/datatable.d.ts
Labels: Core Team

#4633 Fix #4531: InputNumber keydown/keyup
  components/lib/inputnumber/InputNumber.js
  components/lib/inputnumber/InputNumberBase.js
  components/lib/inputnumber/inputnumber.d.ts
Labels: Type: Enhancement, Core Team

#4385 Fix #4007: ProgressBar display small value percentages.
  components/lib/progressbar/ProgressBar.js
  components/lib/progressbar/ProgressBarBase.js
  components/lib/progressbar/__snapshots__/ProgressBar.spec.js.snap
Labels: Status: Pending Review, Core Team

#4760 fix: #4759 bad behaviour of Dialog component
  components/lib/dialog/Dialog.js
Labels: Type: Bug

#4767 Fix #4766: Dropdown respect menu item style
  components/lib/dropdown/DropdownPanel.js
Labels: Core Team

#4769 Fix #4768: Sort and Filter performance gains
  components/lib/carousel/Carousel.js
  components/lib/datatable/DataTable.js
  components/lib/dataview/DataView.js
  components/lib/galleria/GalleriaThumbnails.js
  components/lib/treetable/TreeTable.js
  components/lib/utils/ObjectUtils.js
Labels: Core Team

#4771 Fix primefaces primefaces #4770 Overlay Panel: Second overlay panel on the page you select doesnot listen to the escape key
  components/lib/overlaypanel/OverlayPanel.js
Labels: Type: Bug

#4590 #4589: Fix adding icon to chips
  components/doc/chips/icondoc.js
  components/lib/chips/ChipsBase.js
  pages/chips/index.js
Labels: Type: Enhancement

#4773 Fix #4716: TreeSelect showClear and clearIcon
  components/doc/treeselect/clearicondoc.js
  components/lib/dropdown/Dropdown.js
  components/lib/dropdown/DropdownBase.js
  components/lib/dropdown/dropdown.d.ts
  components/lib/treeselect/TreeSelect.js
  components/lib/treeselect/TreeSelectBase.js
  components/lib/treeselect/treeselect.d.ts
  pages/treeselect/index.js
Labels: Core Team

#4794 Fix #4471: 9.6.2 Column Resize fix for strict and non-strict mode
  components/lib/datatable/DataTable.js
Labels: Type: Bug

#4791 Fix #4766: 9.6.2 Dropdown respect menu item style
  components/lib/dropdown/DropdownPanel.js
Labels: Type: Bug

#4785 Fix #4579: 9.6.2 Calendar mask correct hook
  components/lib/calendar/Calendar.js
Labels: Type: Bug

#4783 Fix #4604: 9.6.2 Tooltip autohide fix
  components/doc/tooltip/autohidedoc.js
  components/lib/tooltip/Tooltip.js
Labels: Type: Bug

#4782 Fix #4680: 9.6.2 Slider onSlideEnd have correct new value
  components/lib/slider/Slider.js
Labels: Type: Bug

#4781 Fix #4568: 9.6.2 Calendar focus state should change when displaying p…
  components/lib/calendar/Calendar.js
Labels: Type: Bug

#4792 Fix #4777: Datatable typescript improvements
  components/doc/datatable/cellselection/multipledoc.js
  components/doc/datatable/cellselection/singledoc.js
  components/doc/datatable/pt/ptdoc.js
  components/doc/datatable/rowselection/checkboxdoc.js
  components/doc/datatable/rowselection/disableddoc.js
  components/doc/datatable/rowselection/eventsdoc.js
  components/doc/datatable/rowselection/multipledoc.js
  components/doc/datatable/rowselection/radiobuttondoc.js
  components/doc/datatable/rowselection/singledoc.js
  components/lib/datatable/datatable.d.ts
Labels: Typescript

#4790 Fix #4788: Calendar typescript improvements
  components/doc/calendar/basicdoc.js
  components/doc/calendar/buttonbardoc.js
  components/doc/calendar/datetemplatedoc.js
  components/doc/calendar/floatlabeldoc.js
  components/doc/calendar/formatdoc.js
  components/doc/calendar/icondoc.js
  components/doc/calendar/inlinedoc.js
  components/doc/calendar/localedoc.js
  components/doc/calendar/minmaxdoc.js
  components/doc/calendar/monthpickerdoc.js
  components/doc/calendar/multipledoc.js
  components/doc/calendar/multiplemonthsdoc.js
  components/doc/calendar/rangedoc.js
  components/doc/calendar/timedoc.js
  components/doc/calendar/touchuidoc.js
  components/doc/calendar/yearpickerdoc.js
  components/lib/calendar/Calendar.js
  components/lib/calendar/calendar.d.ts
Labels: Typescript

#4795 Fix #4784: AutoComplete improve UX with selectionLimit
  components/lib/autocomplete/AutoComplete.js
Labels: Core Team

#4796 Fix #4030: Changing Calendar input (with mask) clears the rest of the form's state
  components/lib/calendar/Calendar.js
Labels: Type: Bug

#4798 Fix #4797: ObjectUtils.resolveFieldData perf improvement
  components/lib/utils/ObjectUtils.js
Labels: Core Team

#4801 #Fix #4531: InputNumber missing charCode
  components/lib/inputnumber/InputNumber.js
Labels: Core Team

#4800 Fix #4797: ObjectUtils.resolveFieldData perf improvement
  components/lib/utils/ObjectUtils.js
Labels: Core Team

#4804 Fix #4803: Calendar disabledDays only in date display
  components/lib/calendar/Calendar.js
Labels: Core Team

#4815 Fix #4811: Doc PrimeReactContext in hook
  components/doc/configuration/appendtodoc.js
  components/doc/configuration/csstransitiondoc.js
  components/doc/configuration/filtermatchmodedoc.js
  components/doc/configuration/hideoverlaysdoc.js
  components/doc/configuration/inputstyledoc.js
  components/doc/configuration/noncedoc.js
  components/doc/configuration/nullsortorderdoc.js
  components/doc/configuration/rippledoc.js
  components/doc/configuration/zindexdoc.js
  components/lib/blockui/__snapshots__/BlockUI.spec.js.snap
Labels: Core Team

#4821 Fix #4819: Overlay handling better handling of alignment with browser…
  components/lib/hooks/useOverlayListener.js
  components/lib/overlaypanel/OverlayPanel.js
  components/lib/overlaypanel/overlaypanel.d.ts
Labels: Core Team

#4824 Fix #4823 9.7.0: Backport PrimeReactProvider global settings
  components/lib/api/PrimeReactContext.js
  components/lib/api/api.d.ts
Labels: Core Team

#4827 Fix #4819: Overlay better handling of dissmissible
  components/doc/overlaypanel/datatabledoc.js
  components/lib/overlaypanel/OverlayPanel.js
Labels: Core Team

#4830 Fix #4431: HeaderCell fixes based on previous refactor
  components/lib/datatable/HeaderCell.js
Labels: Core Team

#4817 Fix #4816: TreeTable onValueChange
  components/lib/treetable/TreeTable.js
  components/lib/treetable/TreeTableBase.js
  components/lib/treetable/treetable.d.ts
Labels: Core Team

#4833 Fix #4832: Datatable TS onContextMenuSelectionChange
  components/lib/datatable/datatable.d.ts
Labels: Core Team

#4842 Fix #4839: Avatar Circle CSS needs more specific selector
  components/lib/avatar/AvatarBase.js
Labels: Core Team

#4841 Fix #4836: Password do not put input props on container DIV
  components/doc/password/basicdoc.js
  components/lib/password/Password.js
  components/lib/password/PasswordBase.js
Labels: Core Team

#4843 Fix #4834: Calendar p-inputwrapper-focus
  components/lib/calendar/Calendar.js
Labels: Core Team

#4851 Union type to allow SVGElement for icon props
  components/lib/utils/utils.d.ts
Labels: Typescript
