Repository primefaces/primereact, pull requests merged in 2023-10, with the labels that each got.

#4995 Fix #4993: Column missing headerClassName
  components/lib/datatable/HeaderCell.js
Labels: Core Team

#4996 Fix #4994: Filter button still rendered even if show=false
  components/lib/datatable/ColumnFilter.js
Labels: Core Team

#5010 Multiselect clearIcon missing in TypeScript
  components/lib/multiselect/MultiSelectBase.js
  components/lib/multiselect/multiselect.d.ts
Labels: Typescript, Core Team

#5029 Fix #5018: Checkbox typescript FormEvent
  components/lib/checkbox/checkbox.d.ts
Labels: Core Team

#5025 Feature: add typing for useHandleStyle
  components/lib/componentbase/componentbase.d.ts
Labels: Typescript

#5030 Fix #5026: useStorage must JSON.stringify
  components/lib/hooks/useStorage.js
Labels: Core Team

#5032 Fix #5027: Calendar set initial stepMinute
  components/lib/calendar/Calendar.js
Labels: Core Team

#5033 Fix #5028: Multiselect filterTemplate
  components/lib/multiselect/MultiSelect.js
  components/lib/multiselect/MultiSelectHeader.js
Labels: Core Team

#5037 Fix #5035: ContextMenu not passing data
  components/lib/datatable/TableBody.js
Labels: Core Team

#5043 Fix #5039: DT contextmenu + row checkbox event handling
  components/lib/datatable/RowCheckbox.js
  components/lib/datatable/TableBody.js
Labels: Core Team

#5045 fix Primefaces primefaces#5044 Menu with popup prop passed doesnot close on Escape keypress
  components/doc/common/apidoc/index.json
  components/lib/menu/Menu.js
  components/lib/menu/MenuBase.js
  components/lib/menu/menu.d.ts
Labels: Type: Bug

#5050 Fix #4219: Prevent NPE on current when autoHighlight
  components/lib/autocomplete/AutoComplete.js
Labels: Core Team

#5052 Fix #5047: Dropdown add label to itemGroup passthrough
  components/lib/dropdown/DropdownBase.js
  components/lib/dropdown/DropdownPanel.js
Labels: Core Team

#5056 Fix #5054: ContextMenu typescript examples fixed
  components/doc/contextmenu/basicdoc.js
  components/doc/contextmenu/pt/ptdoc.js
Labels: Core Team

#5057 Added custom event for data table row pointer events #5051
  components/doc/common/apidoc/index.json
  components/lib/datatable/BodyRow.js
  components/lib/datatable/DataTable.js
  components/lib/datatable/DataTableBase.js
  components/lib/datatable/TableBody.js
  components/lib/datatable/datatable.d.ts
Labels: Type: Enhancement

#5066 Fix #5060: --text-color-secondary
  components/doc/colors/overviewdoc.js
  components/doc/mention/autoresizedoc.js
  components/doc/mention/basicdoc.js
  components/doc/mention/floatlabeldoc.js
  components/doc/mention/form/formikdoc.js
  components/doc/mention/form/hookformdoc.js
  components/doc/mention/invaliddoc.js
  components/doc/mention/pt/ptdoc.js
  components/doc/mention/triggersdoc.js
Labels: Core Team

#5067 Fix: ContextMenu: Broken with nested items (10.0) #5064
  components/lib/contextmenu/ContextMenuSub.js
Labels: Type: Bug

#5069 Fix typo in bulma demo
  pages/bulma/index.js
Labels: Component: Documentation

#5072 Fix #5071: useDebounce Typescript
  components/lib/hooks/hooks.d.ts
Labels: Core Team

#5075 Fix #5074: Prevent rowExpander from clicking row
  components/layout/topbar.js
  components/lib/datatable/BodyCell.js
Labels: Core Team

#5089 Fix #5088: Fieldset missing props.className
  components/lib/fieldset/Fieldset.js
Labels: Core Team

#5090 Fix #5083: Toast/Messages remove by message
  components/lib/messages/Messages.js
  components/lib/toast/Toast.js
  components/lib/utils/ObjectUtils.js
Labels: Core Team

#5081 Fix Tree copy by doing a shallow copy of the value
  components/lib/tree/Tree.js
Labels: Type: Enhancement

#5101 Fix #5100: MultiSelect add space after comma
  components/lib/multiselect/MultiSelect.js
Labels: Core Team

#5105 Fix #5102: TreeSelect filterTemplate typescript
  components/lib/treeselect/treeselect.d.ts
Labels: Core Team

#5104 Fix Inplace Component Doc Image Responsive Issue
  components/doc/inplace/imagedoc.js
Labels: Component: Documentation

#5112 Fix #5111: Slider fix NaN on bottom CSS
  components/lib/slider/Slider.js
Labels: Core Team

#5128 Fix #5114: Mentioning deletes the first word of the comment
  components/lib/mention/Mention.js
Labels: Type: Bug

#5134 Fix #5132: InputNumber icon TS def
  components/lib/inputnumber/inputnumber.d.ts
Labels: Core Team

#5133 Fix #5125: Defensive handling of finding passthrough prop
  components/lib/componentbase/ComponentBase.js
Labels: Core Team

#5136 Fix #5135: Password expose toggleMask() method
  components/lib/password/Password.js
  components/lib/password/password.d.ts
Labels: Core Team

#5139 Fix typos: inteface-> interface
  components/doc/timeline/alignmentdoc.js
  components/doc/timeline/basicdoc.js
  components/doc/timeline/oppositedoc.js
  components/doc/timeline/pt/ptdoc.js
  components/doc/timeline/templatedoc.js
  components/doc/treetable/filterdoc.js
Labels: Component: Documentation

#5149 Fix #5148: SpeedDial menu className and style
  components/lib/speeddial/SpeedDial.js
Labels: Type: Bug, Core Team

#5150 Fix #2052: Accordion dynamic showcase example
  components/doc/accordion/dynamicdoc.js
  pages/accordion/index.js
Labels: Core Team

#5152 Fix #5151: MultiSelect prevent SelectAll click propagation
  components/lib/multiselect/MultiSelectHeader.js
Labels: Core Team

#5155 Fix Divider Tests
  components/lib/divider/__snapshots__/Divider.spec.js.snap
Labels: Core Team

#5162 Fix #5161: FileUpload localize pending/completed
  components/lib/api/Locale.js
  components/lib/fileupload/FileUpload.js
  components/lib/tooltip/Tooltip.js
Labels: Core Team

#5174 Fix #5169: SplitterPanel allow id
  components/lib/splitter/Splitter.js
Labels: Core Team

#5175 Fix #5172: Ripple forwardRef issue
  components/lib/ripple/Ripple.js
Labels: Core Team

#5178 Fix #5177: Orderlist move top and bottom keep order
  components/lib/orderlist/OrderListControls.js
Labels: Core Team

#5179 Add missing pi-file-edit icon
  components/lib/api/PrimeIcons.js
Labels: Type: Bug

#5182 Fix #5164: Datatable frozen column and filter row
  components/lib/datatable/DataTableBase.js
  components/lib/datatable/TableHeader.js
Labels: Core Team

#5183 Fix #5181: Tailwind MenuBar end class
  components/lib/passthrough/tailwind/index.js
Labels: Core Team

#5194 Fix #5186: InputNumber for multi-char currency
  components/lib/inputnumber/InputNumber.js
Labels: Core Team

#5195 Fix #5192: Allow CTRL/SHIFT + ENTER for TextArea
  components/lib/datatable/BodyCell.js
Labels: Core Team

#5197 fix(Datatable): Missing rowEditorSaveButton and rowEditorSaveIcon on …
  components/lib/column/column.d.ts
  package-lock.json
Labels: Typescript

#5199 Update tailwinddoc.js for PanelMenu
  components/doc/panelmenu/theming/tailwinddoc.js
Labels: Component: Documentation

#5201 feat: Remove duplicate styling
  components/lib/passthrough/tailwind/index.js
Labels: Component: Tailwind

#5204 Fix #5203: ComponentBase context could be undefined
  components/lib/componentbase/ComponentBase.js
Labels: Core Team
