Repository primefaces/primereact, pull requests merged in 2023-06, with the labels that each got.

#4480 Update typescript libs
  package-lock.json
  package.json
Labels: Typescript, Core Team

#4490 Fix #4489: Dropdown add getVirtualScroller
  components/lib/dropdown/dropdown.d.ts
Labels: Core Team

#4493 Fix #4492: Datatable check/radio respect isDataSelectable
  components/lib/datatable/BodyCell.js
  components/lib/datatable/RowCheckbox.js
  components/lib/datatable/RowRadioButton.js
Labels: Core Team

#4494 Fix #4486: PassThrough Image does not support referrerpolicy
  components/lib/avatar/avatar.d.ts
  components/lib/chip/chip.d.ts
  components/lib/fileupload/fileupload.d.ts
  components/lib/image/image.d.ts
Labels: Core Team

#4496 Lint and Format and Test Fixes
  components/doc/dock/advanceddoc.js
  components/doc/slidemenu/pt/wireframe.js
  components/layout/layout.js
  components/lib/accordion/Accordion.js
  components/lib/api/context.js
  components/lib/avatar/__snapshots__/Avatar.spec.js.snap
  components/lib/avatargroup/__snapshots__/AvatarGroup.spec.js.snap
  components/lib/badge/__snapshots__/Badge.spec.js.snap
  components/lib/blockui/BlockUI.spec.js
  components/lib/blockui/__snapshots__/BlockUI.spec.js.snap
  components/lib/button/Button.spec.js
  components/lib/button/__snapshots__/Button.spec.js.snap
  components/lib/calendar/Calendar.js
  components/lib/card/Card.spec.js
  components/lib/card/__snapshots__/Card.spec.js.snap
  components/lib/chip/__snapshots__/Chip.spec.js.snap
  components/lib/colorpicker/ColorPicker.js
  components/lib/componentbase/ComponentBase.js
  components/lib/datatable/DataTable.js
  components/lib/divider/__snapshots__/Divider.spec.js.snap
  components/lib/fieldset/Fieldset.spec.js
  components/lib/fieldset/__snapshots__/Fieldset.spec.js.snap
  components/lib/hooks/useLocale.js
  components/lib/inputtext/__snapshots__/InputText.spec.js.snap
  components/lib/inputtextarea/__snapshots__/InputTextarea.spec.js.snap
  components/lib/megamenu/MegaMenu.js
  components/lib/message/__snapshots__/Message.spec.js.snap
  components/lib/multiselect/MultiSelect.js
  components/lib/paginator/Paginator.js
  components/lib/panel/Panel.spec.js
  components/lib/panel/__snapshots__/Panel.spec.js.snap
  components/lib/progressbar/__snapshots__/ProgressBar.spec.js.snap
  components/lib/progressspinner/__snapshots__/ProgressSpinner.spec.js.snap
  components/lib/ripple/Ripple.spec.js
  components/lib/ripple/__snapshots__/Ripple.spec.js.snap
  components/lib/scrollpanel/__snapshots__/ScrollPanel.spec.js.snap
  components/lib/skeleton/__snapshots__/Skeleton.spec.js.snap
  components/lib/splitter/Splitter.js
  components/lib/splitter/__snapshots__/Splitter.spec.js.snap
  components/lib/tabview/TabView.js
  components/lib/tag/__snapshots__/Tag.spec.js.snap
  components/lib/tooltip/Tooltip.spec.js
  components/lib/utils/ObjectUtils.js
  pages/_app.js
Labels: Core Team

#4500 Enhancement #4499: Add toggler template to TreeTable
  components/doc/treetable/templatedoc.js
  components/lib/treetable/TreeTable.js
  components/lib/treetable/TreeTableBody.js
  components/lib/treetable/TreeTableRow.js
  components/lib/treetable/treetable.d.ts
Labels: Type: Enhancement

#4501 Fix #4498: Update Icons docs
  components/doc/common/doccomponent.js
  components/doc/customicons/fontawesomedoc.js
  components/doc/customicons/imagedoc.js
  components/doc/customicons/materialdoc.js
  components/doc/customicons/svgdoc.js
  pages/customicons/index.js
Labels: Core Team

#4507 Fix #4505: ScrollTop not mounting
  components/lib/hooks/useEventListener.js
  components/lib/scrolltop/ScrollTop.js
Labels: Core Team

#4297 Fix #4291: InputNumber respect PrimeReact.locale
  components/lib/inputnumber/InputNumber.js
Labels: Status: Pending Review, Core Team

#4508 Fix #4502: added TreeTable row hover events (OnRowMouseEnter and OnRowMouseLeave)
  components/lib/treetable/TreeTable.js
  components/lib/treetable/TreeTableBase.js
  components/lib/treetable/TreeTableBody.js
  components/lib/treetable/TreeTableRow.js
  components/lib/treetable/treetable.d.ts
Labels: Type: Enhancement

#4510 Fix #4509: Orderlist aria labels on buttons
  components/lib/api/Locale.js
  components/lib/orderlist/OrderListControls.js
Labels: Core Team

#4514 Fix #4513: Carousel expose start/stop autoplay methods
  components/lib/carousel/Carousel.js
  components/lib/carousel/carousel.d.ts
Labels: Core Team

#4517 Fix #4516: FileUpload uploaded files updates
  components/lib/fileupload/FileUpload.js
  components/lib/fileupload/fileupload.d.ts
Labels: Core Team

#4526 Fix #4525: TreeSelect add togglerTemplate
  components/lib/treeselect/TreeSelect.js
  components/lib/treeselect/TreeSelectBase.js
  components/lib/treeselect/treeselect.d.ts
Labels: Core Team

#4529 Fix #4528: SlideMenu separator missing
  components/lib/slidemenu/SlideMenuSub.js
Labels: Core Team

#4532 Fix #4527: Toast update position demo and docs
  components/doc/toast/positiondoc.js
  components/lib/toast/toast.d.ts
Labels: Core Team

#4534 Fix #4533: FileUpload input passthrough in basic mode
  components/lib/fileupload/FileUpload.js
Labels: Core Team

#4539 Fix #4523: Multiselect remove onClick on checkbox SVG
  components/lib/multiselect/MultiSelectBase.js
Labels: Core Team

#4541 Fix #4518: svg images with no base size do not show up in preview
  components/lib/image/Image.css
Labels: Type: Bug

#4544 Fix #4543: ContextMenu global in strict mode
  components/lib/contextmenu/ContextMenu.js
Labels: Core Team

#4550 fix: chips to have type string instead of any for the value since HTM…
  components/lib/chips/chips.d.ts
Labels: Typescript

#4554 Fix #4553: Tooltip fix typescript for methods
  components/lib/tooltip/tooltip.d.ts
Labels: Core Team

#4488 Fixed #4483 - SplitButton: menu icon not visible in large size
  public/themes/arya-blue/theme.css
  public/themes/arya-green/theme.css
  public/themes/arya-orange/theme.css
  public/themes/arya-purple/theme.css
  public/themes/bootstrap4-dark-blue/theme.css
  public/themes/bootstrap4-dark-purple/theme.css
  public/themes/bootstrap4-light-blue/theme.css
  public/themes/bootstrap4-light-purple/theme.css
  public/themes/fluent-light/theme.css
  public/themes/lara-dark-blue/theme.css
  public/themes/lara-dark-indigo/theme.css
  public/themes/lara-dark-purple/theme.css
  public/themes/lara-dark-teal/theme.css
  public/themes/lara-light-blue/theme.css
  public/themes/lara-light-indigo/theme.css
  public/themes/lara-light-purple/theme.css
  public/themes/lara-light-teal/theme.css
  public/themes/luna-amber/theme.css
  public/themes/luna-blue/theme.css
  public/themes/luna-green/theme.css
  public/themes/luna-pink/theme.css
  public/themes/md-dark-deeppurple/theme.css
  public/themes/md-dark-indigo/theme.css
  public/themes/md-light-deeppurple/theme.css
  public/themes/md-light-indigo/theme.css
  public/themes/mdc-dark-deeppurple/theme.css
  public/themes/mdc-dark-indigo/theme.css
  public/themes/mdc-light-deeppurple/theme.css
  public/themes/mdc-light-indigo/theme.css
  public/themes/mira/theme.css
  public/themes/nano/theme.css
  public/themes/nova-accent/theme.css
  public/themes/nova-alt/theme.css
  public/themes/nova/theme.css
  public/themes/rhea/theme.css
  public/themes/saga-blue/theme.css
  public/themes/saga-green/theme.css
  public/themes/saga-orange/theme.css
  public/themes/saga-purple/theme.css
  public/themes/soho-dark/theme.css
  public/themes/soho-light/theme.css
  public/themes/tailwind-light/theme.css
  public/themes/vela-blue/theme.css
  public/themes/vela-green/theme.css
  public/themes/vela-orange/theme.css
  public/themes/vela-purple/theme.css
  public/themes/viva-dark/theme.css
  public/themes/viva-light/theme.css
Labels: Component: Theme

#4561 Fix #4158: Dialog/Confirm re-focus original element on close
  components/lib/confirmdialog/ConfirmDialog.js
  components/lib/confirmpopup/ConfirmPopup.js
  components/lib/dialog/Dialog.js
Labels: Core Team

#4564 Fix #4563: Paginator fix ARIA for page links
  components/lib/api/Locale.js
  components/lib/paginator/PageLinks.js
Labels: Core Team

#4573 Fix #4565: Carousel initialization
  components/lib/carousel/Carousel.js
Labels: Core Team

#4576 Fix #4571: Panel toggle methods
  components/doc/panel/toggleabledoc.js
  components/lib/panel/Panel.js
  components/lib/panel/panel.d.ts
Labels: Core Team

#4575 Fix #4570: Panel ref should not point to elementRef
  components/lib/panel/Panel.js
Labels: Core Team

#4582 Fix #4579: Calendar mask correct hook
  components/lib/calendar/Calendar.js
Labels: Core Team

#4583 Fix #4578: Calendar overlay size should be based on original view
  components/lib/calendar/Calendar.js
Labels: Core Team

#4584 Fix #4568: Calendar focus state should change when displaying panel
  components/lib/calendar/Calendar.js
Labels: Core Team

#4586 Fix #4585: DocSearch upgrade to fix NPE
  package-lock.json
  package.json
Labels: Core Team

#4587 Fix #4581: Fix DomHandler getScrollable to always include body or window
  components/lib/hooks/useOverlayScrollListener.js
  components/lib/utils/DomHandler.js
Labels: Core Team
