Repository primefaces/primereact, pull requests merged in 2023-12, with the labels that each got.

#5482 Fix #5477: ComponentBase fkey refactor
  components/lib/componentbase/ComponentBase.js
Labels: Core Team

#5483 Fix #5471: Calendar PT refactor
  components/doc/calendar/theming/tailwinddoc.js
  components/lib/calendar/Calendar.js
  components/lib/passthrough/tailwind/index.js
Labels: Core Team

#5484 Fix #5461: Passthrough TS and casing issues
  components/lib/accordion/accordion.d.ts
  components/lib/cascadeselect/cascadeselect.d.ts
  components/lib/passthrough/tailwind/index.js
  components/lib/tabview/tabview.d.ts
Labels: Core Team

#5486 Fix #5485: Messages restore close animation
  components/lib/messages/Messages.js
Labels: Core Team

#5456 Fix 5455 updating demo environments to vite
  components/doc/common/codeeditor/index.js
  components/doc/common/codeeditor/templates.js
  components/doc/common/docsectioncode.js
Labels: Core Team

#5491 Fix #5490: useDebounce fixed
  components/lib/hooks/useDebounce.js
Labels: Core Team

#5503 Fix #5492: Listbox passthrough fixes
  components/doc/listbox/theming/tailwinddoc.js
  components/lib/listbox/ListBoxItem.js
  components/lib/listbox/listbox.d.ts
  components/lib/passthrough/tailwind/index.js
Labels: Core Team

#5504 Fix #5493: Multiselect passthrough fixes
  components/doc/multiselect/theming/tailwinddoc.js
  components/lib/multiselect/MultiSelectHeader.js
  components/lib/multiselect/MultiSelectItem.js
  components/lib/multiselect/multiselect.d.ts
  components/lib/passthrough/tailwind/index.js
Labels: Core Team

#5506 Fix #5499: Autocomplete/Chips PT fixes
  components/doc/autocomplete/theming/tailwinddoc.js
  components/doc/chips/theming/tailwinddoc.js
  components/lib/autocomplete/AutoCompletePanel.js
  components/lib/autocomplete/autocomplete.d.ts
  components/lib/listbox/ListBoxItem.js
  components/lib/multiselect/MultiSelectItem.js
  components/lib/passthrough/tailwind/index.js
Labels: Core Team

#5516 Fix #5515: FileUpload Tailwind docs
  components/doc/fileupload/theming/tailwinddoc.js
Labels: Core Team

#5531 Fix #5530: Chip onRemove event pass value
  components/lib/chip/Chip.js
  components/lib/chip/chip.d.ts
Labels: Core Team

#5519 Fix #5512: Dropdown add tabindex for Tailwind
  components/lib/dropdown/Dropdown.js
Labels: Core Team

#5538 Fix #5535: Calendar update input on locale change
  components/lib/calendar/Calendar.js
Labels: Core Team

#5539 Fix #5533/#4147: Calendar respect viewDate
  components/lib/calendar/Calendar.js
Labels: Core Team

#5532 DataTable:converted to data- lookups instead of className lookups
  components/lib/datatable/BodyCell.js
  components/lib/datatable/DataTable.js
  components/lib/datatable/TableBody.js
Labels: Component: Tailwind

#5549 Fix #5546: AccordionTab Tailwind issues
  components/lib/accordion/Accordion.js
  components/lib/accordion/AccordionBase.js
Labels: Core Team

#5554 fix:#5553:TreeTable: need to be converted to data- lookups instead of className lookups
  components/lib/treetable/TreeTable.js
  components/lib/treetable/TreeTableScrollableView.js
Labels: Component: Tailwind

#5557 Fix #5555: BodyCell frozen issue
  components/doc/datatable/theming/tailwinddoc.js
  components/lib/datatable/BodyCell.js
  components/lib/passthrough/tailwind/index.js
Labels: Core Team

#5552 fix:InputNumber: Text selection not working on input focus when using a s…
  components/lib/inputnumber/InputNumber.js
Labels: Type: Bug

#5559 Fix #5558: Calendar previous/next fix
  components/doc/calendar/theming/tailwinddoc.js
  components/lib/calendar/Calendar.js
  components/lib/calendar/calendar.d.ts
  components/lib/passthrough/tailwind/index.js
Labels: Core Team

#5560 Fix #5556: RowEdit set value in useEffect
  components/lib/datatable/BodyCell.js
Labels: Core Team

#5562 Fix #5561: Inplace respect active prop
  components/lib/inplace/Inplace.js
Labels: Core Team

#5571 Fix #5568: MultiSelect filterInput PT
  components/doc/multiselect/theming/tailwinddoc.js
  components/lib/passthrough/tailwind/index.js
Labels: Core Team

#5525 Support `roundingMode` for InputNumber
  components/lib/inputnumber/InputNumber.js
  components/lib/inputnumber/InputNumberBase.js
  components/lib/inputnumber/inputnumber.d.ts
Labels: Type: Enhancement, Status: Pending Review

#5573 Fix #5572: Multselect selectAllLabel was being added to DOM
  components/lib/multiselect/MultiSelectBase.js
Labels: Core Team

#5579 Tooltip fix Tailwind CSS
  components/doc/tooltip/theming/tailwinddoc.js
  components/lib/passthrough/tailwind/index.js
Labels: Core Team

#5578 fix:Calendar:currentView changed should invoke alignOverlay
  components/lib/calendar/Calendar.js
Labels: Type: Bug

#5580 Fix #5574: Calendar Tailwind context.selected val
  components/lib/calendar/Calendar.js
Labels: Core Team

#5582 Fix #5574: Calendar Tailwind context.selected val
  components/lib/calendar/Calendar.js
Labels: Core Team

#5583 Fix #5574: Calendar Tailwind context.selected val
  components/lib/calendar/Calendar.js
Labels: Core Team

#5586 fix:Dialog:breakpoints not work
  components/lib/dialog/Dialog.js
Labels: Type: Bug

#5592 Fix #5588: TreeTable emptyMessage
  components/lib/datatable/datatable.d.ts
  components/lib/treetable/TreeTable.js
  components/lib/treetable/TreeTableBody.js
  components/lib/treetable/treetable.d.ts
Labels: Core Team

#5595 Fix #5591: TreeTable remove 'custom' sort need
  components/lib/treetable/TreeTable.js
Labels: Core Team

#5598 Fix #5597: TreeTable body align
  components/lib/treetable/TreeTableBase.js
  components/lib/treetable/TreeTableBodyCell.js
  components/lib/treetable/TreeTableHeader.js
Labels: Core Team

#5601 fix:TreeTable: missing import
  components/lib/treetable/TreeTableBody.js
Labels: Type: Bug

#5602 feat:Calendar:add disabledDate
  components/lib/calendar/Calendar.js
  components/lib/calendar/Calendar.spec.js
  components/lib/calendar/CalendarBase.js
Labels: Type: Enhancement

#5612 Fix #5609: ToggleButton focusedState
  components/doc/togglebutton/theming/tailwinddoc.js
  components/lib/passthrough/tailwind/index.js
  components/lib/togglebutton/ToggleButton.js
Labels: Core Team

#5614 Fix #5610: Radio/Checkbox always fire onClick
  components/lib/checkbox/Checkbox.js
  components/lib/radiobutton/RadioButton.js
Labels: Core Team

#5608 fix:InputNumber's issue when Locale set de-DE
  components/lib/inputnumber/InputNumber.js
Labels: Type: Bug

#5618 Formatted icons
  components/lib/icons/sortamountdown/index.js
  components/lib/icons/sortamountupalt/index.js
Labels: Core Team

#5624 Fix #5623 - Otherprops not working for InputSwitch
  components/lib/inputswitch/InputSwitch.js
Labels: Core Team

#5628 fix:Image preview zoom in bug
  components/lib/image/Image.js
Labels: Type: Bug

#5625 fix:Calendar not showing correctly in Table
  components/lib/calendar/Calendar.js
Labels: Type: Bug

#5634 fix:format error when Locale set de-DE
  components/lib/inputnumber/InputNumber.js
Labels: Type: Bug

#5636 Fix #5635: Maximizable dialog after move
  components/lib/dialog/DialogBase.js
Labels: Core Team

#5638 Fix #5637: Sidebar aria-label close
  components/lib/sidebar/Sidebar.js
Labels: Core Team

#5641 Fix #5640: Column dynamically evaluate rowEditor
  components/doc/datatable/edit/roweditdoc.js
  components/lib/datatable/BodyCell.js
Labels: Core Team

#5647 Accept array as PT value
  components/lib/componentbase/ComponentBase.js
Labels: Type: Enhancement

#5659 Fix #5652: Ripple set deprecated static when context is changed
  components/doc/confirmpopup/headlessdoc.js
  components/doc/dropdown/editabledoc.js
  components/lib/api/PrimeReact.js
  components/lib/api/PrimeReactContext.js
  components/lib/confirmdialog/confirmdialog.d.ts
  components/lib/dialog/dialog.d.ts
  components/lib/panel/Panel.js
  components/lib/toast/toast.d.ts
Labels: Core Team

#5658 fix:ConfirmDialog：confirmDialog method in unstyled mode, the pop-up w…
  components/lib/confirmdialog/ConfirmDialog.js
Labels: Type: Bug

#5660 Fix #5651: GroupRowsBy handle dates and objects
  components/lib/datatable/TableBody.js
  components/lib/utils/ObjectUtils.js
Labels: Core Team

#5663 Fix #5661: Dialog footerClassName
  components/lib/dialog/DialogBase.js
Labels: Core Team

#5665 Fix #5664: FileUpload progress template
  components/lib/fileupload/FileUpload.js
  components/lib/fileupload/fileupload.d.ts
Labels: Core Team
