Repository primefaces/primereact, pull requests merged in 2023-03, with the labels that each got.

#4094 Fix #4093: Button size docs corrected
  components/lib/button/button.d.ts
Labels: Typescript, Core Team

#4111 Fix #4108: Button severity add "help"
  components/doc/common/apidoc/index.json
  components/lib/button/button.d.ts
Labels: Typescript, Core Team

#4121 Fix #4093: Button: Size 'large' or 'lg'
  components/doc/common/apidoc/index.json
  components/lib/button/Button.js
  components/lib/button/button.d.ts
Labels: Type: Enhancement

#4106 F missing in filter example causing Code Sandbox not to run
  components/doc/dropdown/filterdoc.js
Labels: Component: Documentation, Core Team

#4130 Fix #4129: MutliSelect typescript filter update
  components/lib/multiselect/multiselect.d.ts
Labels: Typescript, Core Team

#4131 #4110 added float label css selector for tooltipOption showOnDisabled
  components/lib/inputtext/InputText.css
Labels: Status: Pending Review

#4124 Update sizesdoc.js
  components/doc/inputtext/sizesdoc.js
Labels: Status: Pending Review, Component: Documentation

#4087 Implement api for getting mock data
  next.config.js
  package-lock.json
  package.json
  pages/api/data/customers.js
  public/data/customers-large.json
  service/CustomerService.js
Labels: Core Team

#4182 Fix #4179: Tree drag drop typescript update
  components/doc/common/apidoc/index.json
  components/lib/tree/tree.d.ts
Labels: Typescript, Core Team

#4164 Fix #4163: Calendar view typescript def
  components/doc/calendar/basicdoc.js
  components/doc/calendar/buttonbardoc.js
  components/doc/calendar/datetemplatedoc.js
  components/doc/calendar/floatlabeldoc.js
  components/doc/calendar/formatdoc.js
  components/doc/calendar/icondoc.js
  components/doc/calendar/inlinedoc.js
  components/doc/calendar/localedoc.js
  components/doc/calendar/minmaxdoc.js
  components/doc/calendar/monthpickerdoc.js
  components/doc/calendar/multipledoc.js
  components/doc/calendar/multiplemonthsdoc.js
  components/doc/calendar/rangedoc.js
  components/doc/calendar/timedoc.js
  components/doc/calendar/touchuidoc.js
  components/doc/calendar/yearpickerdoc.js
  components/doc/common/apidoc/index.json
  components/lib/calendar/calendar.d.ts
Labels: Typescript, Core Team
