Repository primefaces/primereact, pull requests merged in 2023-09, with the labels that each got.

#4856 Fix #4854: Datatable showRowReorder render NULL instead of false
  components/lib/datatable/BodyCell.js
Labels: Core Team

#4865 Fix #4845: Datatable menu filter with singular text field
  components/lib/datatable/ColumnFilter.js
Labels: Core Team

#4869 Fix #4866: Calendar support mask slotChar
  components/lib/calendar/Calendar.js
  components/lib/calendar/CalendarBase.js
  components/lib/calendar/calendar.d.ts
Labels: Core Team

#4871 Fix #4858: AutoComplete add required property
  components/lib/autocomplete/AutoComplete.js
  components/lib/autocomplete/autocomplete.d.ts
  components/lib/passthrough/tailwind/index.js
Labels: Core Team

#4870 Fix #4872: Added filesizeTypes Locale
  components/doc/common/apidoc/index.json
  components/lib/api/Locale.js
  components/lib/api/api.d.ts
  components/lib/fileupload/FileUpload.js
  components/lib/hooks/useLocale.js
Labels: Type: Enhancement

#4876 Fix #4845: Menu filter bug fix switching match mode
  components/lib/datatable/ColumnFilter.js
Labels: Core Team

#4818 PR4814: fix deeply nested replace on row edit
  components/lib/datatable/BodyCell.js
  components/lib/utils/ObjectUtils.js
  components/lib/utils/utils.d.ts
Labels: Type: Bug, Status: Pending Review

#4880 Fix #4878: DomHandler typescript fixes
  components/lib/utils/utils.d.ts
Labels: Core Team

#4884 Fix #4882: InputMask AutoFocus
  components/lib/inputmask/InputMask.js
  components/lib/inputtext/InputText.js
Labels: Core Team

#4896 Docs typo fix
  components/doc/chart/chartjsdoc.js
Labels: Component: Documentation

#4898 Fix #4893: Accordion controlled docs missing useState
  components/doc/accordion/controlleddoc.js
Labels: Core Team

#4899 Fix #4891: Tooltip typescript update
  components/lib/tooltip/tooltip.d.ts
Labels: Core Team

#4886 docs: Changed Height Picklist component
  components/doc/picklist/basicdoc.js
  components/doc/picklist/filterdoc.js
  components/doc/picklist/pt/ptdoc.js
Labels: Component: Documentation

#4904 Fix #4875: InputNumber minus sign with currency
  components/lib/inputnumber/InputNumber.js
Labels: Core Team

#4907 Fix #4906: Slider pageX error on mobile when undefined.
  components/lib/slider/Slider.js
Labels: Core Team

#4908 Fix #4892: Calendar highlight selected months and years in multiple mode
  components/lib/calendar/Calendar.js
Labels: Core Team

#4915 Fix #4914: Column FilterMatchModes typescript definition.
  components/lib/column/column.d.ts
Labels: Core Team

#4918 Fix #4917: Datatable/Calendar doc props
  api-generator/build-apidoc.js
  components/doc/common/apidoc/index.json
  components/doc/common/docapisection.js
  components/lib/calendar/calendar.d.ts
  components/lib/datatable/datatable.d.ts
Labels: Core Team

#4921 Fix #4920: Boolean inputs use FormBooleanEvent
  components/lib/checkbox/checkbox.d.ts
  components/lib/inputswitch/inputswitch.d.ts
  components/lib/radiobutton/radiobutton.d.ts
  components/lib/ts-helpers.d.ts
Labels: Core Team

#4925 Fix #4834: Calendar focus and inputwrapper-focus
  components/lib/calendar/Calendar.js
  components/lib/splitter/__snapshots__/Splitter.spec.js.snap
Labels: Core Team

#4935 Fix #4934: Password keydown called twice
  components/lib/blockui/__snapshots__/BlockUI.spec.js.snap
  components/lib/password/Password.js
  components/lib/password/PasswordBase.js
  components/lib/splitter/__snapshots__/Splitter.spec.js.snap
Labels: Core Team

#4946 Fix #4940: scroll block applied incorrectly in some cases
  components/lib/dialog/Dialog.js
Labels: Type: Enhancement

#4947 Fix TS issues
  components/lib/chip/chip.d.ts
  components/lib/galleria/galleria.d.ts
  components/lib/image/image.d.ts
Labels: Core Team

#4949 Fix #4948: FileUpload click instead of mousedown
  components/lib/fileupload/FileUpload.js
Labels: Core Team

#3239 Fix #3238: Remove IE Support
  components/lib/calendar/Calendar.js
  components/lib/fileupload/FileUpload.js
Labels: Core Team

#4950 Fix #4932: Menu respect ID field
  components/lib/breadcrumb/BreadCrumb.js
  components/lib/contextmenu/ContextMenu.js
  components/lib/contextmenu/ContextMenuSub.js
  components/lib/dock/Dock.js
  components/lib/megamenu/MegaMenu.js
  components/lib/menu/Menu.js
  components/lib/menubar/Menubar.js
  components/lib/menubar/MenubarSub.js
  components/lib/panelmenu/PanelMenu.js
  components/lib/panelmenu/PanelMenuSub.js
  components/lib/slidemenu/SlideMenu.js
  components/lib/slidemenu/SlideMenuSub.js
  components/lib/steps/Steps.js
  components/lib/tabmenu/TabMenu.js
  components/lib/tieredmenu/TieredMenu.js
  components/lib/tieredmenu/TieredMenuSub.js
Labels: Core Team

#4953 fix Primefaces #4952 ConfirmPopup: Escape key does not close the popup.
  components/doc/common/apidoc/index.json
  components/lib/confirmpopup/ConfirmPopup.js
  components/lib/confirmpopup/ConfirmPopupBase.js
  components/lib/confirmpopup/confirmpopup.d.ts
Labels: Type: Enhancement

#4957 Fix #4956: Megmenu allow URL to be top level submenu
  components/lib/megamenu/MegaMenu.js
Labels: Core Team

#4962 fix Primefaces #4961 SlideMenu: SlideMenu with popup prop passed doesnot close on Escape keypress.
  components/doc/common/apidoc/index.json
  components/lib/slidemenu/SlideMenu.js
  components/lib/slidemenu/SlideMenuBase.js
  components/lib/slidemenu/slidemenu.d.ts
Labels: Type: Enhancement

#4965 Fix #4960: TreeTable column footer missing props
  components/lib/treetable/TreeTableFooter.js
Labels: Core Team

#4967 MultiSelect label now uses props.values instead of props.options
  components/lib/multiselect/MultiSelect.js
Labels: Type: Enhancement

#4966 Fix #4675: ESM module use .mjs instead of .js
  rollup.config.js
Labels: Core Team

#4976 Fix #4946: Dialog scroll block tracking
  components/lib/blockui/__snapshots__/BlockUI.spec.js.snap
  components/lib/dialog/Dialog.js
Labels: Core Team

#4989 Fix #4983: Radiobutton typescript FormEvent
  components/lib/radiobutton/radiobutton.d.ts
Labels: Core Team

#4991 Fix #4988: MultiSelect fix for optionValue
  components/lib/multiselect/MultiSelect.js
Labels: Core Team
