Repository primefaces/primereact, pull requests merged in 2023-04, with the labels that each got.

#4262 Fix #4261: TabView make icons optional
  components/lib/tabview/tabview.d.ts
Labels: Core Team

#4263 Fix #4258: Message omit content attribute
  components/lib/message/message.d.ts
  package-lock.json
Labels: Core Team

#4234 Fix #4233: Calendar decadeTemplate spelling
  components/doc/common/apidoc/index.json
  components/lib/calendar/calendar.d.ts
Labels: Core Team

#4232 Fix #4231: Password omit content attribute
  components/lib/password/password.d.ts
Labels: Core Team

#4224 Fix #4222: Update API docs
  api-generator/components/calendar.js
  api-generator/components/captcha.js
  api-generator/components/cascadeselect.js
  api-generator/components/gmap.js
Labels: Component: Documentation, Core Team

#4218 Fix #4215: Dropdown RHF example
  components/doc/dropdown/form/hookformdoc.js
Labels: Core Team

#4201 Fix #4198: Mention add ref to docs
  components/doc/common/apidoc/index.json
Labels: Core Team

#4260 Fix #4259: Calendar unique month key for multiple months
  components/lib/calendar/Calendar.js
Labels: Core Team

#4255 Fix #4254: Paginator alwaysShow fix
  components/lib/paginator/Paginator.js
Labels: Core Team

#4250 Fix #4249: Picklist use filterTemplate properly
  components/lib/picklist/PickList.js
Labels: Core Team

#4246 Fix #4244: BodyRow add rowindex to key
  components/lib/datatable/BodyRow.js
Labels: Core Team

#4239 Fix #4238: Datatable performance issue when not editable
  components/doc/common/apidoc/index.json
  components/lib/datatable/DataTableBase.js
Labels: Core Team

#4225 Fix #4221: Mention target must always be input textarea
  components/lib/mention/Mention.js
Labels: Core Team

#4247 Fix #4011: TieredMenu wrong id on menu items
  components/lib/tieredmenu/TieredMenuSub.js
Labels: Core Team

#4217 Fix #4197: InputTextArea reset height when clearing out all text
  components/lib/inputtextarea/InputTextarea.js
Labels: Core Team

#4236 Fix #4235: Tabview check for conditionally rendered panels
  components/lib/tabview/TabView.js
Labels: Core Team

#4066 Fix #4062: Add pi-arrow-right-arrow-left
  components/lib/api/PrimeIcons.js
Labels: Core Team

#4266 Fix #4259: Calendar unique month key for multiple months
  components/lib/calendar/Calendar.js
Labels: Core Team

#4237 Update basicdoc.js
  components/doc/confirmpopup/basicdoc.js
Labels: Component: Documentation

#4178 Fix #2666: DataTable: Cell edit support Dropdown.
  components/lib/datatable/BodyCell.js
Labels: Status: Pending Review

#4271 Fix #4269: Datatable fix NPE on MultiSort with removableSort
  components/lib/datatable/DataTable.js
Labels: Core Team

#4274 Fix #4273: Image add missing props
  components/doc/common/apidoc/index.json
  components/lib/image/Image.js
  components/lib/image/ImageBase.js
  components/lib/image/image.d.ts
Labels: Core Team

#4280 Fix #4248: Datatable Strict mode issue
  components/lib/datatable/DataTable.js
Labels: Core Team

#4287 [FIX] - Correction of the documentation of the sidebar position example
  components/doc/sidebar/positiondoc.js
Labels: Component: Documentation

#4290 Fix #4289: InputMask autoClear doc default
  components/lib/inputmask/inputmask.d.ts
Labels: Core Team

#4296 Fix #4200: Panel Footer Option
  components/lib/panel/Panel.js
  components/lib/panel/PanelBase.js
  components/lib/panel/panel.d.ts
Labels: Type: New Feature

#3983 Fix #3982: Charts add accessibility to canvas
  api-generator/components/chart.js
  components/lib/chart/Chart.js
  components/lib/chart/chart.d.ts
Labels: Core Team

#3980 Fix #3975: Column exportHeader property
  api-generator/components/column.js
  components/lib/column/column.d.ts
  components/lib/datatable/DataTable.js
Labels: Core Team

#3963 Fix #3962: Dialog dismissible mask must initiate pointer down
  components/lib/dialog/Dialog.js
  components/lib/dialog/dialog.d.ts
Labels: Core Team

#4214 Fix #4168: ConfirmDialog/Popup prevent multiple clicks
  components/lib/confirmdialog/ConfirmDialog.js
  components/lib/confirmpopup/ConfirmPopup.js
Labels: Core Team

#4302 Fix #4300: Image add attributes to main image
  components/lib/image/Image.js
Labels: Core Team

#4303 Fix #4301: Carousel never controlled while in autoplay
  components/lib/carousel/Carousel.js
Labels: Core Team

#4314 Fix #4313: Dialog fix maximized check
  components/lib/dialog/Dialog.js
  components/lib/dialog/DialogBase.js
Labels: Core Team

#4316 Fix #4315: Datatable typescript updates
  components/doc/datatable/cellselection/disableddoc.js
  components/doc/datatable/cellselection/eventsdoc.js
  components/doc/datatable/cellselection/multipledoc.js
  components/doc/datatable/cellselection/singledoc.js
  components/doc/datatable/rowselection/checkboxdoc.js
  components/doc/datatable/rowselection/disableddoc.js
  components/doc/datatable/rowselection/eventsdoc.js
  components/doc/datatable/rowselection/multipledoc.js
  components/doc/datatable/rowselection/radiobuttondoc.js
  components/doc/datatable/rowselection/singledoc.js
  components/doc/datatable/samples/productsdoc.js
  components/lib/datatable/datatable.d.ts
Labels: Core Team

#4317 Row Expansion typescript example updates
  components/doc/datatable/rowexpansiondoc.js
  components/doc/datatable/rowgroup/expandabledoc.js
Labels: Typescript

#4318 Datatable customers demo fix
  components/doc/datatable/samples/customersdoc.js
Labels: Component: Documentation
