Repository primefaces/primereact, pull requests merged in 2023-11, with the labels that each got.

#5207 fix: Some Tailwind classes for panelmenu
  components/lib/passthrough/tailwind/index.js
Labels: Component: Tailwind

#5211 Fix #5205: MenuItem missing command callback
  api-generator/build-apidoc.js
  components/doc/common/apidoc/index.json
Labels: Core Team

#5212 Fix #5210: Multiselect align overlay after filtering
  components/lib/multiselect/MultiSelect.js
Labels: Core Team

#5217 Fix #5203: ComponentBase context could be undefined
  components/lib/componentbase/ComponentBase.js
Labels: Core Team

#5225 Fix #5216: fix the Mention bug to keeps the search text
  components/lib/mention/Mention.js
Labels: Type: Bug

#5232 fix(input-number): when zero is entered, value displayed isn't expected
  components/lib/inputnumber/InputNumber.js
Labels: Type: Bug

#5236 Fix OverlayPanel Toast
  components/doc/overlaypanel/datatabledoc.js
Labels: Core Team

#5239 perf(tab-view): shouldUseTab method replaces index with tab.key
  components/lib/tabview/TabView.js
  components/lib/tabview/tabview.d.ts
Labels: Type: Performance

#5248 Fix #5247: Multiselect onRemove event
  components/lib/multiselect/MultiSelect.js
  components/lib/multiselect/MultiSelectBase.js
  components/lib/multiselect/multiselect.d.ts
Labels: Core Team

#5249 Fix #5245: InputNumber prevent infinite loop
  components/lib/inputnumber/InputNumber.js
Labels: Core Team

#5251 Fix #5250: MultiSelect stopPropagation on checkbox
  components/lib/multiselect/MultiSelectItem.js
Labels: Core Team

#5257 Fix #5254: TreeNode PT incorrect props
  components/lib/tree/UITreeNode.js
Labels: Core Team

#5259 Fix #5255 - Added if condition for expanding menu item
  components/lib/panelmenu/PanelMenu.js
Labels: Core Team

#5263 Windows Dev instructions
  DEVELOPMENT.md
  package.json
  rollup.config.js
Labels: Component: Documentation

#5268 updated docs #5267
  components/doc/confirmdialog/theming/tailwinddoc.js
  components/doc/dialog/theming/tailwinddoc.js
Labels: Core Team

#5097 Fix #5096 - Component Styles: Remove use of !important now that @layer is used
  components/lib/cascadeselect/CascadeSelect.js
  components/lib/cascadeselect/CascadeSelectBase.js
  components/lib/componentbase/ComponentBase.js
  components/lib/contextmenu/ContextMenu.js
  components/lib/datatable/DataTable.js
  components/lib/datatable/DataTableBase.js
  components/lib/dialog/Dialog.js
  components/lib/dialog/DialogBase.js
  components/lib/megamenu/MegaMenu.js
  components/lib/overlaypanel/OverlayPanel.js
  components/lib/ripple/RippleBase.js
  components/lib/scrolltop/ScrollTopBase.js
  components/lib/tieredmenu/TieredMenu.js
  components/lib/treetable/TreeTableBase.js
Labels: Type: Bug

#5274 Fix #5273: Button plain prop for unstyled
  components/lib/button/ButtonBase.js
  components/lib/button/button.d.ts
Labels: Core Team

#5277 Fix #5276: Splitter prevent error on state storage
  components/lib/splitter/Splitter.js
Labels: Core Team

#5275 Fix #5269: InputNumber buttons add aria-hidden
  components/lib/inputnumber/InputNumber.js
Labels: Core Team

#5279 #5278 Added plain prop into classes and updated demos
  components/doc/button/raisedtextdoc.js
  components/doc/button/textdoc.js
  components/lib/button/ButtonBase.js
Labels: Core Team

#5280 Fix #5270: Inputnumber clarity on id vs inputId.
  components/doc/inputnumber/accessibilitydoc.js
Labels: Core Team

#5282 Fix #5281/#5160: Revert fix causing infinite loop
  components/lib/datatable/DataTable.js
Labels: Core Team

#5284 Fix #5283: InputText size TS fix
  components/lib/inputtext/inputtext.d.ts
Labels: Core Team

#5287 Fix TopBar
  components/layout/topbar.js
Labels: Core Team

#5293 Fix #5288: Datatable add readonly frozenRow property
  components/lib/datatable/DataTableBase.js
  components/lib/datatable/datatable.d.ts
Labels: Core Team

#5295 Fix #5294: Tailwind fixes from PrimeVue
  components/doc/autocomplete/theming/tailwinddoc.js
  components/doc/dialog/theming/tailwinddoc.js
  components/doc/image/theming/tailwinddoc.js
  components/lib/passthrough/tailwind/index.js
Labels: Core Team

#5304 Fix 5303 Spacing inconsistency in code displays
  components/doc/common/codehighlight.js
Labels: Core Team

#5301 Fix #5300 tooltip with showondisabled prop breaks some input component style
  components/lib/tooltip/Tooltip.js
  components/lib/tooltip/TooltipBase.js
Labels: Core Team

#5305 Fix #5296: Tailwind dialog mask props
  components/doc/dialog/theming/tailwinddoc.js
  components/lib/dialog/Dialog.js
  components/lib/passthrough/tailwind/index.js
Labels: Core Team

#5286 fix(InputMask): Paste at Cursor Selection
  components/lib/inputmask/InputMask.js
Labels: Type: Bug

#5309 Fix #5308: Dropdown icon pass overlay visible state
  components/doc/dropdown/templatedoc.js
  components/lib/dropdown/Dropdown.js
Labels: Core Team

#5313 Fix #5311: AppendTo should be correct on mount
  components/lib/autocomplete/AutoComplete.js
  components/lib/calendar/Calendar.js
  components/lib/cascadeselect/CascadeSelect.js
  components/lib/colorpicker/ColorPicker.js
  components/lib/dropdown/Dropdown.js
  components/lib/mention/Mention.js
  components/lib/multiselect/MultiSelect.js
  components/lib/password/Password.js
  components/lib/splitbutton/SplitButton.js
  components/lib/treeselect/TreeSelect.js
Labels: Core Team

#5318 Fix #5316: Ripple docs
  components/doc/configuration/rippledoc.js
Labels: Core Team

#5319 Fix #5312: Tooltip left behind on slow machine
  components/lib/tooltip/Tooltip.js
Labels: Type: Bug, Core Team

#5322 fix: strength meter popup does not close on escape
  components/lib/password/Password.js
Labels: Type: Enhancement

#5325 Fix #5234: IconProps better SVG typescript support
  components/lib/utils/utils.d.ts
Labels: Core Team

#5331 Fix #5328: Showcase fixes
  components/news/newssection.js
  pages/landing/herosection.js
Labels: Core Team

#5334 Fix #5332: Fix hideOverlaysOnScrolling
  components/lib/hooks/useOverlayListener.js
Labels: Core Team

#5336 Fix #5333: Missing PrimeIcons
  components/lib/api/PrimeIcons.js
Labels: Core Team

#5339 fix(input-number): unable to input a decimal point
  components/lib/inputnumber/InputNumber.js
Labels: Type: Bug

#5341 Fix #4430: RowEdit icon customization fix
  components/lib/datatable/DataTable.js
Labels: Core Team

#5348 Fix #5347: Selection previous row with up arrow NPE
  components/lib/datatable/BodyRow.js
Labels: Core Team

#5364 fix: #5363, Mention: Page Breaks when navigating to Mention component
  components/lib/mention/Mention.js
Labels: Type: Bug

#5359 Fix #5349: PanelMenu fix from PrimeVue
  components/lib/panelmenu/PanelMenuBase.js
  jsconfig.json
Labels: Core Team

#5368 fix: fix speed dial menu not closing on escape
  components/lib/speeddial/SpeedDial.js
Labels: Type: Enhancement

#5366 fix: #5365, SplitButton: SplitButton popup not closing on escape button click
  components/lib/splitbutton/SplitButton.js
Labels: Type: Enhancement

#5361 fix: Cascade select popup not closing on escape
  components/lib/cascadeselect/CascadeSelect.js
Labels: Type: Enhancement

#5373 Fix #2666: Fix overlay components in cell editor
  components/lib/datatable/BodyCell.js
Labels: Core Team

#5375 Fix #5363: Mention better fix
  components/lib/mention/Mention.js
Labels: Core Team

#5377 Fix #5376: Tooltip content TS def
  components/lib/tooltip/tooltip.d.ts
Labels: Core Team

#5358 5357 updated misc demos
  components/doc/avatar/groupdoc.js
  components/doc/avatar/labeldoc.js
  components/doc/badge/buttondoc.js
  components/doc/blockui/basicdoc.js
  components/doc/blockui/templatedoc.js
  components/doc/skeleton/datatabledoc.js
  components/doc/styleclass/animationdoc.js
  components/doc/tag/templatedoc.js
  components/doc/terminal/basicdoc.js
Labels: Core Team

#5380 Fix #5378: Update local api.d.ts
  components/lib/api/api.d.ts
  pages/ripple/index.js
Labels: Core Team

#5381 Fix #5379: Accordion tab header passthrough errors
  components/lib/accordion/Accordion.js
  components/lib/accordion/accordion.d.ts
Labels: Core Team

#5386 Fix #5385: Password inputClassname missing
  components/lib/password/Password.js
Labels: Core Team

#5389 Update datatable.d.ts #5388
  components/lib/datatable/datatable.d.ts
Labels: Typescript

#5372 Fix #5370: TreeTable highlight selection in Checkbox mode
  components/lib/treetable/TreeTableRow.js
Labels: Core Team

#5392 Fix #5384: TreeTable support hidden columns
  components/lib/treetable/TreeTableHeader.js
  components/lib/treetable/TreeTableRow.js
Labels: Core Team

#5391 Fix #5390: Calendar only render navigator in first month of multiple months
  components/lib/calendar/Calendar.js
Labels: Core Team

#5317 Fix #5315: Treetable add alignment
  components/lib/treetable/TreeTableBase.js
  components/lib/treetable/TreeTableHeader.js
Labels: Core Team

#5394 Fix #5393: Tree propagate icons to leaf nodes
  components/lib/tree/Tree.js
  components/lib/tree/UITreeNode.js
Labels: Core Team

#5396 Fix #5387: Tailwind TRANSITION docs
  components/doc/menu/theming/tailwinddoc.js
  components/doc/tieredmenu/theming/tailwinddoc.js
Labels: Core Team

#5402 Fix #5398: Slider with min value rendered incorrectly
  components/lib/slider/Slider.js
Labels: Core Team

#5403 Fix #5340: MutliSelect emptyMessage don't add to DOM
  components/lib/multiselect/MultiSelectBase.js
Labels: Core Team

#5405 Fix #4190: Chip aria fixes
  components/lib/chip/Chip.js
  components/lib/chips/Chips.js
Labels: Core Team

#5406 Fix #4883: Splitbutton PT docs
  components/lib/splitbutton/splitbutton.d.ts
Labels: Core Team

#5419 Fix #5414: p-disabled for svg icons
  components/lib/componentbase/ComponentBase.js
Labels: Core Team

#5397 Fix #5233: Cell editor ColumnEditorOptions param fix
  components/lib/datatable/BodyCell.js
Labels: Core Team

#5431 Fix #5427: TreeTable invalid DOM props
  components/lib/treetable/TreeTableHeader.js
Labels: Core Team

#5441 Fix #5440: InputText only print className once
  components/lib/inputtext/InputText.js
  components/lib/inputtext/InputText.spec.js
  components/lib/inputtext/InputTextBase.js
  components/lib/inputtext/__snapshots__/InputText.spec.js.snap
Labels: Core Team

#5442 Dependency Updates and Test fixes
  components/doc/datatable/lazyloaddoc.js
  components/doc/datatable/virtualscroll/lazydoc.js
  components/doc/virtualscroller/lazydoc.js
  components/lib/chip/Chip.spec.js
  components/lib/chip/__snapshots__/Chip.spec.js.snap
  components/lib/passthrough/tailwind/index.js
  package-lock.json
  package.json
Labels: Core Team

#5449 Fix #5447: TreeSelect don't close panel on unselect
  components/lib/treeselect/TreeSelect.js
Labels: Core Team

#5436 Fix #5435: Calendar min width if input is too small
  components/lib/calendar/Calendar.js
Labels: Core Team

#5433 Fix #5425: CascadeSelect fix for StrictMode
  components/lib/cascadeselect/CascadeSelect.js
  components/lib/cascadeselect/CascadeSelectSub.js
Labels: Core Team

#5434 Fix #5202: Calendar rendering performance increase
  components/lib/calendar/Calendar.js
  components/lib/hooks/useStyle.js
  components/lib/ripple/Ripple.js
Labels: Core Team, Type: Performance

#5021 fix(Dialog): "esc" key close dialogs in wrong order
  components/doc/common/apidoc/index.json
  components/lib/cascadeselect/CascadeSelect.js
  components/lib/confirmpopup/ConfirmPopup.js
  components/lib/dialog/Dialog.js
  components/lib/hooks/Hooks.js
  components/lib/hooks/hooks.d.ts
  components/lib/hooks/useDisplayOrder.js
  components/lib/hooks/useGlobalOnEscapeKey.js
  components/lib/hooks/useOnEscapeKey.js
  components/lib/image/Image.js
  components/lib/menu/Menu.js
  components/lib/overlaypanel/OverlayPanel.js
  components/lib/password/Password.js
  components/lib/sidebar/Sidebar.js
  components/lib/slidemenu/SlideMenu.js
  components/lib/speeddial/SpeedDial.js
  components/lib/splitbutton/SplitButton.js
Labels: Type: Enhancement

#5451 Fix #5445: Tabview passthrough fixes
  components/doc/tabview/theming/tailwinddoc.js
  components/lib/accordion/Accordion.js
  components/lib/passthrough/tailwind/index.js
  components/lib/tabview/TabView.js
Labels: Core Team

#5454 Fix #5452: Datatable onRowEditChange typescript def
  components/lib/datatable/datatable.d.ts
Labels: Core Team

#5416 Fix 5415 Action buttons should disabled if any item is not selected
  components/lib/orderlist/OrderListControls.js
Labels: Core Team

#5458 Fix #5457: TabMenu fix tailwind styling
  components/doc/tabmenu/theming/tailwinddoc.js
  components/lib/passthrough/tailwind/index.js
  components/lib/tabmenu/TabMenu.js
Labels: Core Team

#5470 Fix #5461: Passthrough case insensitve props
  components/lib/componentbase/ComponentBase.js
  components/lib/confirmdialog/confirmdialog.d.ts
  components/lib/passthrough/tailwind/index.js
Labels: Core Team

#5473 Fix #5465: Sidebar passthrough fix
  components/lib/sidebar/sidebar.d.ts
Labels: Core Team

#5474 Fix #5466: Slider remove handlers
  components/doc/slider/theming/tailwinddoc.js
  components/lib/passthrough/tailwind/index.js
Labels: Core Team

#5475 Fix #5464: Tailwind fixes
  components/doc/inputnumber/theming/tailwinddoc.js
  components/doc/speeddial/theming/tailwinddoc.js
  components/lib/confirmdialog/confirmdialog.d.ts
  components/lib/passthrough/tailwind/index.js
  components/lib/tooltip/tooltip.d.ts
Labels: Core Team
