Repository primefaces/primereact, pull requests merged in 2023-05, with the labels that each got.

#4331 Fix #4327: Datatable allow custom filter icons
  components/lib/datatable/ColumnFilter.js
  components/lib/datatable/DataTable.js
  components/lib/datatable/DataTableBase.js
  components/lib/datatable/HeaderCell.js
  components/lib/datatable/datatable.d.ts
Labels: Core Team

#4338 Fix #4333: Revert #2666
  components/lib/datatable/BodyCell.js
Labels: Core Team

#3971 Fix #3970: DataTable in expand mode resizing problem.
  components/lib/datatable/DataTable.js
Labels: Status: Pending Review

#4340 Fix #4339: Allow control of cell editor
  components/lib/column/column.d.ts
  components/lib/datatable/BodyCell.js
Labels: Core Team

#4355 Fix #4353: useStorage hook default to initialValue not undefined
  components/lib/hooks/useStorage.js
  components/lib/progressspinner/ProgressSpinner.js
  components/lib/progressspinner/ProgressSpinnerBase.js
  components/lib/tag/Tag.js
Labels: Core Team

#4357 Fix #4348: Dropdown optionGroupChildren fix
  components/lib/dropdown/Dropdown.js
  components/lib/dropdown/DropdownBase.js
  components/lib/dropdown/dropdown.d.ts
  components/lib/scrolltop/ScrollTop.js
  components/lib/splitter/__snapshots__/Splitter.spec.js.snap
  pages/scrolltop/index.js
Labels: Core Team

#4364 Fix #4350: Update messages examples and useMountEffect
  components/doc/messages/basicdoc.js
  components/doc/messages/closeabledoc.js
  components/doc/messages/severitydoc.js
  components/doc/messages/stickydoc.js
  components/doc/messages/templatedoc.js
  components/lib/hooks/useMountEffect.js
  components/lib/toast/toast.d.ts
Labels: Core Team

#4365 #4360: Button prevent duplicate classname
  components/lib/button/ButtonBase.js
  components/lib/button/__snapshots__/Button.spec.js.snap
Labels: Core Team

#4369 Fix #4368: Organization Chart selection changed typescript
  components/lib/organizationchart/organizationchart.d.ts
Labels: Core Team

#4372 Fix #4360: Button fix icon loading class
  components/lib/button/Button.js
Labels: Core Team

#4376 Fix #4375: Events forward stopPropagation and preventDefault
  components/lib/autocomplete/AutoComplete.js
  components/lib/calendar/Calendar.js
  components/lib/checkbox/Checkbox.js
  components/lib/chips/Chips.js
  components/lib/colorpicker/ColorPicker.js
  components/lib/dropdown/Dropdown.js
  components/lib/inputmask/InputMask.js
  components/lib/inputnumber/InputNumber.js
  components/lib/inputswitch/InputSwitch.js
  components/lib/listbox/ListBox.js
  components/lib/multiselect/MultiSelect.js
  components/lib/multistatecheckbox/MultiStateCheckbox.js
  components/lib/radiobutton/RadioButton.js
  components/lib/rating/Rating.js
  components/lib/selectbutton/SelectButton.js
  components/lib/togglebutton/ToggleButton.js
  components/lib/treeselect/TreeSelect.js
  components/lib/tristatecheckbox/TriStateCheckbox.js
Labels: Core Team

#4361 Fix #4356: Radio/Checkbox add onClick handling
  components/lib/checkbox/Checkbox.js
  components/lib/checkbox/CheckboxBase.js
  components/lib/checkbox/checkbox.d.ts
  components/lib/radiobutton/RadioButton.js
  components/lib/radiobutton/RadioButtonBase.js
  components/lib/radiobutton/radiobutton.d.ts
Labels: Status: Pending Review, Core Team

#4378 Fix #4174 and #4328: TreeNode and MenuItem TS updates
  components/doc/common/apidoc/index.json
  components/lib/menuitem/menuitem.d.ts
  components/lib/tree/tree.d.ts
  components/lib/treenode/treenode.d.ts
  components/lib/treeselect/treeselect.d.ts
  components/lib/treetable/treetable.d.ts
  pages/tree/index.js
  pages/treeselect/index.js
  pages/treetable/index.js
Labels: Core Team

#4379 Fix #4267 ColorPicker input style and class
  components/lib/colorpicker/ColorPicker.js
  components/lib/colorpicker/ColorPickerBase.js
  components/lib/colorpicker/colorpicker.d.ts
Labels: Core Team

#4380 Fix #4150: Tree togglerTemplate demo
  components/doc/tree/templatedoc.js
Labels: Core Team

#4387 Fix #4337: Datatable showHeaders property
  components/lib/datatable/DataTable.js
  components/lib/datatable/DataTableBase.js
  components/lib/datatable/datatable.d.ts
Labels: Core Team

#4390 Fix #4126: Calendar autoFocus property
  components/lib/calendar/Calendar.js
  components/lib/calendar/CalendarBase.js
  components/lib/calendar/calendar.d.ts
Labels: Core Team

#4398 Fix #4105: Calendar year/month navigator not deprecated
  components/lib/calendar/calendar.d.ts
Labels: Core Team

#4399 Fix #4397: ConfirmDialog missing header
  components/lib/confirmdialog/ConfirmDialog.js
Labels: Core Team

#4406 Fix #4402: Checkbox/Radio click label
  components/lib/checkbox/Checkbox.js
  components/lib/radiobutton/RadioButton.js
Labels: Core Team

#4415 Fix #4211: Datatable attribute selector use Ref not state
  components/lib/datatable/DataTable.js
Labels: Core Team

#4416 Fix #3753: Menu add popupAlignment property
  components/doc/menu/popupdoc.js
  components/lib/menu/Menu.js
  components/lib/menu/MenuBase.js
  components/lib/menu/menu.d.ts
  components/lib/utils/DomHandler.js
Labels: Core Team

#4429 Fix #4427: Multiselect clear icon
  components/doc/multiselect/basicdoc.js
  components/lib/multiselect/MultiSelect.js
Labels: Core Team

#4433 Fix #4430: Row editor icon overrides
  components/lib/datatable/BodyRow.js
  components/lib/datatable/DataTable.js
  components/lib/datatable/TableBody.js
Labels: Core Team

#4434 Fix typedef of PaginatorPageChangeEvent
  components/lib/paginator/paginator.d.ts
Labels: Typescript

#4440 Fix #4439: filterIcon and filterClearIcon not propagated
  components/lib/datatable/TableHeader.js
Labels: Core Team

#2757 Fix #2683: Overlays should close on browser scroll
  components/doc/configuration/hideoverlaysdoc.js
  components/layout/config.js
  components/layout/layout.js
  components/lib/api/PrimeReact.js
  components/lib/api/api.d.ts
  components/lib/hooks/useOverlayScrollListener.js
  components/lib/utils/ConnectedOverlayScrollHandler.js
  components/lib/utils/DomHandler.js
  components/lib/utils/utils.d.ts
  pages/configuration/index.js
Labels: Core Team

#4447 Fix #4446 Dropdown footer was using wrong style name
  components/lib/dropdown/DropdownPanel.js
Labels: Core Team

#4444 Fix #4443: InputNumber preventing ripple on buttons
  components/lib/inputnumber/InputNumber.js
Labels: Core Team

#4451 Datatable typescript filter demos
  components/doc/datatable/filter/advanceddoc.js
  components/doc/datatable/filter/basicdoc.js
Labels: Component: Documentation

#4457 Fix #4455: TS hideOverlaysOnDocumentScrolling
  components/lib/api/api.d.ts
  components/lib/utils/utils.d.ts
Labels: Core Team

#4458 Fix #4456: Calendar showMinMaxRange NPE
  components/lib/calendar/Calendar.js
Labels: Core Team

#4460 Passthrough typescript fixes
  components/lib/card/card.d.ts
  components/lib/slidemenu/slidemenu.d.ts
  components/lib/splitter/splitter.d.ts
  components/lib/toolbar/toolbar.d.ts
Labels: Typescript

#4464 Fix #4462: TabView do not scroll into view on page load
  components/lib/tabview/TabView.js
Labels: Core Team

#4469 Fix #4465: KeyFilter Android fix
  components/doc/keyfilter/presetsdoc.js
  components/lib/inputtext/InputText.js
  components/lib/inputtext/InputTextBase.js
  components/lib/inputtextarea/InputTextarea.js
  components/lib/inputtextarea/InputTextareaBase.js
  components/lib/keyfilter/KeyFilter.js
Labels: Core Team
