Repository primefaces/primereact, pull requests merged in 2023-07, with the labels that each got.

#4594 Fix #4171: Calendar onVisibleChange correct flag value
  components/lib/calendar/Calendar.js
Labels: Core Team

#4595 Fix #3990: MultiSelect selectAll fixes
  components/lib/multiselect/MultiSelect.js
  components/lib/multiselect/MultiSelectHeader.js
Labels: Core Team

#3939 Fix #3934: MultiSelect Add selectAllLabel
  components/doc/multiselect/styledoc.js
  components/lib/multiselect/MultiSelect.css
  components/lib/multiselect/MultiSelectHeader.js
  components/lib/multiselect/MultiSelectPanel.js
  components/lib/multiselect/multiselect.d.ts
Labels: Type: Enhancement

#4596 Fix #3934: Docs
  components/lib/multiselect/multiselect.d.ts
Labels: Core Team

#4588 Fix #4562: SlideMenu fix back button on long menus
  components/doc/slidemenu/basicdoc.js
  components/lib/slidemenu/SlideMenu.css
  components/lib/slidemenu/SlideMenu.js
Labels: Core Team

#4605 Fix #4604: Tooltip autohide fix
  components/doc/tooltip/autohidedoc.js
  components/lib/tooltip/Tooltip.js
Labels: Core Team

#4591 Feat #4485: add custom header prop to sidebar
  components/doc/sidebar/templatedoc.js
  components/lib/sidebar/Sidebar.css
  components/lib/sidebar/Sidebar.js
  components/lib/sidebar/sidebar.d.ts
Labels: Type: New Feature

#4607 Fix #900: Checkbox SVG is firing onRowClick
  components/lib/datatable/RowCheckbox.js
Labels: Core Team

#4615 Fix #4613: Passthrough was not calling functions
  components/lib/componentbase/ComponentBase.js
Labels: Core Team

#4616 Fix #4471: Column Resize fix for strict and non-strict mode
  components/lib/carousel/Carousel.js
  components/lib/datatable/DataTable.js
Labels: Core Team

#4618 Fix Build and tests
  components/lib/badge/BadgeBase.js
  components/lib/chart/ChartBase.js
  components/lib/chip/ChipBase.js
  components/lib/fieldset/FieldsetBase.js
  components/lib/inplace/InplaceBase.js
  components/lib/message/MessageBase.js
  components/lib/scrollpanel/ScrollPanelBase.js
  components/lib/scrolltop/ScrollTopBase.js
  components/lib/skeleton/SkeletonBase.js
  components/lib/toolbar/ToolbarBase.js
Labels: Core Team

#4620 Fix #4619: Fix build circular dependency
  components/lib/utils/ConnectedOverlayScrollHandler.js
  components/lib/utils/Utils.js
  components/lib/utils/utils.d.ts
Labels: Core Team

#4612 feat: add emptyMessage prop
  components/lib/multiselect/MultiSelectPanel.js
  components/lib/multiselect/multiselect.d.ts
Labels: Type: Enhancement

#4627 Fix #4622: PT props should be case insensitive
  components/lib/componentbase/ComponentBase.js
  components/lib/panel/Panel.js
  components/lib/utils/ObjectUtils.js
  components/lib/utils/utils.d.ts
Labels: Core Team

#4628 Fix #4626: Calendar allow month after year localization
  components/doc/calendar/localedoc.js
  components/lib/api/Locale.js
  components/lib/calendar/Calendar.js
  components/lib/hooks/useLocale.js
Labels: Core Team

#4630 Fix #4629: TreeTable do not allow reorder over frozen column
  components/lib/treetable/TreeTable.js
  components/lib/treetable/TreeTableHeader.js
Labels: Core Team

#4632 bug fix #4263
  components/lib/autocomplete/AutoComplete.js
Labels: Type: Bug

#4638 Fix #4636: ColumnFilter in row mode all custom icons
  components/lib/datatable/TableHeader.js
  components/lib/tag/TagBase.js
Labels: Core Team

#4642 feat: allow additional props from IconType to expose additional props in base object
  components/lib/datatable/datatable.d.ts
  components/lib/utils/utils.d.ts
Labels: Typescript

#4646 Added .p-fileupload-highlight class
  components/lib/fileupload/FileUpload.css
Labels: Type: Bug

#4652 Fix #4651: Toggle button hasIcon check
  components/lib/togglebutton/ToggleButton.js
Labels: Core Team

#4647 #4602: Add NONCE to inline style
  components/lib/hooks/useStyle.js
  components/lib/utils/DomHandler.js
  components/lib/utils/utils.d.ts
Labels: Core Team

#4653 Fix #4650: Keyfilter validateOnly example
  components/doc/keyfilter/regexdoc.js
  components/doc/keyfilter/regexworddoc.js
  pages/keyfilter/index.js
Labels: Core Team

#4659 Fix #4657: Datatable correct passthrough callback
  components/lib/datatable/BodyRow.js
  components/lib/datatable/TableBody.js
Labels: Core Team

#4663 Fix #4662: SVG icons allow click event to pass through
  components/lib/iconbase/IconBase.css
Labels: Core Team

#4677 Fix #4676: Passthrough allow `data-testid` or any arbitrary attribute
  components/lib/utils/utils.d.ts
Labels: Core Team

#4681 Fix #4680: Slider onSlideEnd have correct new value
  components/lib/slider/Slider.js
Labels: Core Team

#4685 Fix #3788: Carousel swipe events
  components/lib/carousel/Carousel.js
Labels: Type: Bug

#4688 Fix #4686: Slider prevent NaN on styles
  components/lib/slider/Slider.js
Labels: Core Team

#4470 Feature #4395 Add enabledDates prop in calendar comp
  api-generator/components/calendar.js
  components/doc/common/apidoc/index.json
  components/lib/calendar/Calendar.js
  components/lib/calendar/CalendarBase.js
  components/lib/calendar/calendar.d.ts
Labels: Type: New Feature

#4693 Fix #4692: Tree aria move from div to li
  components/lib/tree/UITreeNode.js
Labels: Core Team

#4694 Fix #4691: TreeNode checkbox aria-checked false
  components/lib/tree/UITreeNode.js
Labels: Core Team

#4695 Fix #4689: TreeTable onCellEditInit
  components/lib/treetable/TreeTableBodyCell.js
  components/lib/treetable/TreeTableRow.js
Labels: Core Team

#4697 Fix #4696: Filter arial-label
  components/lib/datatable/ColumnFilter.js
  components/lib/tree/Tree.js
Labels: Core Team

#4702 Fix #4654: DataTable. Filtering When Toggling Columns
  components/lib/datatable/DataTable.js
Labels: Type: Bug

#4703 Fix #3762: TreeSelect: Filtering does not select the nodes correctly
  components/lib/tree/Tree.js
  components/lib/tree/UITreeNode.js
  components/lib/treetable/TreeTable.js
  components/lib/treetable/TreeTableBody.js
  components/lib/treetable/TreeTableRow.js
  components/lib/utils/ObjectUtils.js
Labels: Type: Bug
