Repository primefaces/primereact, pull requests merged in 2024-11, with the labels that each got.

#7378 fix: #7377, MultiSelect: Cannot access the close Icon and clear the input using keyboard in Filled mode
  components/lib/multiselect/MultiSelect.js
Labels: Type: Bug

#7386 Fix #7439: Refactor multiselect
  components/lib/multiselect/MultiSelect.js
Labels: Core Team

#7401 fix(BodyCell): prevent cell or row refocus when overlay clicked
  components/lib/datatable/BodyCell.js
Labels: Type: Bug

#7411 update stickydoc.js to make the options more clear
  components/doc/toast/stickydoc.js
Labels: Component: Documentation

#7417 Fixing cssTransitionfalse does not disable animations globally
  components/lib/api/PrimeReactContext.js
  components/templates/TemplateLicense.js
Labels: Type: Bug

#7431 Fix: Dropdowmitem: Passing key directly without using spread
  components/lib/dropdown/DropdownItem.js
Labels: Type: Bug

#7446 Add 'help' as severity in splitbutton.d.ts
  components/lib/splitbutton/splitbutton.d.ts
Labels: Typescript
