Repository primefaces/primereact, pull requests merged in 2024-04, with the labels that each got.

#6264 Fix #6263: ButtonGroup use forwardRef properly
  components/lib/buttongroup/ButtonGroup.js
Labels: Core Team

#6294 Fix #6285: Calendar multiple months with yearNavigator
  components/doc/calendar/multiplemonthsdoc.js
  components/lib/calendar/Calendar.js
Labels: Core Team

#6314 Fix #6233: Column MatchMode Typescript fix
  components/lib/column/column.d.ts
  components/lib/passthrough/tailwind/index.js
Labels: Typescript

#6330 Fix #5187: TailWind Styled mode instructions
  components/doc/tailwind/csslayerdoc.js
  components/lib/inputtext/__snapshots__/InputText.spec.js.snap
  package-lock.json
  package.json
Labels: Core Team

#6335 Fix #6333: ButtonGroup add children to Typescript
  components/lib/buttongroup/buttongroup.d.ts
Labels: Core Team

#6337 Change Vue to React in docs and URLs
  components/doc/accordion/templatedoc.js
  components/doc/contextmenu/commanddoc.js
  components/doc/dialog/templatedoc.js
  components/doc/megamenu/templatedoc.js
  components/doc/menubar/templatedoc.js
  components/doc/messages/customicon.js
  components/doc/panel/templatedoc.js
  components/doc/sidebar/headlessdoc.js
  components/doc/sidebar/templatedoc.js
  components/doc/stepper/pt/wireframe.js
  components/doc/tabmenu/templatedoc.js
  components/doc/tabview/templatedoc.js
  components/doc/toolbar/customdoc.js
  components/lib/stepperpanel/stepperpanel.d.ts
Labels: Core Team

#6320 Fix #6288: MultiSelect focus checkbox on focus of list item
  components/lib/multiselect/MultiSelectItem.js
Labels: Core Team

#6258 Fix #6257: InputNumber SHIFT key fix
  components/lib/inputnumber/InputNumber.js
Labels: Core Team

#6332 Fix #6275: InputNumber restore Android usage
  components/lib/inputnumber/InputNumber.js
Labels: Core Team

#6164 Fix #6163: p-hidden-accessible modernization
  components/lib/componentbase/ComponentBase.js
Labels: Status: Discussion, Component: Accessibility, Core Team

#6319 Fix #6305: Multiselect proper scrollIntoView handling
  components/lib/multiselect/MultiSelect.js
Labels: Core Team

#6309 Set key to undefined so index get correct value when creating list items
  components/lib/autocomplete/AutoCompletePanel.js
Labels: Status: Pending Review

#6270 fix: primefaces #6269, Dropdown: (accessiblility) cannot access and clear the selected input using using keyboard
  components/lib/dropdown/Dropdown.js
Labels: Status: Pending Review

#6348 Fix unit tests
  components/lib/blockui/__snapshots__/BlockUI.spec.js.snap
  components/lib/scrollpanel/__snapshots__/ScrollPanel.spec.js.snap
Labels: Component: Test

#6347 fix: #6312 #6346 Tailwind classes for inputswitch and checkbox as styling is broken
  components/doc/checkbox/theming/tailwinddoc.js
  components/doc/inputswitch/theming/tailwinddoc.js
  components/lib/passthrough/tailwind/index.js
Labels: Component: Tailwind

#6354 Fix #6353: Sidebar doc fix
  components/doc/sidebar/headlessdoc.js
Labels: Core Team

#6361 Fix #6358: InputOtp fix typescript case
  components/lib/inputotp/package.json
Labels: Core Team

#6362 Fix #6359: Stepper proper forwardRef
  components/lib/stepper/StepperContent.js
  components/lib/stepper/StepperHeader.js
  components/lib/stepper/StepperSeparator.js
  components/lib/stepperpanel/StepperPanel.js
Labels: Core Team

#6363 Fix Stepper demos
  components/doc/stepper/basicdoc.js
  components/doc/stepper/lineardoc.js
  components/doc/stepper/verticaldoc.js
Labels: Core Team

#6368 Revert typedoc
  package-lock.json
  package.json
Labels: Typescript

#6383 Fix #6382: InputOtp wrong import
  components/lib/inputotp/InputOtp.js
Labels: Core Team

#6388 Add missing children prop in FloatLabel.d.ts
  components/lib/floatlabel/FloatLabel.d.ts
Labels: Typescript

#6218 Fix/#6216 MultiSelect - SelectionLimit issue
  components/lib/multiselect/MultiSelect.js
Labels: Type: Bug

#6374 Fix #6316: fixed issue on selecting option by key event when using optionValue prop
  components/lib/dropdown/Dropdown.js
Labels: Type: Bug

#6360 Fix #6357: typescript definition for ButtonGroup
  components/lib/buttongroup/buttongroup.d.ts
Labels: Typescript

#6395 Fix #6393: Locale prevent prototype pollution
  components/lib/api/Locale.js
  components/lib/hooks/useLocale.js
Labels: Type: Security, Core Team

#6386 Fix #6379: Showcase examples use IconField
  components/doc/datatable/filter/advanceddoc.js
  components/doc/datatable/filter/basicdoc.js
  components/doc/datatable/filter/customdoc.js
  components/doc/datatable/samples/customersdoc.js
  components/doc/datatable/samples/productsdoc.js
  components/doc/datatable/statefuldoc.js
  components/doc/datatable/theming/tailwinddoc.js
  components/doc/toolbar/basicdoc.js
  components/doc/treetable/filterdoc.js
Labels: Core Team

#6400 FileUpload: add missing type definition for cancelIcon
  components/lib/fileupload/fileupload.d.ts
Labels: Typescript

#6401 Fix #6399: DataTable custom filter example
  components/doc/datatable/filter/customdoc.js
Labels: Component: Documentation, Core Team

#6356 Fix #6334: typescript definition for Stepper and StepperPanel
  components/lib/stepper/stepper.d.ts
  components/lib/stepperpanel/stepperpanel.d.ts
Labels: Typescript

#6365 AutoComplete: Fix the issue of passing an undefined key while rendering lists.
  components/lib/autocomplete/AutoCompletePanel.js
Labels: Type: Bug

#6406 fix: #6405 Fix Tailwind theme for TriStateCheckbox
  components/doc/tristatecheckbox/theming/tailwinddoc.js
  components/lib/passthrough/tailwind/index.js
  components/lib/tristatecheckbox/TriStateCheckbox.js
Labels: Component: Tailwind

#6412 Fix #6404: Password fix invalid/variant props
  components/lib/password/password.d.ts
Labels: Typescript, Core Team

#6421 Fix #6420: Added Fragment at doc
  components/doc/iconfield/basicdoc.js
Labels: Component: Documentation

#6433 Fix 'updateTokens' to change tokens value
  components/lib/inputotp/InputOtp.js
Labels: Type: Bug

#6449 Fix #6442: TabView round scrollLeft like PrimeVue
  components/lib/tabview/TabView.js
Labels: Core Team

#6436 TreeTable: call customer sortFunction for column set as sortField
  components/lib/treetable/TreeTable.js
Labels: Type: Bug

#6378 Fix #6376: Typescript boolean instead of false
  components/lib/datatable/datatable.d.ts
  components/lib/dropdown/dropdown.d.ts
  components/lib/multiselect/multiselect.d.ts
Labels: Typescript, Core Team

#6460 added data-pc-section="toggler" to the toggler relates to #6307
  components/doc/tree/templatedoc.js
Labels: Type: Bug

#6458 Fix #6448: Dialog onHide prop call
  components/lib/dialog/Dialog.js
Labels: Type: Enhancement

#6465 Fix #6464: PrimeIcons v7 constants
  components/lib/api/PrimeIcons.js
Labels: Core Team

#6472 VirtualScroller/Ripple TS updates
  components/lib/api/api.d.ts
  components/lib/ripple/ripple.d.ts
  components/lib/virtualscroller/virtualscroller.d.ts
Labels: Typescript, Core Team

#6471 Fix #6468: TreeSelect header fix
  components/lib/treeselect/TreeSelect.js
Labels: Type: Bug

#6463 Fix #6462: StepperHeader add type button
  components/lib/stepper/StepperHeader.js
Labels: Type: Bug

#6453 Fix #6451: OverlayPanel add isVisible method to external API
  components/lib/overlaypanel/OverlayPanel.js
  components/lib/overlaypanel/overlaypanel.d.ts
Labels: Core Team

#6428 Fix #6427: Chips respect removable function
  components/lib/chips/Chips.js
Labels: Core Team

#6411 Fix #6408: TreeSelect pass emptyMessage to Tree
  components/lib/treeselect/TreeSelect.js
Labels: Core Team

#6390 Fix #6389: Passthrough accordiontab not tab
  components/doc/accordion/theming/tailwinddoc.js
  components/lib/accordion/Accordion.js
  components/lib/accordion/AccordionBase.js
  components/lib/accordion/accordion.d.ts
  components/lib/passthrough/tailwind/index.js
  components/lib/tabview/tabview.d.ts
Labels: Core Team

#6367 Fix #6366: ColumnFilter proper ID handling
  components/lib/datatable/ColumnFilter.js
Labels: Core Team

#6355 Fix #6340: MeterGroup minor refactor similar to other components
  components/lib/metergroup/MeterGroup.js
Labels: Core Team

#6485 Fix #6231: Checkbox onClick TS def
  components/lib/checkbox/checkbox.d.ts
Labels: Core Team

#6350 Fix #6339: Stepper add p-component to Stepper action
  components/lib/stepper/StepperBase.js
Labels: Core Team

#6484 Fix #6481: KeyFilter handle AZERTY and dead keys
  components/lib/keyfilter/KeyFilter.js
Labels: Core Team

#6375 Fix #6148: fixed the issue with the home separator if home prop is null/undefined
  components/lib/breadcrumb/BreadCrumb.js
Labels: Type: Bug

#6429 Fix #5960: Quill 2.0.0 support
  components/doc/editor/accessibilitydoc.js
  components/doc/editor/basicdoc.js
  components/doc/editor/readonlydoc.js
  components/doc/editor/templatedoc.js
  components/doc/editor/theming/tailwinddoc.js
  components/lib/editor/Editor.js
  components/lib/editor/Editor.spec.js
  package-lock.json
  package.json
Labels: Core Team

#6430 Fix #6124 : Dropdown navigation like PrimeVue
  components/lib/dropdown/Dropdown.js
  components/lib/dropdown/DropdownPanel.js
Labels: Type: Bug, Status: Pending Test

#6452 Fix #6123: Dropdown scroll into view on focus
  components/lib/dropdown/Dropdown.js
Labels: Core Team, Status: Pending Test

#6381 Fix #5858: Menu align focus with PrimeVue
  components/lib/menu/Menu.js
Labels: Core Team, Status: Pending Test

#6447 Fix #6445: Calendar updateViewDate fix
  components/lib/calendar/Calendar.js
Labels: Status: Pending Test

#6486 Fix #6475: Stepper add get/set active step
  components/lib/stepper/Stepper.js
  components/lib/stepper/stepper.d.ts
Labels: Core Team

#6435 Fix #6095: Dialog refactor using FocusTrap
  components/lib/dialog/Dialog.js
Labels: Core Team, Status: Pending Test

#6493 Fix #6396: Password use IconField for toggle mask
  components/lib/password/Password.js
Labels: Core Team, Status: Pending Test

#6488 Fix #6489: add menu context to menu
  components/doc/common/apidoc/index.json
  components/lib/menu/Menu.js
  components/lib/menu/menu.d.ts
Labels: Status: Pending Test

#6504 Fix #6503: remove unused codes
  components/lib/accordion/Accordion.js
Labels: Type: Enhancement
