Repository primefaces/primereact, pull requests merged in 2024-12, with the labels that each got.

#7482 Fix #7368: Unique key prop added to Chips and icons
  components/lib/button/__snapshots__/Button.spec.js.snap
  components/lib/chip/Chip.js
  components/lib/chip/__snapshots__/Chip.spec.js.snap
  components/lib/chips/Chips.js
  components/lib/fieldset/__snapshots__/Fieldset.spec.js.snap
  components/lib/message/__snapshots__/Message.spec.js.snap
  components/lib/panel/__snapshots__/Panel.spec.js.snap
  components/lib/utils/IconUtils.js
  package-lock.json
  package.json
Labels: Core Team

#7484 Fix #7483: Toast/Message handle remove by id 0
  components/lib/messages/Messages.js
  components/lib/toast/Toast.js
Labels: Core Team

#7485 Fixed incorrect defaultValues for emptyMessage
  components/lib/dropdown/dropdown.d.ts
Labels: Component: Documentation

#7495 Fix #7494: ConfirmDialog do not call onHide if dialog is not visible
  components/lib/confirmdialog/ConfirmDialog.js
Labels: Core Team

#7520 Fix InputTextArea exhaustive deps
  components/lib/inputtextarea/InputTextarea.js
Labels: Core Team

#7530 Fix #7529: Datatable advanced filter allow SPACE key
  components/lib/datatable/HeaderCell.js
Labels: Core Team

#7531 Fix #7514: Dropdown float label fix
  components/lib/dropdown/DropdownBase.js
Labels: Type: Bug

#7532 Fix #7489: ScrollPanel defend against NULL ref
  components/lib/scrollpanel/ScrollPanel.js
Labels: Core Team

#7533 Fix #7436: Button tooltip prevent display order collision
  components/lib/inputtextarea/__snapshots__/InputTextarea.spec.js.snap
  components/lib/tooltip/Tooltip.js
  package-lock.json
  package.json
Labels: Core Team

#7534 Fix #7440: Checkbox pass event for onBlur/onFocus
  components/lib/checkbox/Checkbox.js
Labels: Core Team

#7535 Fix #7409: Dropdown useOptionAsValue do not pass to DOM
  components/lib/dropdown/DropdownBase.js
Labels: Core Team

#7537 Fix #7508: Disabled Menu item display
  components/lib/menu/Menu.js
  components/lib/menu/MenuBase.js
Labels: Core Team
