Repository primefaces/primereact, pull requests merged in 2024-03, with the labels that each got.

#6089 Tooltip fix Typescript def of events
  components/lib/tooltip/tooltip.d.ts
Labels: Typescript, Core Team

#5974 Contrast variant for SplitButton
  components/doc/splitbutton/outlineddoc.js
  components/doc/splitbutton/raiseddoc.js
  components/doc/splitbutton/roundeddoc.js
  components/doc/splitbutton/severitydoc.js
  components/doc/splitbutton/templatedoc.js
  components/doc/splitbutton/theming/tailwinddoc.js
  components/lib/splitbutton/splitbutton.d.ts
  public/themes/arya-blue/theme.css
  public/themes/arya-green/theme.css
  public/themes/arya-orange/theme.css
  public/themes/bootstrap4-dark-blue/theme.css
  public/themes/bootstrap4-light-blue/theme.css
  public/themes/fluent-light/theme.css
  public/themes/lara-dark-amber/theme.css
  public/themes/lara-dark-blue/theme.css
  public/themes/lara-dark-cyan/theme.css
  public/themes/lara-dark-green/theme.css
  public/themes/lara-dark-indigo/theme.css
  public/themes/lara-dark-pink/theme.css
  public/themes/lara-dark-teal/theme.css
  public/themes/lara-light-amber/theme.css
  public/themes/lara-light-blue/theme.css
  public/themes/lara-light-cyan/theme.css
  public/themes/lara-light-green/theme.css
  public/themes/lara-light-indigo/theme.css
  public/themes/lara-light-pink/theme.css
  public/themes/lara-light-teal/theme.css
  public/themes/luna-amber/theme.css
  public/themes/luna-blue/theme.css
  public/themes/luna-green/theme.css
  public/themes/luna-pink/theme.css
  public/themes/md-dark-indigo/theme.css
  public/themes/md-light-indigo/theme.css
  public/themes/mdc-dark-indigo/theme.css
  public/themes/mdc-light-indigo/theme.css
  public/themes/mira/theme.css
  public/themes/nano/theme.css
  public/themes/nova-accent/theme.css
  public/themes/nova-alt/theme.css
  public/themes/nova/theme.css
  public/themes/rhea/theme.css
  public/themes/saga-blue/theme.css
  public/themes/saga-green/theme.css
  public/themes/saga-orange/theme.css
  public/themes/soho-dark/theme.css
  public/themes/soho-light/theme.css
  public/themes/tailwind-light/theme.css
  public/themes/vela-blue/theme.css
  public/themes/vela-green/theme.css
  public/themes/vela-orange/theme.css
  public/themes/viva-dark/theme.css
  public/themes/viva-light/theme.css
Labels: Type: Enhancement

#6106 Fix #6105 - StyleClass: deprecate enterClassName/leaveClassName use e…
  components/lib/styleclass/StyleClass.js
  components/lib/styleclass/StyleClassBase.js
  components/lib/styleclass/styleclass.d.ts
Labels: Type: Enhancement

#6135 Fixed Message tests
  components/lib/message/__snapshots__/Message.spec.js.snap
Labels: Component: Test

#6146 Fix #6145: AutoComplete change event typedef
  components/lib/autocomplete/autocomplete.d.ts
  components/lib/checkbox/Checkbox.js
  components/lib/checkbox/CheckboxBase.js
  components/lib/checkbox/checkbox.d.ts
  components/lib/radiobutton/radiobutton.d.ts
  components/lib/togglebutton/togglebutton.d.ts
  components/lib/tristatecheckbox/tristatecheckbox.d.ts
Labels: Typescript

#6134 Fixed wrong prop in TailwindDoc in Accordion
  components/doc/accordion/theming/tailwinddoc.js
Labels: Component: Documentation

#6112 Fix #6111: ConfirmDialog/Popup 'content' not allowed on DIV
  components/lib/confirmdialog/ConfirmDialogBase.js
  components/lib/confirmpopup/ConfirmPopupBase.js
Labels: Type: Bug, Core Team

#6118 Fix #6116: Tree allow custom node icons
  components/lib/tree/UITreeNode.js
Labels: Type: Bug, Core Team

#6100 Fix #6048: Avoid throwing error while drop on tree component
  components/lib/tree/Tree.js
Labels: Type: Bug

#6096 Fix #6094: Calendar Tailwdind Passthrough
  components/lib/passthrough/tailwind/index.js
Labels: Core Team, Component: Tailwind

#6082 Fix: Tooltip missing type unstyled
  components/lib/tooltip/tooltipoptions.d.ts
Labels: Typescript

#6066 Fix #6063: Menu Tailwind content CSS
  components/doc/menu/theming/tailwinddoc.js
Labels: Core Team, Component: Tailwind

#6034 Fix #6033: Docs Sidebar Headless
  components/doc/sidebar/headlessdoc.js
Labels: Component: Documentation, Core Team

#6040 Fix #6039: splitter bug fixes
  components/lib/splitter/Splitter.js
  components/lib/splitter/__snapshots__/Splitter.spec.js.snap
  components/lib/splitter/splitter.d.ts
Labels: Component: Accessibility

#6114 Fix #6113: MultiSelect loading and loadingIcon types
  components/lib/multiselect/MultiSelectBase.js
  components/lib/multiselect/multiselect.d.ts
Labels: Typescript, Core Team

#6161 Fix #6160: InputText className listed twice
  components/lib/hooks/useDisplayOrder.js
  components/lib/inputtext/InputText.js
  components/lib/inputtext/__snapshots__/InputText.spec.js.snap
Labels: Type: Bug, Core Team

#5997 autoOptionFocus default type is changed as false
  components/lib/dropdown/dropdown.d.ts
  components/lib/listbox/ListBoxBase.js
  components/lib/listbox/listbox.d.ts
  components/lib/multiselect/multiselect.d.ts
Labels: Type: Enhancement

#6003 Dropdown Enhancements - highlightOnSelect - checkmark - PT Options
  components/doc/common/apidoc/index.json
  components/doc/dropdown/checkmarkdoc.js
  components/lib/dropdown/Dropdown.js
  components/lib/dropdown/DropdownBase.js
  components/lib/dropdown/DropdownItem.js
  components/lib/dropdown/DropdownPanel.js
  components/lib/dropdown/dropdown.d.ts
  pages/dropdown/index.js
Labels: Type: Enhancement

#6031 autoOptionFocus property added to Input-like components
  components/doc/common/apidoc/index.json
  components/lib/orderlist/OrderList.js
  components/lib/orderlist/OrderListBase.js
  components/lib/orderlist/orderlist.d.ts
  components/lib/picklist/PickList.js
  components/lib/picklist/PickListBase.js
  components/lib/picklist/picklist.d.ts
Labels: Type: Enhancement

#6157 Fix #6156: Speeddial Tailwind use correct parent prop
  components/lib/passthrough/tailwind/index.js
Labels: Core Team, Component: Tailwind

#6069 Fix #6068: Documentation Fixes
  components/doc/common/apidoc/index.json
  components/doc/organizationchart/basicdoc.js
  components/doc/organizationchart/pt/ptdoc.js
  components/doc/organizationchart/templatedoc.js
  components/doc/tree/eventsdoc.js
  components/doc/treetable/contextmenudoc.js
  components/doc/treetable/filterdoc.js
  components/doc/treetable/scroll/frozencolumnsdoc.js
  components/doc/treetable/scroll/verticaldoc.js
  components/doc/treetable/selection/multipledoc.js
  components/doc/treetable/selection/singledoc.js
  components/lib/sidebar/sidebar.d.ts
Labels: Component: Documentation

#6158 Fix #6047:InputNumber remove onKeyPress
  components/lib/inputnumber/InputNumber.js
  components/lib/inputnumber/inputnumber.d.ts
Labels: Component: Accessibility, Core Team

#6026 Fix #6024: Panel and Dialog style docs
  components/doc/dialog/theming/styleddoc.js
  components/doc/panel/theming/styleddoc.js
Labels: Component: Documentation, Core Team

#6167 Issue - #5540 - Bugfix: fixed animations not working correctly on TRANSITION.toggleable with tailwind preset
  components/lib/passthrough/tailwind/index.js
Labels: Component: Tailwind

#6169 #6168 fixed, Duplicate key "aria-label" in object literal fixed
  components/lib/datatable/BodyCell.js
Labels: Component: Accessibility

#6051 Fix #6050: Locale TypeScript updates
  components/lib/api/Locale.js
  components/lib/api/api.d.ts
Labels: Typescript, Core Team

#6104 Fix #6101: Slider: event.value in onSlideEnd returns null on touch devices
  components/lib/slider/Slider.js
Labels: Type: Bug

#6122 Fix #6119: Password reset feedback meter when value changes
  components/lib/password/Password.js
Labels: Type: Bug, Core Team

#6128 fix #6054: PanelMenu doesn't expand sub-items
  components/lib/panelmenu/PanelMenuList.js
  components/lib/panelmenu/PanelMenuSub.js
Labels: Type: Bug, Status: Pending Review

#6131 Fix #3155: DataTable Reset of vertical scroll position on select
  components/lib/datatable/TableBody.js
Labels: Type: Bug

#6102 Fix #6067: Editor: onTextChange handler does not reflect updated props
  components/lib/editor/Editor.js
  components/lib/editor/Editor.spec.js
Labels: Type: Bug

#6126 fix: values of Default column in API section is unreadable when darkMode (fixes #6125)
  components/doc/common/docapitable.js
Labels: Component: Documentation

#6090 Fix #6079: useStyle better handling of undefined ID
  components/lib/hooks/useStyle.js
Labels: Type: Bug, Core Team

#6098 Fix #6097: MultiSelect pass selected option to event
  components/lib/multiselect/MultiSelect.js
Labels: Type: Bug, Core Team

#6088 Fix #6086: Chips input component doesn't function properly on mobile devices
  components/lib/chips/Chips.js
  components/lib/chips/chips.d.ts
Labels: Type: Bug

#6045 Fix #6044: Autocomplete reset selectedItem if value cleared
  components/lib/autocomplete/AutoComplete.js
Labels: Type: Bug, Core Team

#6060 Fix #6055: DomHandler incorrect case for computed styles
  components/lib/utils/DomHandler.js
Labels: Type: Bug, Core Team

#6053 Fix #6049: Tree lazy mode crash on arrow right
  components/lib/tree/Tree.js
Labels: Type: Bug, Core Team

#6032 Fix #6027: Dropdown filter and editable
  components/lib/dropdown/Dropdown.js
Labels: Type: Bug, Core Team

#6038 Fix #6037: Image stop click propagation on preview buttons
  components/lib/image/Image.js
Labels: Type: Bug, Core Team

#6036 Fix #6035: Dropdown changing value on press Tab Key
  components/lib/dropdown/Dropdown.js
Labels: Type: Bug, Core Team

#5681 feat:CascadeSelect support scroll in container
  components/lib/cascadeselect/CascadeSelect.js
  components/lib/cascadeselect/CascadeSelectBase.js
  components/lib/cascadeselect/CascadeSelectSub.js
  components/lib/passthrough/tailwind/index.js
Labels: Type: Enhancement

#6052 Fix #6046, Password: (accessiblility) cannot access toggle button using keyboard
  components/lib/password/Password.js
Labels: Component: Accessibility

#6062 Fix #6061: MultiStateCheckbox className on root element
  components/lib/multistatecheckbox/MultiStateCheckbox.js
Labels: Type: Bug, Core Team

#6188 Fix #6186: readonly to readOnly DOM prop
  components/lib/radiobutton/RadioButton.js
  components/lib/togglebutton/ToggleButton.js
  components/lib/tristatecheckbox/TriStateCheckbox.js
Labels: Core Team

#6189 MenuBar length spelled wrong
  components/lib/menubar/Menubar.js
Labels: Type: Bug

#6177 Fix #6173: TreeSelect emptyMessage allow JSX content
  components/lib/treeselect/TreeSelect.js
  components/lib/treeselect/treeselect.d.ts
Labels: Core Team

#6200 Fix #6197: Checkbox remove defaultChecked property
  components/lib/checkbox/Checkbox.js
Labels: Core Team

#6213 fix #6211 DataTable Drag to select doesn't work on any page past page…
  components/lib/datatable/TableBody.js
Labels: Type: Bug

#6202 New component ButtonGroup
  components/doc/button/buttongroupdoc.js
  components/doc/common/apidoc/index.json
  components/lib/buttongroup/ButtonGroup.js
  components/lib/buttongroup/ButtonGroupBase.js
  components/lib/buttongroup/buttongroup.d.ts
  components/lib/buttongroup/package.json
  components/lib/componentbase/ComponentBase.js
  components/lib/dataview/DataViewBase.js
  components/lib/selectbutton/SelectButtonBase.js
  pages/button/index.js
  public/themes/arya-blue/theme.css
  public/themes/arya-green/theme.css
  public/themes/arya-orange/theme.css
  public/themes/bootstrap4-dark-blue/theme.css
  public/themes/bootstrap4-light-blue/theme.css
  public/themes/fluent-light/theme.css
  public/themes/lara-dark-amber/theme.css
  public/themes/lara-dark-blue/theme.css
  public/themes/lara-dark-cyan/theme.css
  public/themes/lara-dark-green/theme.css
  public/themes/lara-dark-indigo/theme.css
  public/themes/lara-dark-pink/theme.css
  public/themes/lara-dark-teal/theme.css
  public/themes/lara-light-amber/theme.css
  public/themes/lara-light-blue/theme.css
  public/themes/lara-light-cyan/theme.css
  public/themes/lara-light-green/theme.css
  public/themes/lara-light-indigo/theme.css
  public/themes/lara-light-pink/theme.css
  public/themes/lara-light-teal/theme.css
  public/themes/luna-amber/theme.css
  public/themes/luna-blue/theme.css
  public/themes/luna-green/theme.css
  public/themes/luna-pink/theme.css
  public/themes/md-dark-indigo/theme.css
  public/themes/md-light-indigo/theme.css
  public/themes/mdc-dark-indigo/theme.css
  public/themes/mdc-light-indigo/theme.css
  public/themes/mira/theme.css
  public/themes/nano/theme.css
  public/themes/nova-accent/theme.css
  public/themes/nova-alt/theme.css
  public/themes/nova/theme.css
  public/themes/rhea/theme.css
  public/themes/saga-blue/theme.css
  public/themes/saga-green/theme.css
  public/themes/saga-orange/theme.css
  public/themes/soho-dark/theme.css
  public/themes/soho-light/theme.css
  public/themes/tailwind-light/theme.css
  public/themes/vela-blue/theme.css
  public/themes/vela-green/theme.css
  public/themes/vela-orange/theme.css
  public/themes/viva-dark/theme.css
  public/themes/viva-light/theme.css
Labels: Core Team

#6214 Fix #6151: fixed maxDate prop validation issue
  components/lib/calendar/Calendar.js
Labels: Type: Bug

#6199 Fix #6194: Datatable rowClassName fixed
  components/lib/datatable/BodyRow.js
Labels: Core Team

#6193 Fix #6192: InputNumber restore Copy and Paste functionality
  components/lib/inputnumber/InputNumber.js
Labels: Type: Bug, Core Team

#6166 Fix #6165: TabView refactor closeIcon like other icons
  components/lib/tabview/TabView.js
  components/lib/tabview/TabViewBase.js
Labels: Core Team

#6025 Fix #6023: Support NumpadEnter
  components/lib/accordion/Accordion.js
  components/lib/calendar/Calendar.js
  components/lib/chip/Chip.js
  components/lib/contextmenu/ContextMenu.js
  components/lib/datatable/BodyCell.js
  components/lib/datatable/BodyRow.js
  components/lib/datatable/HeaderCell.js
  components/lib/dock/Dock.js
  components/lib/dropdown/Dropdown.js
  components/lib/fieldset/Fieldset.js
  components/lib/fileupload/FileUpload.js
  components/lib/galleria/GalleriaItem.js
  components/lib/galleria/GalleriaThumbnails.js
  components/lib/inplace/Inplace.js
  components/lib/inputnumber/InputNumber.js
  components/lib/megamenu/MegaMenu.js
  components/lib/menu/Menu.js
  components/lib/menubar/Menubar.js
  components/lib/speeddial/SpeedDial.js
  components/lib/splitter/Splitter.js
  components/lib/steps/Steps.js
  components/lib/tabmenu/TabMenu.js
  components/lib/tabview/TabView.js
  components/lib/terminal/Terminal.js
  components/lib/tieredmenu/TieredMenu.js
  components/lib/treetable/TreeTableHeader.js
  components/lib/tristatecheckbox/TriStateCheckbox.js
Labels: Type: Bug, Core Team

#5460 Feature: "notIn" mode for Datatable filters
  components/doc/common/apidoc/index.json
  components/lib/api/FilterService.js
  components/lib/api/test/FilterService.spec.js
  components/lib/column/column.d.ts
  components/lib/datatable/datatable.d.ts
  components/lib/picklist/picklist.d.ts
  components/lib/treetable/treetable.d.ts
Labels: Type: Enhancement, Status: Pending Review

#6221 Fix #6220: MultiSelect locale selectionMessage
  components/lib/multiselect/MultiSelect.js
Labels: Core Team

#6224 Fix #6223: RadioButton onChange called twice
  components/lib/checkbox/Checkbox.js
  components/lib/radiobutton/RadioButton.js
Labels: Core Team

#6236 Fix #6233: FilterMatchMode typescript updates
  components/lib/api/api.d.ts
  components/lib/column/column.d.ts
  components/lib/dropdown/dropdown.d.ts
  components/lib/listbox/listbox.d.ts
  components/lib/multiselect/multiselect.d.ts
  components/lib/orderlist/orderlist.d.ts
  components/lib/picklist/picklist.d.ts
Labels: Core Team

#6238 Component structure enhancement
  components/doc/common/apidoc/index.json
  components/lib/column/column.d.ts
  components/lib/datatable/DataTableBase.js
  components/lib/datatable/HeaderCheckbox.js
  components/lib/datatable/RowCheckbox.js
  components/lib/datatable/RowRadioButton.js
  components/lib/multiselect/MultiSelect.js
  components/lib/multiselect/MultiSelectHeader.js
  components/lib/multiselect/MultiSelectPanel.js
  components/lib/slider/Slider.js
Labels: Core Team

#6241 Tree TreeTable Structure Enhancement
  components/lib/tree/Tree.js
  components/lib/tree/TreeBase.js
  components/lib/tree/UITreeNode.js
  components/lib/treetable/TreeTableBase.js
  components/lib/treetable/TreeTableRow.js
  public/themes/arya-blue/theme.css
  public/themes/arya-green/theme.css
  public/themes/arya-orange/theme.css
  public/themes/bootstrap4-dark-blue/theme.css
  public/themes/bootstrap4-dark-purple/theme.css
  public/themes/bootstrap4-light-blue/theme.css
  public/themes/bootstrap4-light-purple/theme.css
  public/themes/fluent-light/theme.css
  public/themes/lara-dark-amber/theme.css
  public/themes/lara-dark-blue/theme.css
  public/themes/lara-dark-cyan/theme.css
  public/themes/lara-dark-green/theme.css
  public/themes/lara-dark-indigo/theme.css
  public/themes/lara-dark-pink/theme.css
  public/themes/lara-dark-teal/theme.css
  public/themes/lara-light-amber/theme.css
  public/themes/lara-light-blue/theme.css
  public/themes/lara-light-cyan/theme.css
  public/themes/lara-light-green/theme.css
  public/themes/lara-light-indigo/theme.css
  public/themes/lara-light-pink/theme.css
  public/themes/lara-light-teal/theme.css
  public/themes/luna-amber/theme.css
  public/themes/luna-blue/theme.css
  public/themes/luna-green/theme.css
  public/themes/luna-pink/theme.css
  public/themes/md-dark-deeppurple/theme.css
  public/themes/md-dark-indigo/theme.css
  public/themes/md-light-deeppurple/theme.css
  public/themes/md-light-indigo/theme.css
  public/themes/mdc-dark-deeppurple/theme.css
  public/themes/mdc-dark-indigo/theme.css
  public/themes/mdc-light-deeppurple/theme.css
  public/themes/mdc-light-indigo/theme.css
  public/themes/mira/theme.css
  public/themes/nano/theme.css
  public/themes/nova-accent/theme.css
  public/themes/nova-alt/theme.css
  public/themes/nova/theme.css
  public/themes/rhea/theme.css
  public/themes/saga-blue/theme.css
  public/themes/saga-green/theme.css
  public/themes/saga-orange/theme.css
  public/themes/soho-dark/theme.css
  public/themes/soho-light/theme.css
  public/themes/tailwind-light/theme.css
  public/themes/vela-blue/theme.css
  public/themes/vela-green/theme.css
  public/themes/vela-orange/theme.css
  public/themes/viva-dark/theme.css
  public/themes/viva-light/theme.css
Labels: Core Team

#6232 Fix #6231: Checkbox typescript and onClick event
  components/lib/checkbox/CheckboxBase.js
  components/lib/checkbox/checkbox.d.ts
Labels: Core Team
