Repository primefaces/primereact, pull requests merged in 2024-07, with the labels that each got.

#6810 Fix #6809: Make sure editable dropdown opens when user types
  DEVELOPMENT.md
  components/doc/common/apidoc/index.json
  components/lib/dropdown/Dropdown.js
Labels: Type: Bug

#6818 Calendar's monthNavigatorTemplate Not Working
  components/lib/dropdown/Dropdown.js
Labels: Type: Bug, Core Team

#6721 Fix #6718: FocusTrap better handling of autoFocus property
  components/lib/button/Button.js
  components/lib/focustrap/FocusTrap.js
Labels: Core Team

#6570 Fix: ListBox keyboard navigation like primevue
  components/lib/listbox/ListBox.js
Labels: Component: Accessibility

#6679 Fix #6291 Checkbox: Component fail to render when
  components/lib/checkbox/Checkbox.js
  components/lib/checkbox/checkbox.d.ts
Labels: Status: Pending Review

#6831 Fix #6822: Refactor Dropdown.js to improve optionLabel and optionValue retrieval
  components/lib/dropdown/Dropdown.js
Labels: Type: Bug

#6832 Fix #6824: Update ToastMessage severity options
  components/lib/toast/toast.d.ts
Labels: Typescript

#6837 Fix #6836: TreeTable onFilter type def
  components/lib/treetable/treetable.d.ts
Labels: Core Team

#6841 Fix: #6820 updating activeStep does not actually change the active step
  components/lib/stepper/Stepper.js
Labels: Type: Bug

#6847 Fix #6845: TreeTableSelectionKeys type def
  components/lib/treetable/treetable.d.ts
Labels: Core Team

#6848 Fix #6842: TreeTable Typescript for page event
  components/lib/treetable/treetable.d.ts
Labels: Core Team

#6849 Fix #6823: Datatable loader unstyled non-boolean attribute warning #6823
  components/lib/datatable/DataTable.js
Labels: Type: Bug

#6850 Fix #6789: PanelMenu typedef for onOpen/onClose
  components/lib/panelmenu/panelmenu.d.ts
Labels: Core Team

#6853 Fix #6852: Sort icons match PrimeVue
  components/lib/icons/sortamountdown/index.js
  components/lib/icons/sortamountupalt/index.js
Labels: Core Team

#6869 Fix #6867: Update z-index for submenu list in MenubarBase.js
  components/lib/menubar/MenubarBase.js
Labels: Type: Bug

#6860 fix #6859 : Re-rendering of Sidebar component
  components/lib/sidebar/Sidebar.js
Labels: Type: Performance

#6871 Fix #6858: Dropdown crashes when label is an empty string
  components/lib/dropdown/Dropdown.js
Labels: Type: Bug

#6885 Revert #6058
  components/lib/dropdown/Dropdown.js
Labels: Core Team

#6884 fix: combine the className props in the Menu separator
  components/lib/menu/Menu.js
Labels: Type: Bug

#6886 Fix #6881: TreeTable onResizeEnd incorrect column value
  components/lib/treetable/treetable.d.ts
Labels: Core Team

#6891 fix: #6888, Tree: inputText's onChange in nodeTemplate does not respond to a space key
  components/lib/tree/UITreeNode.js
Labels: Type: Bug

#6899 Fix #6825: focusOnShow prop in Dialog component
  components/lib/dialog/Dialog.js
Labels: Type: Bug

#6902 Fix #6901: Custom passthrough options for bodyRow
  components/doc/common/apidoc/index.json
  components/lib/datatable/datatable.d.ts
Labels: Typescript

#6921 Fix(Calendar): reset the isOverlayClicked value after overlayVisibleState is set to false.
  components/lib/calendar/Calendar.js
Labels: Type: Bug

#6919 Fix(Calendar): allow the end date to be the same as the start date using input.
  components/lib/calendar/Calendar.js
Labels: Type: Bug

#6926 Fix #6922: Autocomplete fix input passthrough TS
  components/lib/autocomplete/autocomplete.d.ts
Labels: Typescript, Core Team

#6930 Fix #6929: Unstyled prop forwarded to InputText
  components/lib/autocomplete/AutoComplete.js
  components/lib/calendar/Calendar.js
  components/lib/inputnumber/InputNumber.js
  components/lib/mention/Mention.js
  components/lib/multiselect/MultiSelectHeader.js
  components/lib/password/Password.js
Labels: Core Team

#6935 RadioButton: Fix Issue with Pass Through Options
  components/lib/radiobutton/RadioButton.js
  components/lib/radiobutton/RadioButtonBase.js
Labels: Component: Unstyled

#6937 fix #6936: Editor get focus on init and on every value change
  components/lib/editor/Editor.js
Labels: Type: Bug

#6865 overlap icons in the dropdown filter component
  components/lib/dropdown/DropdownBase.js
Labels: Type: Bug, Core Team

#6938 Fix #6922: fix input passthrough TS
  components/lib/calendar/calendar.d.ts
  components/lib/cascadeselect/cascadeselect.d.ts
  components/lib/inputotp/inputotp.d.ts
Labels: Core Team

#6941 Fix #6939: Datatable fix row checkbox/radiobutton PT
  components/lib/column/column.d.ts
  components/lib/datatable/RowCheckbox.js
  components/lib/datatable/RowRadioButton.js
Labels: Core Team

#6954 Update Transitions for unstyled Accordion in tailwinddoc.js
  components/doc/accordion/theming/tailwinddoc.js
Labels: Component: Tailwind

#6959 Fix #6940: Inplace update doc for active and controlled mode
  components/lib/inplace/inplace.d.ts
Labels: Core Team
