Repository primefaces/primereact, pull requests merged in 2024-01, with the labels that each got.

#5674 fix:Ripple and Tabview bugs in Next.js App Router
  components/lib/ripple/Ripple.js
  components/lib/utils/ObjectUtils.js
  public/themes/arya-blue/theme.css
  public/themes/arya-green/theme.css
  public/themes/arya-orange/theme.css
  public/themes/arya-purple/theme.css
  public/themes/bootstrap4-dark-blue/theme.css
  public/themes/bootstrap4-dark-purple/theme.css
  public/themes/bootstrap4-light-blue/theme.css
  public/themes/bootstrap4-light-purple/theme.css
  public/themes/fluent-light/theme.css
  public/themes/lara-dark-amber/theme.css
  public/themes/lara-dark-blue/theme.css
  public/themes/lara-dark-cyan/theme.css
  public/themes/lara-dark-green/theme.css
  public/themes/lara-dark-indigo/theme.css
  public/themes/lara-dark-pink/theme.css
  public/themes/lara-dark-purple/theme.css
  public/themes/lara-dark-teal/theme.css
  public/themes/lara-light-amber/theme.css
  public/themes/lara-light-blue/theme.css
  public/themes/lara-light-cyan/theme.css
  public/themes/lara-light-green/theme.css
  public/themes/lara-light-indigo/theme.css
  public/themes/lara-light-pink/theme.css
  public/themes/lara-light-purple/theme.css
  public/themes/lara-light-teal/theme.css
  public/themes/luna-amber/theme.css
  public/themes/luna-blue/theme.css
  public/themes/luna-green/theme.css
  public/themes/luna-pink/theme.css
  public/themes/md-dark-deeppurple/theme.css
  public/themes/md-dark-indigo/theme.css
  public/themes/md-light-deeppurple/theme.css
  public/themes/md-light-indigo/theme.css
  public/themes/mdc-dark-deeppurple/theme.css
  public/themes/mdc-dark-indigo/theme.css
  public/themes/mdc-light-deeppurple/theme.css
  public/themes/mdc-light-indigo/theme.css
  public/themes/mira/theme.css
  public/themes/nano/theme.css
  public/themes/nova-accent/theme.css
  public/themes/nova-alt/theme.css
  public/themes/nova/theme.css
  public/themes/rhea/theme.css
  public/themes/saga-blue/theme.css
  public/themes/saga-green/theme.css
  public/themes/saga-orange/theme.css
  public/themes/saga-purple/theme.css
  public/themes/soho-dark/theme.css
  public/themes/soho-light/theme.css
  public/themes/tailwind-light/theme.css
  public/themes/vela-blue/theme.css
  public/themes/vela-green/theme.css
  public/themes/vela-orange/theme.css
  public/themes/vela-purple/theme.css
  public/themes/viva-dark/theme.css
  public/themes/viva-light/theme.css
Labels: Type: SSR

#5677 Fix #5676: Dropdown Tailwind disabled item
  components/doc/dropdown/theming/tailwinddoc.js
  components/lib/passthrough/tailwind/index.js
Labels: Core Team

#5680 fix: RadioButton: data selector and Hook Form doc
  components/doc/radiobutton/form/hookformdoc.js
  components/lib/radiobutton/RadioButton.js
Labels: Type: Bug

#5693 Fix #5692: Content is optional
  components/lib/confirmpopup/confirmpopup.d.ts
  components/lib/dialog/dialog.d.ts
  components/lib/sidebar/sidebar.d.ts
  components/lib/toast/toast.d.ts
Labels: Core Team

#5566 feat #5246: add styleContainer option for PrimeReactContext
  components/doc/common/apidoc/index.json
  components/doc/configuration/appendtodoc.js
  components/doc/configuration/stylecontainer.js
  components/lib/api/PrimeReactContext.js
  components/lib/api/api.d.ts
  components/lib/carousel/Carousel.js
  components/lib/cascadeselect/CascadeSelect.js
  components/lib/contextmenu/ContextMenu.js
  components/lib/datatable/DataTable.js
  components/lib/dialog/Dialog.js
  components/lib/galleria/GalleriaThumbnails.js
  components/lib/hooks/useStyle.js
  components/lib/megamenu/MegaMenu.js
  components/lib/orderlist/OrderList.js
  components/lib/overlaypanel/OverlayPanel.js
  components/lib/picklist/PickList.js
  components/lib/tieredmenu/TieredMenu.js
  components/lib/utils/DomHandler.js
  components/lib/utils/utils.d.ts
  pages/configuration/index.js
Labels: Type: Enhancement

#5698 Fix #5697: Revert ConfirmDialog fix
  components/lib/confirmdialog/ConfirmDialog.js
Labels: Core Team

#5705 Fix #5704: Image error on mask click
  components/lib/image/Image.js
Labels: Core Team

#5726 fix: fix tiered menu break in demo page
  components/lib/tieredmenu/TieredMenuSub.js
Labels: Type: Bug

#5721 Form Components: Convert class selector to data selector
  components/lib/dropdown/Dropdown.js
  components/lib/dropdown/DropdownBase.js
  components/lib/dropdown/DropdownPanel.js
  components/lib/listbox/ListBoxItem.js
  components/lib/mention/Mention.js
  components/lib/mention/MentionBase.js
  components/lib/mention/mention.d.ts
  components/lib/multiselect/MultiSelect.js
  components/lib/passthrough/tailwind/index.js
  components/lib/tree/UITreeNode.js
  components/lib/treeselect/TreeSelect.js
Labels: Component: Passthrough

#5731 Fix #5719: Calendar paste 12:01 AM
  components/doc/button/linkdoc.js
  components/doc/calendar/icondoc.js
  components/doc/panel/templatedoc.js
  components/doc/ripple/customdoc.js
  components/doc/toolbar/customdoc.js
  components/lib/calendar/Calendar.js
Labels: Core Team

#5734 fix:InputNumber: 0 Decimal Entry Issue using Currency Mode
  components/lib/inputnumber/InputNumber.js
Labels: Type: Bug

#5733 fix: Datatable text will be selected when resized
  components/lib/datatable/DataTable.js
Labels: Type: Enhancement

#5742 fix: fix missing full screen attribute
  components/doc/sidebar/fullscreendoc.js
Labels: Component: Documentation

#5738 fix: InputNumber: Pos1/End places caret before/after prefix/postfix
  components/lib/inputnumber/InputNumber.js
Labels: Type: Bug

#5737 fix: PickList require dataKey
  components/doc/picklist/basicdoc.js
  components/doc/picklist/filterdoc.js
  components/doc/picklist/pt/ptdoc.js
  components/doc/picklist/theming/tailwinddoc.js
  components/lib/picklist/picklist.d.ts
Labels: Type: Bug

#5732 Fix #4089: Orderlist require dataKey
  components/doc/orderlist/basicdoc.js
  components/doc/orderlist/dragdropdoc.js
  components/doc/orderlist/filterdoc.js
  components/doc/orderlist/pt/ptdoc.js
  components/doc/orderlist/theming/tailwinddoc.js
  components/lib/orderlist/orderlist.d.ts
Labels: Type: Bug

#5744 Fix #5743: TabView default scrollbutton state
  components/lib/tabview/TabView.js
Labels: Core Team

#5746 Fix #5315: TreeTable header alignment
  components/lib/treetable/TreeTableBase.js
Labels: Core Team

#5748 Fix #5556: DT Editor Cannot update a component while rendering a diff…
  components/lib/datatable/BodyCell.js
Labels: Core Team

#5749 Fix #5640: Column dynamically evaluate rowEditor
  components/lib/column/column.d.ts
Labels: Typescript

#5758 Fix #5757: Accordion error reading disabled
  components/lib/accordion/Accordion.js
Labels: Core Team

#5762 Fix #5760: Locale setup docs
  components/doc/configuration/locale/setuplocaledoc.js
  pages/configuration/index.js
Labels: Core Team

#5763 Fix #5551: ConfirmDialog responsive example
  components/doc/confirmdialog/responsivedoc.js
  pages/confirmdialog/index.js
Labels: Component: Documentation

#5764 Fix #5747: InputMask caret() null checking
  components/lib/inputmask/InputMask.js
Labels: Core Team

#5770 Fix #5767: Global Escape key allow duplicate overlays
  components/lib/cascadeselect/CascadeSelect.js
  components/lib/confirmpopup/ConfirmPopup.js
  components/lib/dialog/Dialog.js
  components/lib/hooks/useDisplayOrder.js
  components/lib/hooks/useGlobalOnEscapeKey.js
  components/lib/menu/Menu.js
  components/lib/overlaypanel/OverlayPanel.js
  components/lib/password/Password.js
  components/lib/sidebar/Sidebar.js
  components/lib/slidemenu/SlideMenu.js
  components/lib/speeddial/SpeedDial.js
  components/lib/splitbutton/SplitButton.js
Labels: Core Team

#5772 Fix #5771: Image mask click handling
  components/lib/image/Image.js
Labels: Core Team

#5776 Fix:ConfirmDialog：confirmDialog method in unstyled mode, the pop-up w…
  components/lib/confirmdialog/ConfirmDialog.js
Labels: Type: Bug

#5779 Fix #5777: PanelMenu fix when strictmode = false
  components/lib/panelmenu/PanelMenu.js
  components/lib/panelmenu/PanelMenuList.js
  components/lib/panelmenu/PanelMenuSub.js
Labels: Core Team

#5792 Fix #5785: Menu URL handling
  components/lib/menu/Menu.js
Labels: Core Team

#5793 Fix #5785: Menu URL handling
  components/lib/menu/Menu.js
Labels: Core Team

#5801 Fix Calendar TS and tests
  components/lib/calendar/Calendar.spec.js
  components/lib/calendar/calendar.d.ts
Labels: Core Team

#5797 fix:Calendar: timeOnly Today button should be Now
  components/lib/api/Locale.js
  components/lib/api/api.d.ts
  components/lib/calendar/Calendar.js
Labels: Type: Enhancement

#5803 Fix #5802: Allows clear filter button to render without filterMenu button
  components/lib/datatable/ColumnFilter.js
Labels: Type: Bug

#5806 Fix #5802: ShowClearButton consistency
  components/lib/datatable/ColumnFilter.js
Labels: Type: Bug

#5810 Fix #5809: IntersectionObserver TS def
  components/lib/hooks/hooks.d.ts
Labels: Core Team

#5820 Fix #5818: Editor missing unordered list icon
  components/lib/editor/Editor.js
Labels: Core Team

#5823 Fix #5817: PanelMenu respect item.expanded prop
  components/lib/panelmenu/PanelMenu.js
Labels: Core Team

#5826 Fix #5817: PanelMenu respect item.expanded prop
  components/lib/panelmenu/PanelMenu.js
Labels: Core Team

#5825 fix: #5824, Chips: Separator by new line doesn't work by pasting value
  components/lib/chips/Chips.js
Labels: Type: Bug

#5828 Fix #5827: MenuBar respect menu id
  components/lib/menubar/MenubarSub.js
Labels: Core Team

#5831 Clean-up documentation errors
  components/doc/tieredmenu/popupdoc.js
Labels: Component: Documentation

#5835 Fix #5834: Sidebar content default property
  components/lib/sidebar/SidebarBase.js
Labels: Core Team

#5840 Fix #5166: Carousel responsive options fix
  components/lib/carousel/Carousel.js
Labels: Core Team

#5844 Fix useMove demo
  components/doc/hooks/usemove/verticaldoc.js
Labels: Component: Documentation

#5845 Update Tailwind setup
  components/doc/tailwind/unstyledmode/setupdoc.js
Labels: Component: Documentation

#5848 Fix #5847: Dropdown typescript loading/icon
  components/lib/dropdown/dropdown.d.ts
Labels: Core Team

#5852 Fix #5849: Splitter improve ARIA accessibility
  components/doc/splitter/accessibilitydoc.js
  components/lib/splitter/Splitter.js
  components/lib/splitter/__snapshots__/Splitter.spec.js.snap
  components/lib/splitter/splitter.d.ts
Labels: Core Team

#5853 Fix #5849: Splitter improve ARIA accessibility
  components/lib/splitter/Splitter.js
  components/lib/splitter/__snapshots__/Splitter.spec.js.snap
Labels: Core Team

#5856 Fix #5854: Galleria onShow/onHide warnings
  components/lib/galleria/GalleriaBase.js
Labels: Core Team

#5857 Fix #5855: Dropdown search filtering ignore meta keys
  components/lib/dropdown/Dropdown.js
  components/lib/dropdown/DropdownBase.js
Labels: Core Team

#5859 Fix #5834: Sidebar header default warning
  components/lib/sidebar/SidebarBase.js
Labels: Core Team

#5832 Fix: TypeScript demos are failing in StackBlitz/CodeSandbox
  components/doc/common/codeeditor/templates.js
Labels: Type: Bug, Core Team

#5864 Fix #5863: Calendar enabledDates evaluated last
  components/lib/calendar/Calendar.js
Labels: Core Team

#5867 Fix #5862: Divider not using className
  components/lib/divider/Divider.js
Labels: Core Team
