Repository primefaces/primereact, pull requests merged in 2024-09, with the labels that each got.

#7105 Fix #7102: DataView fix listTemplate typescript def
  components/lib/datatable/DataTable.js
  components/lib/dataview/dataview.d.ts
Labels: Core Team

#7114 Fix #7109: SplitterPanel pass onClick through
  components/lib/splitter/Splitter.js
Labels: Core Team

#7143 Fix #7137: MultiSelect template docs
  components/doc/multiselect/templatedoc.js
Labels: Core Team

#7149 feat: make AdditionalProps argument in IconOptions type optional
  components/lib/utils/utils.d.ts
Labels: Typescript

#7160 Fix #7126 : update Tree TypeScript documentation
  components/lib/tree/tree.d.ts
Labels: Typescript

#7168 Fix #7165: Badge/Tag typescript add secondary and contrast
  components/lib/badge/badge.d.ts
  components/lib/tag/tag.d.ts
Labels: Core Team

#7175 Fixing accessibility issue of dropdown
  components/lib/dropdown/Dropdown.js
  components/lib/dropdown/DropdownItem.js
  components/lib/dropdown/DropdownPanel.js
Labels: Component: Accessibility

#7178 Panel Menu Component highlights bug
  components/lib/panelmenu/PanelMenuList.js
Labels: Type: Bug, Core Team

#7181 fix: Tree missing drag drop functionality
  components/lib/tree/UITreeNode.js
Labels: Type: Bug

#7183 Fix #7182: FloatLabel proper SPAN attributes
  components/lib/floatlabel/floatlabel.d.ts
Labels: Core Team

#7188 Fix #7187: Provide readable input value based on selected option labels
  components/lib/multiselect/MultiSelect.js
Labels: Status: Pending Review

#7203 Fix DomPurify audit warning
  package-lock.json
  package.json
Labels: Core Team

#7213 Fix #7208: Fix Advanced Filter TS Demo
  components/doc/datatable/filter/advanceddoc.js
Labels: Core Team

#7242 Mention: Add show/hide to typescript and docs
  components/lib/mention/mention.d.ts
Labels: Typescript, Core Team

#7256 Fix #7255: Sidebar closeIcon typescript
  components/doc/sidebar/headlessdoc.js
  components/lib/sidebar/sidebar.d.ts
Labels: Core Team

#7263 Fix #7261: Menu separator respect visible property
  components/lib/contextmenu/ContextMenuSub.js
  components/lib/menu/Menu.js
  components/lib/menubar/MenubarSub.js
  components/lib/panelmenu/PanelMenuSub.js
  components/lib/slidemenu/SlideMenuSub.js
  components/lib/tieredmenu/TieredMenuSub.js
Labels: Core Team

#7264 Fix #7259: SplitButton menu passthrough
  components/lib/splitbutton/SplitButton.js
  components/lib/splitbutton/SplitButtonBase.js
  components/lib/tieredmenu/TieredMenu.js
  components/lib/tieredmenu/TieredMenuBase.js
Labels: Core Team

#7273 Fix #7269: TreeTable ignore size attribute
  components/lib/treetable/TreeTable.js
  components/lib/treetable/treetable.d.ts
Labels: Core Team
