Repository primefaces/primereact, pull requests merged in 2024-10, with the labels that each got.

#7290 Fix formatting
  components/lib/tooltip/Tooltip.js
Labels: Core Team

#7302 Fix #7301: Dialog fix aria close label
  components/lib/dialog/Dialog.js
Labels: Core Team

#7193 fix: trigger remove chip event when the chip is visible
  components/lib/multiselect/MultiSelect.js
Labels: Status: Pending Review

#7353 Fix #6633: AutoComplete with selectedItemTemplate
  components/lib/autocomplete/AutoComplete.js
Labels: Core Team

#7352 Fix: CSS Modules documentation (:global selector)
  components/doc/theming/scopedstyling/cssmodulesdoc.js
Labels: Component: Documentation

#7369 Fix #7368: Chips prevent unique key warning
  components/lib/chips/Chips.js
Labels: Core Team
