Repository primefaces/primereact, pull requests merged in 2024-02, with the labels that each got.

#5869 Fix #5868: TieredMenu respect menuitem className
  components/lib/tieredmenu/TieredMenuBase.js
  components/lib/tieredmenu/TieredMenuSub.js
Labels: Core Team

#5839 Enhancement: DataTable accessibility
  components/lib/datatable/BodyCell.js
  components/lib/datatable/BodyRow.js
  components/lib/datatable/ColumnFilter.js
  components/lib/datatable/HeaderCell.js
  components/lib/datatable/HeaderCheckbox.js
  components/lib/datatable/TableBody.js
  components/lib/datatable/TableFooter.js
  components/lib/datatable/TableHeader.js
Labels: Type: Enhancement, Core Team

#5873 Fix #5872: hideOverlaysOnDocumentScrolling docs
  components/doc/configuration/hideoverlaysdoc.js
Labels: Core Team

#5883 Fix #5882: CodeSAndbox/StackBlitz were missing extra files (CSS)
  components/doc/common/codeeditor/templates.js
Labels: Core Team

#5884 Fix #5849: Splitter improve keyboard repeat behavior
  components/lib/splitter/Splitter.js
Labels: Core Team

#5886 Fix #5885: Menu focused state for Tailwind
  components/lib/menu/Menu.js
  components/lib/passthrough/tailwind/index.js
Labels: Core Team

#5881 Fix 5880: Password component unnecessary wrapper
  components/lib/password/Password.js
Labels: Type: Bug

#5894 Fix #5892: Fix Splitter resizePanel method
  components/lib/splitter/Splitter.js
Labels: Core Team

#5895 Fix #5893: JumpToPageInput aria label
  components/lib/paginator/JumpToPageInput.js
  components/lib/paginator/RowsPerPageDropdown.js
Labels: Core Team

#5898 Fix #5830: Calendar panel Tailwind width
  components/lib/calendar/Calendar.js
Labels: Core Team

#5902 Fix #3325: Datatable custom filter demo
  components/doc/datatable/filter/customdoc.js
  pages/datatable/index.js
Labels: Core Team

#5903 Fix #5901: Menu/PanelMenu ripple effect
  components/lib/menu/Menu.js
  components/lib/panelmenu/PanelMenuSub.js
Labels: Core Team

#5912 Fix #5905: Password icon classes and cursor:pointer
  components/lib/password/Password.js
  components/lib/password/PasswordBase.js
Labels: Core Team

#5913 fix for #5830
  components/doc/calendar/theming/tailwinddoc.js
  components/lib/passthrough/tailwind/index.js
Labels: Type: Bug

#5926 Improve TypeScript typings for zIndex option
  components/lib/api/api.d.ts
Labels: Typescript

#5937 Fix #5932: Inline tooltip PT options respected
  components/lib/autocomplete/AutoComplete.js
  components/lib/button/Button.js
  components/lib/checkbox/Checkbox.js
  components/lib/chips/Chips.js
  components/lib/colorpicker/ColorPicker.js
  components/lib/datatable/HeaderCell.js
  components/lib/dropdown/Dropdown.js
  components/lib/inputnumber/InputNumber.js
  components/lib/inputswitch/InputSwitch.js
  components/lib/inputtext/InputText.js
  components/lib/inputtextarea/InputTextarea.js
  components/lib/listbox/ListBox.js
  components/lib/multiselect/MultiSelect.js
  components/lib/multistatecheckbox/MultiStateCheckbox.js
  components/lib/radiobutton/RadioButton.js
  components/lib/rating/Rating.js
  components/lib/selectbutton/SelectButton.js
  components/lib/splitbutton/SplitButton.js
  components/lib/togglebutton/ToggleButton.js
  components/lib/treeselect/TreeSelect.js
  components/lib/tristatecheckbox/TriStateCheckbox.js
Labels: Core Team

#5938 #2424 Improve row edit validation api - add rowIndex to rowEditValida…
  components/doc/common/apidoc/index.json
  components/lib/datatable/BodyRow.js
  components/lib/datatable/datatable.d.ts
Labels: Type: Bug

#5939 Fix #5916: Splitter state storage fix
  components/lib/splitter/Splitter.js
Labels: Core Team

#5933 Fix: 5930 add id to menubar top level prevents focus
  components/lib/menubar/Menubar.js
  components/lib/menubar/MenubarSub.js
Labels: Type: Bug, Core Team

#5949 Fix #5941: Menus consistent handling of URL and command
  components/lib/breadcrumb/BreadCrumb.js
  components/lib/contextmenu/ContextMenuSub.js
  components/lib/megamenu/MegaMenu.js
  components/lib/menubar/MenubarSub.js
  components/lib/panelmenu/PanelMenu.js
  components/lib/slidemenu/SlideMenuSub.js
  components/lib/steps/Steps.js
  components/lib/tabmenu/TabMenu.js
  components/lib/tieredmenu/TieredMenuSub.js
Labels: Core Team

#5952 Fix #5942: Dropdown tabbing
  components/lib/dropdown/Dropdown.js
  components/lib/dropdown/DropdownPanel.js
Labels: Core Team

#5953 Fix #5950: Tree emptyMessage
  components/lib/tree/Tree.js
  components/lib/tree/TreeBase.js
  components/lib/tree/tree.d.ts
Labels: Core Team

#5963 Fix #5962: Datatable column reorder typescript def
  components/lib/datatable/datatable.d.ts
Labels: Core Team

#5967 Fix #5889: BlockUI in unstyled mode
  components/lib/blockui/BlockUI.js
  components/lib/blockui/__snapshots__/BlockUI.spec.js.snap
  components/lib/utils/DomHandler.js
Labels: Core Team

#5968 #5954 Add a test for the sidebar component.
  components/lib/sidebar/Sidebar.spec.js
Labels: Component: Test

#5971 Fix #5970: Calendar hideOnRangeSelection
  components/doc/calendar/rangedoc.js
  components/lib/calendar/Calendar.js
  components/lib/calendar/CalendarBase.js
  components/lib/calendar/calendar.d.ts
Labels: Core Team

#5980 Fix #5972: Toast/Message onRemove have the message
  components/lib/messages/Messages.js
  components/lib/toast/Toast.js
  components/lib/toast/ToastBase.js
Labels: Core Team

#5979 Fix #5976: MenuBar unique key per item
  components/lib/menubar/MenubarSub.js
Labels: Core Team

#5981 Fix #5973: Calendar yearNavigator defaults
  components/lib/calendar/Calendar.js
Labels: Core Team

#5987 Fix #5841: SelectButton styling
  components/lib/selectbutton/SelectButton.js
Labels: Type: Bug

#5989 Fix #3672: Listbox keyboard accessibility
  components/lib/listbox/ListBox.js
  components/lib/listbox/ListBoxItem.js
Labels: Core Team

#5990 Fix #5446: MultiSelect ARIA roles
  components/lib/multiselect/MultiSelect.js
  components/lib/multiselect/MultiSelectHeader.js
Labels: Core Team

#5991 Fix #1413/#5836: Dropdown ScreenReader support
  components/lib/dropdown/Dropdown.js
Labels: Core Team

#5993 Fix #5992: TabMenu unstyled mode correct active index
  components/lib/tabmenu/TabMenu.js
Labels: Core Team

#5994 Fix #5426: Tree items have role="treeitem"
  components/lib/tree/Tree.js
  components/lib/tree/UITreeNode.js
Labels: Core Team

#5995 BodyRows merge rowClassName properly #5983
  components/lib/datatable/BodyRow.js
  components/lib/hooks/useMergeProps.js
Labels: Component: Tailwind

#5996 Fix #5983: MergeProps refactor and optimize
  components/lib/carousel/Carousel.js
  components/lib/colorpicker/ColorPickerPanel.js
  components/lib/componentbase/ComponentBase.js
  components/lib/datatable/BodyRow.js
  components/lib/galleria/Galleria.js
  components/lib/galleria/GalleriaThumbnails.js
  components/lib/hooks/useMergeProps.js
  components/lib/passthrough/index.d.ts
  components/lib/treetable/TreeTableRow.js
  components/lib/utils/MergeProps.js
  components/lib/utils/Utils.js
  components/lib/utils/utils.d.ts
Labels: Core Team

#6005 fix:Dropdown: editable input get console error when optionValue is no…
  components/lib/dropdown/Dropdown.js
Labels: Type: Bug

#6001 Errors when applying DataTable
  components/doc/datatable/samples/productsdoc.js
Labels: Component: Documentation

#6012 Fix #6000: Improved closeOnEscape handling
  components/lib/hooks/useDisplayOrder.js
Labels: Core Team

#6014 Fix #6013: Knob RHF example
  components/doc/knob/form/hookformdoc.js
Labels: Core Team

#6020 Fix #6018: Doc update for editable tree/dt cells
  components/doc/datatable/edit/celleditdoc.js
  components/doc/treetable/editdoc.js
  components/lib/treetable/TreeTableBodyCell.js
Labels: Core Team
