Repository primefaces/primereact, pull requests merged in 2024-05, with the labels that each got.

#6520 Fix #6518: fix optionLabel
  components/lib/dropdown/Dropdown.js
Labels: Type: Bug

#6533 Fix #6501: Datatable expose sorts and filters in ref
  components/lib/datatable/DataTable.js
  components/lib/datatable/datatable.d.ts
Labels: Core Team

#6534 Fix #6528: MeterGroup correct CSS handle style
  components/lib/metergroup/MeterGroup.js
Labels: Core Team

#6546 Stepper fix TS docs to onChangeStep
  components/lib/stepper/stepper.d.ts
Labels: Typescript, Core Team

#6547 Fix #6535: Button as link docs
  components/doc/button/linkdoc.js
Labels: Core Team

#6544 Fix #6536: pt submenu fix
  components/lib/menubar/menubar.d.ts
Labels: Component: Unstyled

#6549 Fix #5804: AccordionTab PT error
  components/lib/accordion/Accordion.js
Labels: Core Team

#6551 Fix #6550: dropdown filter fix
  components/lib/dropdown/Dropdown.js
Labels: Type: Bug

#6563 Fix #6561: fix dropdown label
  components/lib/dropdown/Dropdown.js
Labels: Type: Bug

#6567 Fix #6448: Dialog onHide examples
  .eslintignore
  components/doc/dialog/basicdoc.js
  components/doc/dialog/footerdoc.js
  components/doc/dialog/headlessdoc.js
  components/doc/dialog/longcontentdoc.js
  components/doc/dialog/maximizabledoc.js
  components/doc/dialog/positiondoc.js
  components/doc/dialog/responsivedoc.js
  components/doc/dialog/templatedoc.js
  components/doc/dialog/withoutmodaldoc.js
Labels: Core Team

#6572 fix: use additional condition to verify group header
  components/lib/dropdown/DropdownPanel.js
Labels: Type: Bug

#6582 Add ariaLabel method to Typescript
  components/lib/api/api.d.ts
Labels: Typescript, Core Team

#6577 Fix #6573: add paste key
  components/lib/inputotp/InputOtp.js
Labels: Type: Bug

#6595 Fix #6592: InputOtp respect props.value change
  components/lib/datatable/BodyCell.js
  components/lib/datatable/TableBody.js
  components/lib/inputotp/InputOtp.js
Labels: Core Team

#6596 Fix #6594: Fix typo in Scale doc
  components/doc/theming/scaledoc.js
Labels: Core Team

#6597 Fix #6594: Fix typo in PrimeFlex doc
  components/doc/chart/combodoc.js
  components/doc/theming/primeflexdoc.js
Labels: Core Team

#6598 Fix #6593: Password fix tab ordering of toggle mask
  components/lib/password/Password.js
Labels: Core Team

#6601 Fix typo
  README.md
Labels: Component: Documentation

#6605 Show headless sidebar in all window sizes
  components/doc/sidebar/headlessdoc.js
Labels: Component: Documentation

#6579 Fix #6564: IconOptions typescript updated for FontAwesome
  components/lib/utils/utils.d.ts
Labels: Typescript, Core Team

#6607 PanelMenu MenuItem Id Prop Not Passed
  components/lib/panelmenu/PanelMenu.js
Labels: Type: Bug, Core Team

#6612 Fix #6610: MeterGroup render items in percentage
  components/lib/metergroup/MeterGroup.js
Labels: Core Team

#6566 Fix #6522: Minus sign after all selection - InputNumber
  components/lib/inputnumber/InputNumber.js
Labels: Type: Bug

#6616 Tabview Core Styles Moved to SASS Theme and Removed Inkbar for Lara
  components/lib/tabview/TabViewBase.js
  public/themes/arya-blue/theme.css
  public/themes/arya-green/theme.css
  public/themes/arya-orange/theme.css
  public/themes/bootstrap4-dark-blue/theme.css
  public/themes/bootstrap4-dark-purple/theme.css
  public/themes/bootstrap4-light-blue/theme.css
  public/themes/bootstrap4-light-purple/theme.css
  public/themes/fluent-light/theme.css
  public/themes/lara-dark-amber/theme.css
  public/themes/lara-dark-blue/theme.css
  public/themes/lara-dark-cyan/theme.css
  public/themes/lara-dark-green/theme.css
  public/themes/lara-dark-indigo/theme.css
  public/themes/lara-dark-pink/theme.css
  public/themes/lara-dark-teal/theme.css
  public/themes/lara-light-amber/theme.css
  public/themes/lara-light-blue/theme.css
  public/themes/lara-light-cyan/theme.css
  public/themes/lara-light-green/theme.css
  public/themes/lara-light-indigo/theme.css
  public/themes/lara-light-pink/theme.css
  public/themes/lara-light-teal/theme.css
  public/themes/luna-amber/theme.css
  public/themes/luna-blue/theme.css
  public/themes/luna-green/theme.css
  public/themes/luna-pink/theme.css
  public/themes/md-dark-deeppurple/theme.css
  public/themes/md-dark-indigo/theme.css
  public/themes/md-light-deeppurple/theme.css
  public/themes/md-light-indigo/theme.css
  public/themes/mdc-dark-deeppurple/theme.css
  public/themes/mdc-dark-indigo/theme.css
  public/themes/mdc-light-deeppurple/theme.css
  public/themes/mdc-light-indigo/theme.css
  public/themes/mira/theme.css
  public/themes/nano/theme.css
  public/themes/nova-accent/theme.css
  public/themes/nova-alt/theme.css
  public/themes/nova/theme.css
  public/themes/rhea/theme.css
  public/themes/saga-blue/theme.css
  public/themes/saga-green/theme.css
  public/themes/saga-orange/theme.css
  public/themes/soho-dark/theme.css
  public/themes/soho-light/theme.css
  public/themes/tailwind-light/theme.css
  public/themes/vela-blue/theme.css
  public/themes/vela-green/theme.css
  public/themes/vela-orange/theme.css
  public/themes/viva-dark/theme.css
  public/themes/viva-light/theme.css
Labels: Type: Enhancement, Core Team

#6618 Fix #6614: Chart update TypeScript to inherit DIV
  components/lib/chart/chart.d.ts
Labels: Typescript, Core Team

#6619 Fix: Cannot npm link primereact on local project
  package.json
Labels: Component: Documentation

#6611 Added new capabilities and properties to Column and Dialog
  components/doc/common/apidoc/index.json
  components/lib/column/ColumnBase.js
  components/lib/column/column.d.ts
  components/lib/datatable/BodyCell.js
  components/lib/dialog/Dialog.js
  components/lib/dialog/DialogBase.js
Labels: Type: Bug

#6384 Feat: Stateful TreeTable
  components/doc/common/apidoc/index.json
  components/doc/treetable/statefuldoc.js
  components/lib/datatable/DataTable.js
  components/lib/treetable/TreeTable.js
  components/lib/treetable/TreeTableBase.js
  components/lib/treetable/treetable.d.ts
  components/utils/utils.js
  pages/treetable/index.js
Labels: Type: Enhancement

#6638 Fix #6632 InputOtp keyboard navigation
  components/lib/inputotp/InputOtp.js
Labels: Type: Bug

#6641 Fix:#6141:DataTable:Column: onCellEditComplete is fired twice
  components/lib/datatable/BodyCell.js
Labels: Type: Bug

#6643 Fix #6639: VirtualScroller improve useUpdate comparison
  components/lib/virtualscroller/VirtualScroller.js
Labels: Core Team

#6658 Fix #6657 BodyRow tab key handling
  components/lib/datatable/BodyRow.js
Labels: Type: Bug

#6651 Fix #6648: Tooltip default position to 'right' if undefined
  components/lib/tooltip/Tooltip.js
Labels: Core Team

#6649 Fix #6647: PageLinks use totalPages
  components/lib/paginator/PageLinks.js
Labels: Core Team

#6637 Fix #6636: Add missing components to primereact.all.js
  components/lib/primereact.all.js
Labels: Type: Bug, Core Team

#6645 fix: #6644, Galleria: Galleria image in fullscreen mode not closing on escape button click
  components/lib/galleria/Galleria.js
Labels: Type: Bug

#6646 Fix 6631 DragDrop Tree keyboard navigation
  components/lib/tree/Tree.js
  components/lib/tree/UITreeNode.js
Labels: Status: Pending Review, Component: Accessibility

#6670 fix: Error in type definition
  components/doc/common/apidoc/index.json
  components/lib/inputtext/inputtext.d.ts
  package-lock.json
Labels: Typescript

#6672 fix: emptyMessage prop and default label in unstyled mode
  components/lib/dropdown/Dropdown.js
Labels: Type: Bug

#6676 fix: Types in CalendarPassThroughOptions
  components/doc/common/apidoc/index.json
  components/lib/calendar/calendar.d.ts
Labels: Typescript

#6689 fix: Missing prop in SidebarPassThroughMethodOptions
  components/doc/common/apidoc/index.json
  components/lib/sidebar/sidebar.d.ts
Labels: Typescript

#6687 fix: #6680, Tooltip: Escape key not dismissing tooltip (WCAG 2.1 1.4.13)
  components/doc/common/apidoc/index.json
  components/lib/hooks/useGlobalOnEscapeKey.js
  components/lib/tooltip/Tooltip.js
  components/lib/tooltip/TooltipBase.js
  components/lib/tooltip/tooltipoptions.d.ts
Labels: Type: Bug

#6685 Fix onEditorCallback row data not being updated
  components/lib/datatable/BodyCell.js
Labels: Type: Bug

#6699 Fix: metergroup typos
  components/doc/common/apidoc/index.json
  components/lib/metergroup/MeterGroup.js
  components/lib/metergroup/metergroup.d.ts
Labels: Type: Bug

#6705 Fix #6704: TieredMenu remove aria-level
  components/lib/tieredmenu/TieredMenuSub.js
Labels: Core Team

#6707 Fix #6706: Datatable selection aria locale label
  components/lib/datatable/BodyCell.js
Labels: Core Team

#6703 Fix #6058 Dropdown: Select value with Enter when optionValue is set
  components/lib/dropdown/Dropdown.js
Labels: Type: Bug
