Repository primefaces/primereact, pull requests merged in 2024-08, with the labels that each got.

#6960 Added ((data: any) => string) to dataKey property definition
  components/lib/datatable/datatable.d.ts
Labels: Typescript

#6965 Fix #6964: InputOtp passthrough input correctly
  components/lib/inputotp/InputOtp.js
Labels: Core Team

#6972 Fix #6795: Fix calendar overlay requiring double click on date to select a value when mask is present
  components/lib/calendar/Calendar.js
Labels: Type: Bug

#6974 Fix #6663: Show how to preserve filter object when mixing column and …
  components/doc/datatable/filter/advanceddoc.js
Labels: Component: Documentation

#6977 Fix #6861: Fix failed to decode font
  gulpfile.js
Labels: Type: Bug

#6981 Fix #6978: DT HeaderCheckbox passthrough
  components/lib/datatable/HeaderCheckbox.js
  components/lib/datatable/RowCheckbox.js
  components/lib/datatable/RowRadioButton.js
Labels: Core Team

#6985 fix:#6791:DataTable with Virtual Scroller and Multiselect; onSelectio…
  components/lib/datatable/TableBody.js
Labels: Type: Bug

#6986 fix #6984: calendar does not displays up-to-date value if date is manually entered
  components/lib/calendar/Calendar.js
Labels: Type: Bug

#6990 Fix #6989: Datatable errors in console
  components/lib/datatable/RowTogglerButton.js
  components/lib/datatable/TableHeader.js
  package-lock.json
Labels: Type: Bug, Core Team

#6988 Fixes to undroppable tree nodes
  components/lib/tree/UITreeNode.js
Labels: Type: Bug

#6991 fix:#6987 Dropdown filter freezes screen
  components/lib/dropdown/Dropdown.js
  components/lib/dropdown/DropdownPanel.js
Labels: Type: Performance

#6999 Fix #6997: MenuBar re-render on props.model changes
  components/lib/menubar/Menubar.js
  components/lib/menubar/MenubarSub.js
Labels: Core Team

#7004 6993: fix Editor bullet issue when using Quill 2.0.2
  components/doc/common/codeeditor/templates.js
  components/lib/editor/EditorBase.js
  package-lock.json
Labels: Type: Bug

#7003 Fix #7002: Dropdown improve Android key handling
  components/lib/dropdown/Dropdown.js
Labels: Core Team

#7000 Fix #6995: Key should be reference on element and not spread
  components/doc/slider/filterdoc.js
  components/lib/autocomplete/AutoCompletePanel.js
  components/lib/breadcrumb/BreadCrumb.js
  components/lib/calendar/Calendar.js
  components/lib/carousel/Carousel.js
  components/lib/cascadeselect/CascadeSelectBase.js
  components/lib/chip/Chip.js
  components/lib/chips/Chips.js
  components/lib/datascroller/DataScroller.js
  components/lib/dock/Dock.js
  components/lib/galleria/GalleriaItem.js
  components/lib/galleria/GalleriaThumbnails.js
  components/lib/inputotp/InputOtp.js
  components/lib/listbox/ListBox.js
  components/lib/listbox/ListBoxItem.js
  components/lib/mention/MentionBase.js
  components/lib/menu/Menu.js
  components/lib/menubar/MenubarSub.js
  components/lib/multiselect/MultiSelect.js
  components/lib/multiselect/MultiSelectItem.js
  components/lib/multiselect/MultiSelectPanel.js
  components/lib/panelmenu/PanelMenu.js
  components/lib/panelmenu/PanelMenuSub.js
  components/lib/password/Password.js
  components/lib/rating/Rating.js
  components/lib/speeddial/SpeedDial.js
  components/lib/steps/Steps.js
  components/lib/tabmenu/TabMenu.js
Labels: Core Team

#7005 Avoid droppoints within undroppable node, not around
  components/lib/tree/UITreeNode.js
Labels: Type: Bug

#7019 Fix #7016: Revert CascadeSelect type for input
  components/lib/cascadeselect/cascadeselect.d.ts
Labels: Core Team

#7022 Fix #6996: keep the selected row in its position when it gets focused below…
  components/lib/datatable/TableBody.js
Labels: Type: Bug

#7024 Fix #7023: Toast typescript def for content
  components/lib/toast/toast.d.ts
Labels: Core Team

#7030 Fix missing commas in PrimeReact message examples
  components/doc/messages/severitydoc.js
Labels: Component: Documentation

#7048 Fix #7046: TreeTable typescript for PT row/column
  components/lib/treetable/treetable.d.ts
Labels: Core Team

#7053 Fix #7050: HeaderCheckbox passthrough
  components/lib/datatable/HeaderCell.js
  components/lib/datatable/TableHeader.js
Labels: Core Team

#7051 Fix #6998: add closest check condition to detect handle icon drag.
  components/lib/datatable/TableBody.js
Labels: Type: Bug

#7038 fix: #7037, Dropdown: Cannot change icon when expanding or collapsing options
  components/doc/common/apidoc/index.json
  components/lib/dropdown/Dropdown.js
  components/lib/dropdown/DropdownBase.js
  components/lib/dropdown/dropdown.d.ts
Labels: Status: Pending Review

#7068 Fix #6855: ConfirmDialog group missing from typescript
  components/lib/confirmdialog/confirmdialog.d.ts
  components/lib/panelmenu/PanelMenu.js
  components/lib/panelmenu/PanelMenuSub.js
Labels: Core Team

#7075 Fix #7074: ConfirmDialog - RejectButton classes in unstyled mode are not applied
  components/doc/common/apidoc/index.json
  components/lib/confirmdialog/ConfirmDialog.js
  components/lib/confirmdialog/confirmdialog.d.ts
Labels: Component: Unstyled

#7069 Correct passthrough (pt) implementation for Stepperpanel.
  components/lib/stepper/Stepper.js
  components/lib/stepper/StepperBase.js
  components/lib/stepper/StepperContent.js
  components/lib/stepper/StepperHeader.js
  components/lib/stepper/__snapshots__/Stepper.spec.js.snap
Labels: Status: Pending Review, Component: Unstyled
