Repository primefaces/primereact, pull requests merged in 2024-06, with the labels that each got.

#6710 fix:#6683:DataTable: Tabulation is not working propertly
  components/lib/datatable/BodyCell.js
Labels: Type: Bug

#6719 fix: escape key not working in dialog
  components/lib/dialog/Dialog.js
Labels: Type: Bug

#6728 Fix #6727: InputNumber keydown bugfix
  components/lib/inputnumber/InputNumber.js
Labels: Core Team

#6736 Fix #6735: Datatable respect editMode to determine if editable
  components/lib/datatable/BodyCell.js
Labels: Core Team

#6742 Feat #6740: Add content prop to Menubar component
  components/lib/menubar/menubar.d.ts
Labels: Typescript

#6748 Fix #6746: Fix Calendar onDateSelect function
  components/lib/calendar/Calendar.js
Labels: Type: Bug

#6750 Fix package.json security updates for braces
  package-lock.json
  package.json
Labels: Type: Security, Core Team

#6754 Fix #6749: Fix TreeSelect filter for space key
  components/lib/treeselect/TreeSelect.js
Labels: Type: Bug

#6762 fix: incorrect default value for minFractionDigits when set to null
  components/lib/inputnumber/InputNumber.js
Labels: Type: Bug

#6759 fix: highlight range of month in datePicker
  components/lib/calendar/Calendar.js
Labels: Type: Bug

#6760 fix: highlight range of year in datePicker
  components/lib/calendar/Calendar.js
Labels: Type: Bug

#6764 fix(Tooltip): not dynamically update align when position is mouse
  components/lib/tooltip/Tooltip.js
Labels: Type: Bug

#6767 Fix #6766: Added checks for dragdropScope being defined before conversion
  components/lib/tree/UITreeNode.js
Labels: Type: Bug

#6788 Fix(ColorPicker): apply s and b of previous hsb to hsbValue
  components/lib/colorpicker/ColorPicker.js
Labels: Type: Bug

#6794 Fix #6791: apply year change in Calendar when input changed
  components/lib/calendar/Calendar.js
Labels: Type: Bug

#6797 Fix: #6796 check for visibleOptions existing before looking up the index
  components/lib/dropdown/Dropdown.js
Labels: Type: Bug

#6799 Fix: #6666 onMonthChange prop not being called when user increments / decrements month using arrow buttons.
  components/lib/calendar/Calendar.js
Labels: Type: Bug

#6801 Fix a few typos in markdown files
  CODE_OF_CONDUCT.md
  DEVELOPMENT.md
Labels: Component: Documentation
