Repository primefaces/primereact, pull requests merged in 2025-02, with the labels that each got.

#7679 Fix #7678: MegaMenu change const to let
  components/lib/megamenu/MegaMenu.js
Labels: Core Team

#7683 fix(OrderList): prevent point event on p-ink class
  components/lib/orderlist/OrderListBase.js
Labels: Type: Bug

#7686 fix(InputMask): No mask on start typing
  components/lib/inputmask/InputMask.js
Labels: Type: Bug

#7685 Fix #7684: ConfirmDialog fix onHide param to be single string
  components/lib/confirmdialog/ConfirmDialog.js
  components/lib/utils/ObjectUtils.js
Labels: Type: Bug, Core Team

#7693 Fix wrong types
  components/doc/virtualscroller/griddoc.js
Labels: Component: Documentation

#7695 Fix #7684: ConfirmDialog close/escape report 'cancel' event
  components/lib/confirmdialog/ConfirmDialog.js
Labels: Core Team

#7696 Fix #7692: Menu check all items for visible flag
  components/lib/menu/Menu.js
Labels: Core Team

#7701 fix(Calendar): replace invalid date with a valid one in event
  components/lib/calendar/Calendar.js
Labels: Type: Bug

#7708 Fix #7707: useHandleStyle respect isUnstyled
  components/lib/componentbase/ComponentBase.js
Labels: Core Team

#7711 Fix #7709: Divider only add className once
  components/lib/divider/Divider.js
Labels: Core Team

#7713 Fix #7712: Chip improve onRemove control
  components/lib/chip/Chip.js
  components/lib/chip/chip.d.ts
Labels: Core Team
