Repository primefaces/primereact, pull requests merged in 2025-07, with the labels that each got.

#8124 Update instructions to use yalc
  DEVELOPMENT.md
  package.json
Labels: Component: Documentation

#8125 Dropdown: show emptyMessage when Dropdown with VirtualScroller has no data
  components/lib/dropdown/DropdownPanel.js
Labels: Type: Bug

#7951 DataTable: Fix and Simplify overlay handling in cell edit mode
  components/lib/autocomplete/AutoCompletePanel.js
  components/lib/calendar/CalendarPanel.js
  components/lib/colorpicker/ColorPickerPanel.js
  components/lib/datatable/BodyCell.js
  components/lib/datatable/BodyRow.js
  components/lib/dropdown/DropdownPanel.js
  components/lib/multiselect/MultiSelectPanel.js
Labels: Type: Bug

#8147 Fix #8145: Button icon remove pointer events
  components/lib/componentbase/ComponentBase.js
Labels: Core Team
