Repository primefaces/primereact, pull requests merged in 2025-03, with the labels that each got.

#7763 Fix #7729: SpeedDial allow icon to be clicked
  components/lib/calendar/Calendar.js
  components/lib/dropdown/Dropdown.js
  components/lib/speeddial/SpeedDialBase.js
Labels: Core Team

#7772 Fix type in useTimeout hook docs
  components/doc/hooks/usetimeout/importdoc.js
Labels: Component: Documentation

#7777 Fix #7775: Stepper fix typescript add children
  components/lib/stepper/StepperBase.js
  components/lib/stepper/stepper.d.ts
Labels: Core Team

#7804 Fix #6782: Datatable fix rowExpansion PT prop
  components/lib/datatable/TableBody.js
Labels: Core Team

#7816 Next.js 12.3.5
  package-lock.json
  package.json
Labels: dependencies, javascript

#7821 Fix #7819: MultSelect respect 'selectionMessage' locale
  components/lib/multiselect/MultiSelect.js
  components/lib/multiselect/MultiSelectBase.js
Labels: Core Team

#7823 Fix: #7817 (Autocomplete type issue)
  components/lib/autocomplete/autocomplete.d.ts
Labels: Typescript

#7838 Fix #7837: Datatable Body passthrough options fix
  components/lib/datatable/TableBody.js
Labels: Core Team
