Repository primefaces/primereact, pull requests merged in 2025-01, with the labels that each got.

#7539 Fix #7403: FocusTrap in React19 must not access element.ref
  components/lib/focustrap/FocusTrap.js
Labels: Core Team

#7179 Fix #7180 Screenreader improve hidden accessible
  components/doc/accessibility/waiariadoc.js
  components/doc/message/validationdoc.js
  components/doc/theming/utilsdoc.js
  components/lib/componentbase/ComponentBase.js
  components/lib/multistatecheckbox/MultiStateCheckbox.js
  components/lib/tristatecheckbox/TriStateCheckbox.js
Labels: Component: Accessibility

#7548 Fix #7547: Dropdown/MultiSelect add filterDelay
  components/doc/dropdown/filterdoc.js
  components/doc/multiselect/filterdoc.js
  components/lib/dropdown/Dropdown.js
  components/lib/dropdown/DropdownBase.js
  components/lib/dropdown/dropdown.d.ts
  components/lib/multiselect/MultiSelect.js
  components/lib/multiselect/MultiSelectBase.js
  components/lib/multiselect/multiselect.d.ts
Labels: Core Team

#7549 Fix #6747: Tree/TreeSelect add filterDelay
  components/lib/tree/Tree.js
  components/lib/tree/TreeBase.js
  components/lib/tree/tree.d.ts
  components/lib/treeselect/TreeSelect.js
  components/lib/treeselect/TreeSelectBase.js
  components/lib/treeselect/treeselect.d.ts
Labels: Core Team

#7550 Fix #7545: Datatable fix alignFrozen="right"
  components/lib/datatable/BodyCell.js
Labels: Core Team

#7551 Fix #7499: Tree docs update for filterValue
  components/lib/tree/tree.d.ts
  components/lib/treeselect/treeselect.d.ts
Labels: Core Team

#7554 fix:#7546#Datatable: Sort with multiselect - wrong selection
  components/lib/datatable/DataTable.js
  components/lib/datatable/TableBody.js
Labels: Type: Bug

#7559 Fix #7557: KeyFilter whole word docs fix
  components/doc/keyfilter/regexworddoc.js
Labels: Component: Documentation, Core Team

#7560 Fix #5855: Dropdown ignore ALT key when searching
  components/lib/dropdown/Dropdown.js
Labels: Type: Bug

#7281 fix(breadcrumb): missing padding at the end due to unset display prop…
  components/lib/breadcrumb/BreadCrumbBase.js
Labels: Status: Pending Review

#7282 fix(tree): toggle node when filtering mode
  components/lib/tree/Tree.js
  components/lib/tree/UITreeNode.js
Labels: Status: Pending Review

#7556 Fix(Calendar): Improve type declaration using generic types with default parameters (Fixes #7555)
  components/lib/calendar/calendar.d.ts
Labels: Typescript

#7561 Fix #7513: TreeTable stripedRows fix
  components/lib/treetable/TreeTableBase.js
  components/lib/treetable/TreeTableRow.js
Labels: Core Team

#7562 Fix #7045: MenuItem remove aria-hidden
  components/lib/contextmenu/ContextMenuSub.js
  components/lib/dock/Dock.js
  components/lib/megamenu/MegaMenu.js
  components/lib/menu/Menu.js
  components/lib/menubar/MenubarSub.js
  components/lib/panelmenu/PanelMenuSub.js
  components/lib/tieredmenu/TieredMenuSub.js
Labels: Core Team

#7564 Fix #7522: Autocomplete allow selectedItemTemplate in both modes
  components/doc/autocomplete/templatedoc.js
  components/lib/autocomplete/AutoComplete.js
  components/lib/autocomplete/autocomplete.d.ts
Labels: Core Team

#7568 Fix #7566: hideOverlaysOnDocumentScrolling fix for dialogs
  components/lib/utils/DomHandler.js
  pages/_app.js
Labels: Core Team

#7404 Fix #7333: Picklist: When Items are moved to source or target, they are being still selected.
  components/lib/picklist/PickList.js
Labels: Status: Pending Review

#7570 Fix #7343: Remove aria-hidden as not needed from focusable elements
  components/lib/dropdown/Dropdown.js
  components/lib/multiselect/MultiSelectPanel.js
Labels: Core Team

#7571 Fix #7333: PickList remove selection after move
  components/lib/picklist/PickList.js
Labels: Core Team

#7572 Fix #7504: TreeTable update docs example data
  components/doc/treetable/basicdoc.js
  components/doc/treetable/columntoggledoc.js
  components/doc/treetable/conditionalstyledoc.js
  components/doc/treetable/controlleddoc.js
  components/doc/treetable/dynamiccolumnsdoc.js
  components/doc/treetable/editdoc.js
  components/doc/treetable/filterdoc.js
  components/doc/treetable/reorderdoc.js
  components/doc/treetable/resize/expandmodedoc.js
  components/doc/treetable/resize/fitmodedoc.js
  components/doc/treetable/scroll/frozencolumnsdoc.js
  components/doc/treetable/scroll/horizontaldoc.js
  components/doc/treetable/scroll/verticaldoc.js
  components/doc/treetable/selection/checkboxdoc.js
  components/doc/treetable/selection/eventsdoc.js
  components/doc/treetable/selection/multipledoc.js
  components/doc/treetable/selection/singledoc.js
  components/doc/treetable/sort/multiplecolumnsdoc.js
  components/doc/treetable/sort/singlecolumndoc.js
  components/doc/treetable/statefuldoc.js
  components/doc/treetable/templatedoc.js
Labels: Core Team

#7578 Fix #7576: Dropdown reset focused index on Clear
  components/lib/dropdown/Dropdown.js
Labels: Core Team

#7591 Fix #6008: Tooltip allow onBeforeHide to prevent hiding
  components/lib/tooltip/Tooltip.js
Labels: Core Team

#7607 Fix #7604: Calendar focus error with multiple months
  components/lib/calendar/Calendar.js
Labels: Type: Bug, Core Team

#7650 Calendar: added day, month and year information to date cells
  components/lib/calendar/Calendar.js
Labels: Type: Enhancement

#7651 Fix #7627: DataView fix Paginator passthrough
  components/lib/dataview/DataView.js
Labels: Core Team

#7652 Fix #6336: InputText and Stepper fix Typescript defs
  components/lib/inputtext/inputtext.d.ts
  components/lib/stepper/stepper.d.ts
Labels: Core Team

#7663 Fix #7662: OrderList fix filterPlaceholder
  components/doc/orderlist/filterdoc.js
  components/lib/orderlist/OrderList.js
  components/lib/orderlist/OrderListSubList.js
Labels: Core Team

#7659 Fix node expanded if not filtering
  components/lib/tree/Tree.js
  components/lib/tree/UITreeNode.js
Labels: Type: Bug

#7665 Fix: : Type not Working with Sample Template on InputOtp
  components/doc/inputotp/sampledoc.js
Labels: Component: Documentation
