Repository primefaces/primereact, pull requests merged in 2025-05, with the labels that each got.

#7954 Fix #7953: Datatable export only exportable columns
  components/lib/datatable/DataTable.js
Labels: Core Team

#7967 api: improve typing of locale option key in exported keyed locale functions
  components/lib/api/api.d.ts
Labels: Typescript

#7999 fix: prevent Enter key from clearing selection when no option focused
  components/lib/dropdown/Dropdown.js
Labels: Status: Pending Review

#8024 Fix #8023: Locale include all labels from PrimeLocale
  components/lib/api/Locale.js
  components/lib/hooks/useLocale.js
Labels: Type: Bug, Core Team

#8025 Fix #8022: MultiStateCheckbox remove unnecessary ARIA
  components/lib/multistatecheckbox/MultiStateCheckbox.js
Labels: Core Team
