Repository primefaces/primereact, pull requests merged in 2025-04, with the labels that each got.

#7420 Performance (datatable): avoiding unnecessary re-render of cells of rows with no state-change
  components/lib/datatable/BodyCell.js
  components/lib/datatable/BodyRow.js
  components/lib/datatable/TableBody.js
  components/lib/utils/ObjectUtils.js
  components/lib/utils/utils.d.ts
Labels: Status: Pending Review, Type: Performance

#7858 Re-apply #7545
  components/lib/datatable/BodyCell.js
  package-lock.json
  package.json
Labels: Core Team

#7425 Performance (datatable): limiting re-render for only radiobutton/checkbox cells at row selection
  components/lib/datatable/BodyCell.js
  components/lib/datatable/BodyRow.js
  components/lib/datatable/TableBody.js
  components/lib/utils/ObjectUtils.js
Labels: Status: Pending Review, Type: Performance

#7230 fix #7229: update OrderList scroll position when item is moved
  components/lib/orderlist/OrderList.js
Labels: Status: Pending Review

#7865 Fix #7864: Mention add variant
  components/lib/mention/Mention.js
  components/lib/mention/MentionBase.js
  components/lib/mention/mention.d.ts
Labels: Core Team

#7869 Fix #7849: RadioButton readonly to readOnly
  components/lib/radiobutton/RadioButton.js
  components/lib/radiobutton/radiobutton.d.ts
Labels: Core Team

#7870 Fix #7867: TreeSelect filterDelay fix
  components/lib/treeselect/TreeSelect.js
Labels: Core Team

#7879 Fix #7806: InputOtp add autoFocus
  components/lib/inputotp/InputOtp.js
Labels: Core Team

#7882 fix: #7881, AutoComplete, Dropdown: added missing onOverlayHide prop for panels AutoComplete, Dropdown
  components/lib/autocomplete/AutoComplete.js
  components/lib/dropdown/Dropdown.js
Labels: Type: Bug

#7891 Fix #7890: Calendar refocus input after ESC key
  components/lib/calendar/Calendar.js
Labels: Core Team

#7893 Fix #7892: CascadeSelect loading/loadingIcon typescript def
  components/lib/cascadeselect/cascadeselect.d.ts
Labels: Core Team

#7895 Fix #7894: AutoComplete/Chips do not allow removeItem in readonly
  components/lib/autocomplete/AutoComplete.js
  components/lib/chips/Chips.js
Labels: Core Team

#7904 OverlayPanel fix following scroll
  components/doc/hooks/useoverlaylistener/basicdoc.js
  components/lib/autocomplete/AutoComplete.js
  components/lib/calendar/Calendar.js
  components/lib/cascadeselect/CascadeSelect.js
  components/lib/colorpicker/ColorPicker.js
  components/lib/confirmpopup/ConfirmPopup.js
  components/lib/datatable/ColumnFilter.js
  components/lib/dropdown/Dropdown.js
  components/lib/hooks/useOverlayListener.js
  components/lib/hooks/useOverlayScrollListener.js
  components/lib/mention/Mention.js
  components/lib/menu/Menu.js
  components/lib/multiselect/MultiSelect.js
  components/lib/overlaypanel/OverlayPanel.js
  components/lib/password/Password.js
  components/lib/slidemenu/SlideMenu.js
  components/lib/treeselect/TreeSelect.js
  components/lib/utils/DomHandler.js
  components/lib/utils/utils.d.ts
Labels: Status: Pending Test

#7917 Fix #7911: Chip store unique id
  components/lib/chip/Chip.js
Labels: Core Team

#7923 Fix #7922: MenuBar remove aria-level
  components/lib/menubar/MenubarSub.js
Labels: Core Team

#7940 Fix #5353 Datatable BodyRow docs
  components/lib/datatable/datatable.d.ts
Labels: Core Team
